// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package grpc

import (
	"context"
	"sync"

	"github.com/google/uuid"
	"github.com/zorcal/theapp/backend/internal/core/mdl"
)

// Ensure, that MockedAuthCore does implement AuthCore.
// If this is not the case, regenerate this file with moq.
var _ AuthCore = &MockedAuthCore{}

// MockedAuthCore is a mock implementation of AuthCore.
//
//	func TestSomethingThatUsesAuthCore(t *testing.T) {
//
//		// make and configure a mocked AuthCore
//		mockedAuthCore := &MockedAuthCore{
//			AuthSessionFunc: func(ctx context.Context, userID uuid.UUID, projectID *int) (mdl.AuthSession, error) {
//				panic("mock out the AuthSession method")
//			},
//			RefreshAccessTokenFunc: func(ctx context.Context, rt mdl.RefreshToken) (mdl.AuthTokenPair, error) {
//				panic("mock out the RefreshAccessToken method")
//			},
//			RevokeAllUserRefreshTokensFunc: func(ctx context.Context, userExternalID uuid.UUID) error {
//				panic("mock out the RevokeAllUserRefreshTokens method")
//			},
//			RevokeRefreshTokenFunc: func(ctx context.Context, rt mdl.RefreshToken) error {
//				panic("mock out the RevokeRefreshToken method")
//			},
//			VerifyMagicLinkFunc: func(ctx context.Context, vml mdl.VerifyMagicLink) (mdl.AuthTokenPair, error) {
//				panic("mock out the VerifyMagicLink method")
//			},
//		}
//
//		// use mockedAuthCore in code that requires AuthCore
//		// and then make assertions.
//
//	}
type MockedAuthCore struct {
	// AuthSessionFunc mocks the AuthSession method.
	AuthSessionFunc func(ctx context.Context, userID uuid.UUID, projectID *int) (mdl.AuthSession, error)

	// RefreshAccessTokenFunc mocks the RefreshAccessToken method.
	RefreshAccessTokenFunc func(ctx context.Context, rt mdl.RefreshToken) (mdl.AuthTokenPair, error)

	// RevokeAllUserRefreshTokensFunc mocks the RevokeAllUserRefreshTokens method.
	RevokeAllUserRefreshTokensFunc func(ctx context.Context, userExternalID uuid.UUID) error

	// RevokeRefreshTokenFunc mocks the RevokeRefreshToken method.
	RevokeRefreshTokenFunc func(ctx context.Context, rt mdl.RefreshToken) error

	// VerifyMagicLinkFunc mocks the VerifyMagicLink method.
	VerifyMagicLinkFunc func(ctx context.Context, vml mdl.VerifyMagicLink) (mdl.AuthTokenPair, error)

	// calls tracks calls to the methods.
	calls struct {
		// AuthSession holds details about calls to the AuthSession method.
		AuthSession []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID uuid.UUID
			// ProjectID is the projectID argument value.
			ProjectID *int
		}
		// RefreshAccessToken holds details about calls to the RefreshAccessToken method.
		RefreshAccessToken []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Rt is the rt argument value.
			Rt mdl.RefreshToken
		}
		// RevokeAllUserRefreshTokens holds details about calls to the RevokeAllUserRefreshTokens method.
		RevokeAllUserRefreshTokens []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserExternalID is the userExternalID argument value.
			UserExternalID uuid.UUID
		}
		// RevokeRefreshToken holds details about calls to the RevokeRefreshToken method.
		RevokeRefreshToken []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Rt is the rt argument value.
			Rt mdl.RefreshToken
		}
		// VerifyMagicLink holds details about calls to the VerifyMagicLink method.
		VerifyMagicLink []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Vml is the vml argument value.
			Vml mdl.VerifyMagicLink
		}
	}
	lockAuthSession                sync.RWMutex
	lockRefreshAccessToken         sync.RWMutex
	lockRevokeAllUserRefreshTokens sync.RWMutex
	lockRevokeRefreshToken         sync.RWMutex
	lockVerifyMagicLink            sync.RWMutex
}

// AuthSession calls AuthSessionFunc.
func (mock *MockedAuthCore) AuthSession(ctx context.Context, userID uuid.UUID, projectID *int) (mdl.AuthSession, error) {
	if mock.AuthSessionFunc == nil {
		panic("MockedAuthCore.AuthSessionFunc: method is nil but AuthCore.AuthSession was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		UserID    uuid.UUID
		ProjectID *int
	}{
		Ctx:       ctx,
		UserID:    userID,
		ProjectID: projectID,
	}
	mock.lockAuthSession.Lock()
	mock.calls.AuthSession = append(mock.calls.AuthSession, callInfo)
	mock.lockAuthSession.Unlock()
	return mock.AuthSessionFunc(ctx, userID, projectID)
}

// AuthSessionCalls gets all the calls that were made to AuthSession.
// Check the length with:
//
//	len(mockedAuthCore.AuthSessionCalls())
func (mock *MockedAuthCore) AuthSessionCalls() []struct {
	Ctx       context.Context
	UserID    uuid.UUID
	ProjectID *int
} {
	var calls []struct {
		Ctx       context.Context
		UserID    uuid.UUID
		ProjectID *int
	}
	mock.lockAuthSession.RLock()
	calls = mock.calls.AuthSession
	mock.lockAuthSession.RUnlock()
	return calls
}

// RefreshAccessToken calls RefreshAccessTokenFunc.
func (mock *MockedAuthCore) RefreshAccessToken(ctx context.Context, rt mdl.RefreshToken) (mdl.AuthTokenPair, error) {
	if mock.RefreshAccessTokenFunc == nil {
		panic("MockedAuthCore.RefreshAccessTokenFunc: method is nil but AuthCore.RefreshAccessToken was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Rt  mdl.RefreshToken
	}{
		Ctx: ctx,
		Rt:  rt,
	}
	mock.lockRefreshAccessToken.Lock()
	mock.calls.RefreshAccessToken = append(mock.calls.RefreshAccessToken, callInfo)
	mock.lockRefreshAccessToken.Unlock()
	return mock.RefreshAccessTokenFunc(ctx, rt)
}

// RefreshAccessTokenCalls gets all the calls that were made to RefreshAccessToken.
// Check the length with:
//
//	len(mockedAuthCore.RefreshAccessTokenCalls())
func (mock *MockedAuthCore) RefreshAccessTokenCalls() []struct {
	Ctx context.Context
	Rt  mdl.RefreshToken
} {
	var calls []struct {
		Ctx context.Context
		Rt  mdl.RefreshToken
	}
	mock.lockRefreshAccessToken.RLock()
	calls = mock.calls.RefreshAccessToken
	mock.lockRefreshAccessToken.RUnlock()
	return calls
}

// RevokeAllUserRefreshTokens calls RevokeAllUserRefreshTokensFunc.
func (mock *MockedAuthCore) RevokeAllUserRefreshTokens(ctx context.Context, userExternalID uuid.UUID) error {
	if mock.RevokeAllUserRefreshTokensFunc == nil {
		panic("MockedAuthCore.RevokeAllUserRefreshTokensFunc: method is nil but AuthCore.RevokeAllUserRefreshTokens was just called")
	}
	callInfo := struct {
		Ctx            context.Context
		UserExternalID uuid.UUID
	}{
		Ctx:            ctx,
		UserExternalID: userExternalID,
	}
	mock.lockRevokeAllUserRefreshTokens.Lock()
	mock.calls.RevokeAllUserRefreshTokens = append(mock.calls.RevokeAllUserRefreshTokens, callInfo)
	mock.lockRevokeAllUserRefreshTokens.Unlock()
	return mock.RevokeAllUserRefreshTokensFunc(ctx, userExternalID)
}

// RevokeAllUserRefreshTokensCalls gets all the calls that were made to RevokeAllUserRefreshTokens.
// Check the length with:
//
//	len(mockedAuthCore.RevokeAllUserRefreshTokensCalls())
func (mock *MockedAuthCore) RevokeAllUserRefreshTokensCalls() []struct {
	Ctx            context.Context
	UserExternalID uuid.UUID
} {
	var calls []struct {
		Ctx            context.Context
		UserExternalID uuid.UUID
	}
	mock.lockRevokeAllUserRefreshTokens.RLock()
	calls = mock.calls.RevokeAllUserRefreshTokens
	mock.lockRevokeAllUserRefreshTokens.RUnlock()
	return calls
}

// RevokeRefreshToken calls RevokeRefreshTokenFunc.
func (mock *MockedAuthCore) RevokeRefreshToken(ctx context.Context, rt mdl.RefreshToken) error {
	if mock.RevokeRefreshTokenFunc == nil {
		panic("MockedAuthCore.RevokeRefreshTokenFunc: method is nil but AuthCore.RevokeRefreshToken was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Rt  mdl.RefreshToken
	}{
		Ctx: ctx,
		Rt:  rt,
	}
	mock.lockRevokeRefreshToken.Lock()
	mock.calls.RevokeRefreshToken = append(mock.calls.RevokeRefreshToken, callInfo)
	mock.lockRevokeRefreshToken.Unlock()
	return mock.RevokeRefreshTokenFunc(ctx, rt)
}

// RevokeRefreshTokenCalls gets all the calls that were made to RevokeRefreshToken.
// Check the length with:
//
//	len(mockedAuthCore.RevokeRefreshTokenCalls())
func (mock *MockedAuthCore) RevokeRefreshTokenCalls() []struct {
	Ctx context.Context
	Rt  mdl.RefreshToken
} {
	var calls []struct {
		Ctx context.Context
		Rt  mdl.RefreshToken
	}
	mock.lockRevokeRefreshToken.RLock()
	calls = mock.calls.RevokeRefreshToken
	mock.lockRevokeRefreshToken.RUnlock()
	return calls
}

// VerifyMagicLink calls VerifyMagicLinkFunc.
func (mock *MockedAuthCore) VerifyMagicLink(ctx context.Context, vml mdl.VerifyMagicLink) (mdl.AuthTokenPair, error) {
	if mock.VerifyMagicLinkFunc == nil {
		panic("MockedAuthCore.VerifyMagicLinkFunc: method is nil but AuthCore.VerifyMagicLink was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Vml mdl.VerifyMagicLink
	}{
		Ctx: ctx,
		Vml: vml,
	}
	mock.lockVerifyMagicLink.Lock()
	mock.calls.VerifyMagicLink = append(mock.calls.VerifyMagicLink, callInfo)
	mock.lockVerifyMagicLink.Unlock()
	return mock.VerifyMagicLinkFunc(ctx, vml)
}

// VerifyMagicLinkCalls gets all the calls that were made to VerifyMagicLink.
// Check the length with:
//
//	len(mockedAuthCore.VerifyMagicLinkCalls())
func (mock *MockedAuthCore) VerifyMagicLinkCalls() []struct {
	Ctx context.Context
	Vml mdl.VerifyMagicLink
} {
	var calls []struct {
		Ctx context.Context
		Vml mdl.VerifyMagicLink
	}
	mock.lockVerifyMagicLink.RLock()
	calls = mock.calls.VerifyMagicLink
	mock.lockVerifyMagicLink.RUnlock()
	return calls
}
