// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package grpc

import (
	"context"
	"sync"

	"github.com/google/uuid"
	"github.com/zorcal/theapp/backend/internal/core/mdl"
)

// Ensure, that MockedAuthCore does implement AuthCore.
// If this is not the case, regenerate this file with moq.
var _ AuthCore = &MockedAuthCore{}

// MockedAuthCore is a mock implementation of AuthCore.
//
//	func TestSomethingThatUsesAuthCore(t *testing.T) {
//
//		// make and configure a mocked AuthCore
//		mockedAuthCore := &MockedAuthCore{
//			RefreshAccessTokenFunc: func(ctx context.Context, rawToken string) (mdl.AuthTokenPair, error) {
//				panic("mock out the RefreshAccessToken method")
//			},
//			RevokeAllUserRefreshTokensFunc: func(ctx context.Context, userExternalID uuid.UUID) error {
//				panic("mock out the RevokeAllUserRefreshTokens method")
//			},
//			RevokeRefreshTokenFunc: func(ctx context.Context, rawToken string) error {
//				panic("mock out the RevokeRefreshToken method")
//			},
//			VerifyMagicLinkFunc: func(ctx context.Context, rawToken string) (mdl.AuthTokenPair, error) {
//				panic("mock out the VerifyMagicLink method")
//			},
//		}
//
//		// use mockedAuthCore in code that requires AuthCore
//		// and then make assertions.
//
//	}
type MockedAuthCore struct {
	// RefreshAccessTokenFunc mocks the RefreshAccessToken method.
	RefreshAccessTokenFunc func(ctx context.Context, rawToken string) (mdl.AuthTokenPair, error)

	// RevokeAllUserRefreshTokensFunc mocks the RevokeAllUserRefreshTokens method.
	RevokeAllUserRefreshTokensFunc func(ctx context.Context, userExternalID uuid.UUID) error

	// RevokeRefreshTokenFunc mocks the RevokeRefreshToken method.
	RevokeRefreshTokenFunc func(ctx context.Context, rawToken string) error

	// VerifyMagicLinkFunc mocks the VerifyMagicLink method.
	VerifyMagicLinkFunc func(ctx context.Context, rawToken string) (mdl.AuthTokenPair, error)

	// calls tracks calls to the methods.
	calls struct {
		// RefreshAccessToken holds details about calls to the RefreshAccessToken method.
		RefreshAccessToken []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RawToken is the rawToken argument value.
			RawToken string
		}
		// RevokeAllUserRefreshTokens holds details about calls to the RevokeAllUserRefreshTokens method.
		RevokeAllUserRefreshTokens []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserExternalID is the userExternalID argument value.
			UserExternalID uuid.UUID
		}
		// RevokeRefreshToken holds details about calls to the RevokeRefreshToken method.
		RevokeRefreshToken []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RawToken is the rawToken argument value.
			RawToken string
		}
		// VerifyMagicLink holds details about calls to the VerifyMagicLink method.
		VerifyMagicLink []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RawToken is the rawToken argument value.
			RawToken string
		}
	}
	lockRefreshAccessToken         sync.RWMutex
	lockRevokeAllUserRefreshTokens sync.RWMutex
	lockRevokeRefreshToken         sync.RWMutex
	lockVerifyMagicLink            sync.RWMutex
}

// RefreshAccessToken calls RefreshAccessTokenFunc.
func (mock *MockedAuthCore) RefreshAccessToken(ctx context.Context, rawToken string) (mdl.AuthTokenPair, error) {
	if mock.RefreshAccessTokenFunc == nil {
		panic("MockedAuthCore.RefreshAccessTokenFunc: method is nil but AuthCore.RefreshAccessToken was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		RawToken string
	}{
		Ctx:      ctx,
		RawToken: rawToken,
	}
	mock.lockRefreshAccessToken.Lock()
	mock.calls.RefreshAccessToken = append(mock.calls.RefreshAccessToken, callInfo)
	mock.lockRefreshAccessToken.Unlock()
	return mock.RefreshAccessTokenFunc(ctx, rawToken)
}

// RefreshAccessTokenCalls gets all the calls that were made to RefreshAccessToken.
// Check the length with:
//
//	len(mockedAuthCore.RefreshAccessTokenCalls())
func (mock *MockedAuthCore) RefreshAccessTokenCalls() []struct {
	Ctx      context.Context
	RawToken string
} {
	var calls []struct {
		Ctx      context.Context
		RawToken string
	}
	mock.lockRefreshAccessToken.RLock()
	calls = mock.calls.RefreshAccessToken
	mock.lockRefreshAccessToken.RUnlock()
	return calls
}

// RevokeAllUserRefreshTokens calls RevokeAllUserRefreshTokensFunc.
func (mock *MockedAuthCore) RevokeAllUserRefreshTokens(ctx context.Context, userExternalID uuid.UUID) error {
	if mock.RevokeAllUserRefreshTokensFunc == nil {
		panic("MockedAuthCore.RevokeAllUserRefreshTokensFunc: method is nil but AuthCore.RevokeAllUserRefreshTokens was just called")
	}
	callInfo := struct {
		Ctx            context.Context
		UserExternalID uuid.UUID
	}{
		Ctx:            ctx,
		UserExternalID: userExternalID,
	}
	mock.lockRevokeAllUserRefreshTokens.Lock()
	mock.calls.RevokeAllUserRefreshTokens = append(mock.calls.RevokeAllUserRefreshTokens, callInfo)
	mock.lockRevokeAllUserRefreshTokens.Unlock()
	return mock.RevokeAllUserRefreshTokensFunc(ctx, userExternalID)
}

// RevokeAllUserRefreshTokensCalls gets all the calls that were made to RevokeAllUserRefreshTokens.
// Check the length with:
//
//	len(mockedAuthCore.RevokeAllUserRefreshTokensCalls())
func (mock *MockedAuthCore) RevokeAllUserRefreshTokensCalls() []struct {
	Ctx            context.Context
	UserExternalID uuid.UUID
} {
	var calls []struct {
		Ctx            context.Context
		UserExternalID uuid.UUID
	}
	mock.lockRevokeAllUserRefreshTokens.RLock()
	calls = mock.calls.RevokeAllUserRefreshTokens
	mock.lockRevokeAllUserRefreshTokens.RUnlock()
	return calls
}

// RevokeRefreshToken calls RevokeRefreshTokenFunc.
func (mock *MockedAuthCore) RevokeRefreshToken(ctx context.Context, rawToken string) error {
	if mock.RevokeRefreshTokenFunc == nil {
		panic("MockedAuthCore.RevokeRefreshTokenFunc: method is nil but AuthCore.RevokeRefreshToken was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		RawToken string
	}{
		Ctx:      ctx,
		RawToken: rawToken,
	}
	mock.lockRevokeRefreshToken.Lock()
	mock.calls.RevokeRefreshToken = append(mock.calls.RevokeRefreshToken, callInfo)
	mock.lockRevokeRefreshToken.Unlock()
	return mock.RevokeRefreshTokenFunc(ctx, rawToken)
}

// RevokeRefreshTokenCalls gets all the calls that were made to RevokeRefreshToken.
// Check the length with:
//
//	len(mockedAuthCore.RevokeRefreshTokenCalls())
func (mock *MockedAuthCore) RevokeRefreshTokenCalls() []struct {
	Ctx      context.Context
	RawToken string
} {
	var calls []struct {
		Ctx      context.Context
		RawToken string
	}
	mock.lockRevokeRefreshToken.RLock()
	calls = mock.calls.RevokeRefreshToken
	mock.lockRevokeRefreshToken.RUnlock()
	return calls
}

// VerifyMagicLink calls VerifyMagicLinkFunc.
func (mock *MockedAuthCore) VerifyMagicLink(ctx context.Context, rawToken string) (mdl.AuthTokenPair, error) {
	if mock.VerifyMagicLinkFunc == nil {
		panic("MockedAuthCore.VerifyMagicLinkFunc: method is nil but AuthCore.VerifyMagicLink was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		RawToken string
	}{
		Ctx:      ctx,
		RawToken: rawToken,
	}
	mock.lockVerifyMagicLink.Lock()
	mock.calls.VerifyMagicLink = append(mock.calls.VerifyMagicLink, callInfo)
	mock.lockVerifyMagicLink.Unlock()
	return mock.VerifyMagicLinkFunc(ctx, rawToken)
}

// VerifyMagicLinkCalls gets all the calls that were made to VerifyMagicLink.
// Check the length with:
//
//	len(mockedAuthCore.VerifyMagicLinkCalls())
func (mock *MockedAuthCore) VerifyMagicLinkCalls() []struct {
	Ctx      context.Context
	RawToken string
} {
	var calls []struct {
		Ctx      context.Context
		RawToken string
	}
	mock.lockVerifyMagicLink.RLock()
	calls = mock.calls.VerifyMagicLink
	mock.lockVerifyMagicLink.RUnlock()
	return calls
}
