// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package grpc

import (
	"context"
	"sync"

	"github.com/google/uuid"
	"github.com/zorcal/theapp/backend/internal/core/mdl"
)

// Ensure, that MockedCustomRoleCore does implement CustomRoleCore.
// If this is not the case, regenerate this file with moq.
var _ CustomRoleCore = &MockedCustomRoleCore{}

// MockedCustomRoleCore is a mock implementation of CustomRoleCore.
//
//	func TestSomethingThatUsesCustomRoleCore(t *testing.T) {
//
//		// make and configure a mocked CustomRoleCore
//		mockedCustomRoleCore := &MockedCustomRoleCore{
//			CreateCustomRoleFunc: func(ctx context.Context, cr mdl.CreateCustomRole) (mdl.CustomRole, error) {
//				panic("mock out the CreateCustomRole method")
//			},
//			CustomRoleByIDFunc: func(ctx context.Context, customRoleID uuid.UUID) (mdl.CustomRole, error) {
//				panic("mock out the CustomRoleByID method")
//			},
//			CustomRolesFunc: func(ctx context.Context, pageSize int, pageOffset int) ([]mdl.CustomRole, int, error) {
//				panic("mock out the CustomRoles method")
//			},
//			DeleteCustomRoleFunc: func(ctx context.Context, customRoleID uuid.UUID) error {
//				panic("mock out the DeleteCustomRole method")
//			},
//			ModifyCustomRolePermissionsFunc: func(ctx context.Context, mrp mdl.ModifyCustomRolePermissions) (mdl.CustomRole, error) {
//				panic("mock out the ModifyCustomRolePermissions method")
//			},
//			UpdateCustomRoleFunc: func(ctx context.Context, ur mdl.UpdateCustomRole) (mdl.CustomRole, error) {
//				panic("mock out the UpdateCustomRole method")
//			},
//		}
//
//		// use mockedCustomRoleCore in code that requires CustomRoleCore
//		// and then make assertions.
//
//	}
type MockedCustomRoleCore struct {
	// CreateCustomRoleFunc mocks the CreateCustomRole method.
	CreateCustomRoleFunc func(ctx context.Context, cr mdl.CreateCustomRole) (mdl.CustomRole, error)

	// CustomRoleByIDFunc mocks the CustomRoleByID method.
	CustomRoleByIDFunc func(ctx context.Context, customRoleID uuid.UUID) (mdl.CustomRole, error)

	// CustomRolesFunc mocks the CustomRoles method.
	CustomRolesFunc func(ctx context.Context, pageSize int, pageOffset int) ([]mdl.CustomRole, int, error)

	// DeleteCustomRoleFunc mocks the DeleteCustomRole method.
	DeleteCustomRoleFunc func(ctx context.Context, customRoleID uuid.UUID) error

	// ModifyCustomRolePermissionsFunc mocks the ModifyCustomRolePermissions method.
	ModifyCustomRolePermissionsFunc func(ctx context.Context, mrp mdl.ModifyCustomRolePermissions) (mdl.CustomRole, error)

	// UpdateCustomRoleFunc mocks the UpdateCustomRole method.
	UpdateCustomRoleFunc func(ctx context.Context, ur mdl.UpdateCustomRole) (mdl.CustomRole, error)

	// calls tracks calls to the methods.
	calls struct {
		// CreateCustomRole holds details about calls to the CreateCustomRole method.
		CreateCustomRole []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Cr is the cr argument value.
			Cr mdl.CreateCustomRole
		}
		// CustomRoleByID holds details about calls to the CustomRoleByID method.
		CustomRoleByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// CustomRoleID is the customRoleID argument value.
			CustomRoleID uuid.UUID
		}
		// CustomRoles holds details about calls to the CustomRoles method.
		CustomRoles []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// PageSize is the pageSize argument value.
			PageSize int
			// PageOffset is the pageOffset argument value.
			PageOffset int
		}
		// DeleteCustomRole holds details about calls to the DeleteCustomRole method.
		DeleteCustomRole []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// CustomRoleID is the customRoleID argument value.
			CustomRoleID uuid.UUID
		}
		// ModifyCustomRolePermissions holds details about calls to the ModifyCustomRolePermissions method.
		ModifyCustomRolePermissions []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Mrp is the mrp argument value.
			Mrp mdl.ModifyCustomRolePermissions
		}
		// UpdateCustomRole holds details about calls to the UpdateCustomRole method.
		UpdateCustomRole []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Ur is the ur argument value.
			Ur mdl.UpdateCustomRole
		}
	}
	lockCreateCustomRole            sync.RWMutex
	lockCustomRoleByID              sync.RWMutex
	lockCustomRoles                 sync.RWMutex
	lockDeleteCustomRole            sync.RWMutex
	lockModifyCustomRolePermissions sync.RWMutex
	lockUpdateCustomRole            sync.RWMutex
}

// CreateCustomRole calls CreateCustomRoleFunc.
func (mock *MockedCustomRoleCore) CreateCustomRole(ctx context.Context, cr mdl.CreateCustomRole) (mdl.CustomRole, error) {
	if mock.CreateCustomRoleFunc == nil {
		panic("MockedCustomRoleCore.CreateCustomRoleFunc: method is nil but CustomRoleCore.CreateCustomRole was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Cr  mdl.CreateCustomRole
	}{
		Ctx: ctx,
		Cr:  cr,
	}
	mock.lockCreateCustomRole.Lock()
	mock.calls.CreateCustomRole = append(mock.calls.CreateCustomRole, callInfo)
	mock.lockCreateCustomRole.Unlock()
	return mock.CreateCustomRoleFunc(ctx, cr)
}

// CreateCustomRoleCalls gets all the calls that were made to CreateCustomRole.
// Check the length with:
//
//	len(mockedCustomRoleCore.CreateCustomRoleCalls())
func (mock *MockedCustomRoleCore) CreateCustomRoleCalls() []struct {
	Ctx context.Context
	Cr  mdl.CreateCustomRole
} {
	var calls []struct {
		Ctx context.Context
		Cr  mdl.CreateCustomRole
	}
	mock.lockCreateCustomRole.RLock()
	calls = mock.calls.CreateCustomRole
	mock.lockCreateCustomRole.RUnlock()
	return calls
}

// CustomRoleByID calls CustomRoleByIDFunc.
func (mock *MockedCustomRoleCore) CustomRoleByID(ctx context.Context, customRoleID uuid.UUID) (mdl.CustomRole, error) {
	if mock.CustomRoleByIDFunc == nil {
		panic("MockedCustomRoleCore.CustomRoleByIDFunc: method is nil but CustomRoleCore.CustomRoleByID was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		CustomRoleID uuid.UUID
	}{
		Ctx:          ctx,
		CustomRoleID: customRoleID,
	}
	mock.lockCustomRoleByID.Lock()
	mock.calls.CustomRoleByID = append(mock.calls.CustomRoleByID, callInfo)
	mock.lockCustomRoleByID.Unlock()
	return mock.CustomRoleByIDFunc(ctx, customRoleID)
}

// CustomRoleByIDCalls gets all the calls that were made to CustomRoleByID.
// Check the length with:
//
//	len(mockedCustomRoleCore.CustomRoleByIDCalls())
func (mock *MockedCustomRoleCore) CustomRoleByIDCalls() []struct {
	Ctx          context.Context
	CustomRoleID uuid.UUID
} {
	var calls []struct {
		Ctx          context.Context
		CustomRoleID uuid.UUID
	}
	mock.lockCustomRoleByID.RLock()
	calls = mock.calls.CustomRoleByID
	mock.lockCustomRoleByID.RUnlock()
	return calls
}

// CustomRoles calls CustomRolesFunc.
func (mock *MockedCustomRoleCore) CustomRoles(ctx context.Context, pageSize int, pageOffset int) ([]mdl.CustomRole, int, error) {
	if mock.CustomRolesFunc == nil {
		panic("MockedCustomRoleCore.CustomRolesFunc: method is nil but CustomRoleCore.CustomRoles was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		PageSize   int
		PageOffset int
	}{
		Ctx:        ctx,
		PageSize:   pageSize,
		PageOffset: pageOffset,
	}
	mock.lockCustomRoles.Lock()
	mock.calls.CustomRoles = append(mock.calls.CustomRoles, callInfo)
	mock.lockCustomRoles.Unlock()
	return mock.CustomRolesFunc(ctx, pageSize, pageOffset)
}

// CustomRolesCalls gets all the calls that were made to CustomRoles.
// Check the length with:
//
//	len(mockedCustomRoleCore.CustomRolesCalls())
func (mock *MockedCustomRoleCore) CustomRolesCalls() []struct {
	Ctx        context.Context
	PageSize   int
	PageOffset int
} {
	var calls []struct {
		Ctx        context.Context
		PageSize   int
		PageOffset int
	}
	mock.lockCustomRoles.RLock()
	calls = mock.calls.CustomRoles
	mock.lockCustomRoles.RUnlock()
	return calls
}

// DeleteCustomRole calls DeleteCustomRoleFunc.
func (mock *MockedCustomRoleCore) DeleteCustomRole(ctx context.Context, customRoleID uuid.UUID) error {
	if mock.DeleteCustomRoleFunc == nil {
		panic("MockedCustomRoleCore.DeleteCustomRoleFunc: method is nil but CustomRoleCore.DeleteCustomRole was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		CustomRoleID uuid.UUID
	}{
		Ctx:          ctx,
		CustomRoleID: customRoleID,
	}
	mock.lockDeleteCustomRole.Lock()
	mock.calls.DeleteCustomRole = append(mock.calls.DeleteCustomRole, callInfo)
	mock.lockDeleteCustomRole.Unlock()
	return mock.DeleteCustomRoleFunc(ctx, customRoleID)
}

// DeleteCustomRoleCalls gets all the calls that were made to DeleteCustomRole.
// Check the length with:
//
//	len(mockedCustomRoleCore.DeleteCustomRoleCalls())
func (mock *MockedCustomRoleCore) DeleteCustomRoleCalls() []struct {
	Ctx          context.Context
	CustomRoleID uuid.UUID
} {
	var calls []struct {
		Ctx          context.Context
		CustomRoleID uuid.UUID
	}
	mock.lockDeleteCustomRole.RLock()
	calls = mock.calls.DeleteCustomRole
	mock.lockDeleteCustomRole.RUnlock()
	return calls
}

// ModifyCustomRolePermissions calls ModifyCustomRolePermissionsFunc.
func (mock *MockedCustomRoleCore) ModifyCustomRolePermissions(ctx context.Context, mrp mdl.ModifyCustomRolePermissions) (mdl.CustomRole, error) {
	if mock.ModifyCustomRolePermissionsFunc == nil {
		panic("MockedCustomRoleCore.ModifyCustomRolePermissionsFunc: method is nil but CustomRoleCore.ModifyCustomRolePermissions was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Mrp mdl.ModifyCustomRolePermissions
	}{
		Ctx: ctx,
		Mrp: mrp,
	}
	mock.lockModifyCustomRolePermissions.Lock()
	mock.calls.ModifyCustomRolePermissions = append(mock.calls.ModifyCustomRolePermissions, callInfo)
	mock.lockModifyCustomRolePermissions.Unlock()
	return mock.ModifyCustomRolePermissionsFunc(ctx, mrp)
}

// ModifyCustomRolePermissionsCalls gets all the calls that were made to ModifyCustomRolePermissions.
// Check the length with:
//
//	len(mockedCustomRoleCore.ModifyCustomRolePermissionsCalls())
func (mock *MockedCustomRoleCore) ModifyCustomRolePermissionsCalls() []struct {
	Ctx context.Context
	Mrp mdl.ModifyCustomRolePermissions
} {
	var calls []struct {
		Ctx context.Context
		Mrp mdl.ModifyCustomRolePermissions
	}
	mock.lockModifyCustomRolePermissions.RLock()
	calls = mock.calls.ModifyCustomRolePermissions
	mock.lockModifyCustomRolePermissions.RUnlock()
	return calls
}

// UpdateCustomRole calls UpdateCustomRoleFunc.
func (mock *MockedCustomRoleCore) UpdateCustomRole(ctx context.Context, ur mdl.UpdateCustomRole) (mdl.CustomRole, error) {
	if mock.UpdateCustomRoleFunc == nil {
		panic("MockedCustomRoleCore.UpdateCustomRoleFunc: method is nil but CustomRoleCore.UpdateCustomRole was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Ur  mdl.UpdateCustomRole
	}{
		Ctx: ctx,
		Ur:  ur,
	}
	mock.lockUpdateCustomRole.Lock()
	mock.calls.UpdateCustomRole = append(mock.calls.UpdateCustomRole, callInfo)
	mock.lockUpdateCustomRole.Unlock()
	return mock.UpdateCustomRoleFunc(ctx, ur)
}

// UpdateCustomRoleCalls gets all the calls that were made to UpdateCustomRole.
// Check the length with:
//
//	len(mockedCustomRoleCore.UpdateCustomRoleCalls())
func (mock *MockedCustomRoleCore) UpdateCustomRoleCalls() []struct {
	Ctx context.Context
	Ur  mdl.UpdateCustomRole
} {
	var calls []struct {
		Ctx context.Context
		Ur  mdl.UpdateCustomRole
	}
	mock.lockUpdateCustomRole.RLock()
	calls = mock.calls.UpdateCustomRole
	mock.lockUpdateCustomRole.RUnlock()
	return calls
}
