// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package grpc

import (
	"context"
	"sync"

	"github.com/zorcal/theapp/backend/internal/core/mdl"
)

// Ensure, that MockedOrganizationCore does implement OrganizationCore.
// If this is not the case, regenerate this file with moq.
var _ OrganizationCore = &MockedOrganizationCore{}

// MockedOrganizationCore is a mock implementation of OrganizationCore.
//
//	func TestSomethingThatUsesOrganizationCore(t *testing.T) {
//
//		// make and configure a mocked OrganizationCore
//		mockedOrganizationCore := &MockedOrganizationCore{
//			CreateOrganizationFunc: func(ctx context.Context, organization mdl.CreateOrganization) (mdl.Organization, error) {
//				panic("mock out the CreateOrganization method")
//			},
//			CreateOrganizationUserFunc: func(ctx context.Context, user mdl.CreateOrganizationUser) (mdl.User, error) {
//				panic("mock out the CreateOrganizationUser method")
//			},
//			OrganizationUsersFunc: func(ctx context.Context, filter mdl.OrganizationUserFilter, pageSize int, pageOffset int) ([]mdl.User, int, error) {
//				panic("mock out the OrganizationUsers method")
//			},
//		}
//
//		// use mockedOrganizationCore in code that requires OrganizationCore
//		// and then make assertions.
//
//	}
type MockedOrganizationCore struct {
	// CreateOrganizationFunc mocks the CreateOrganization method.
	CreateOrganizationFunc func(ctx context.Context, organization mdl.CreateOrganization) (mdl.Organization, error)

	// CreateOrganizationUserFunc mocks the CreateOrganizationUser method.
	CreateOrganizationUserFunc func(ctx context.Context, user mdl.CreateOrganizationUser) (mdl.User, error)

	// OrganizationUsersFunc mocks the OrganizationUsers method.
	OrganizationUsersFunc func(ctx context.Context, filter mdl.OrganizationUserFilter, pageSize int, pageOffset int) ([]mdl.User, int, error)

	// calls tracks calls to the methods.
	calls struct {
		// CreateOrganization holds details about calls to the CreateOrganization method.
		CreateOrganization []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Organization is the organization argument value.
			Organization mdl.CreateOrganization
		}
		// CreateOrganizationUser holds details about calls to the CreateOrganizationUser method.
		CreateOrganizationUser []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// User is the user argument value.
			User mdl.CreateOrganizationUser
		}
		// OrganizationUsers holds details about calls to the OrganizationUsers method.
		OrganizationUsers []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Filter is the filter argument value.
			Filter mdl.OrganizationUserFilter
			// PageSize is the pageSize argument value.
			PageSize int
			// PageOffset is the pageOffset argument value.
			PageOffset int
		}
	}
	lockCreateOrganization     sync.RWMutex
	lockCreateOrganizationUser sync.RWMutex
	lockOrganizationUsers      sync.RWMutex
}

// CreateOrganization calls CreateOrganizationFunc.
func (mock *MockedOrganizationCore) CreateOrganization(ctx context.Context, organization mdl.CreateOrganization) (mdl.Organization, error) {
	if mock.CreateOrganizationFunc == nil {
		panic("MockedOrganizationCore.CreateOrganizationFunc: method is nil but OrganizationCore.CreateOrganization was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		Organization mdl.CreateOrganization
	}{
		Ctx:          ctx,
		Organization: organization,
	}
	mock.lockCreateOrganization.Lock()
	mock.calls.CreateOrganization = append(mock.calls.CreateOrganization, callInfo)
	mock.lockCreateOrganization.Unlock()
	return mock.CreateOrganizationFunc(ctx, organization)
}

// CreateOrganizationCalls gets all the calls that were made to CreateOrganization.
// Check the length with:
//
//	len(mockedOrganizationCore.CreateOrganizationCalls())
func (mock *MockedOrganizationCore) CreateOrganizationCalls() []struct {
	Ctx          context.Context
	Organization mdl.CreateOrganization
} {
	var calls []struct {
		Ctx          context.Context
		Organization mdl.CreateOrganization
	}
	mock.lockCreateOrganization.RLock()
	calls = mock.calls.CreateOrganization
	mock.lockCreateOrganization.RUnlock()
	return calls
}

// CreateOrganizationUser calls CreateOrganizationUserFunc.
func (mock *MockedOrganizationCore) CreateOrganizationUser(ctx context.Context, user mdl.CreateOrganizationUser) (mdl.User, error) {
	if mock.CreateOrganizationUserFunc == nil {
		panic("MockedOrganizationCore.CreateOrganizationUserFunc: method is nil but OrganizationCore.CreateOrganizationUser was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		User mdl.CreateOrganizationUser
	}{
		Ctx:  ctx,
		User: user,
	}
	mock.lockCreateOrganizationUser.Lock()
	mock.calls.CreateOrganizationUser = append(mock.calls.CreateOrganizationUser, callInfo)
	mock.lockCreateOrganizationUser.Unlock()
	return mock.CreateOrganizationUserFunc(ctx, user)
}

// CreateOrganizationUserCalls gets all the calls that were made to CreateOrganizationUser.
// Check the length with:
//
//	len(mockedOrganizationCore.CreateOrganizationUserCalls())
func (mock *MockedOrganizationCore) CreateOrganizationUserCalls() []struct {
	Ctx  context.Context
	User mdl.CreateOrganizationUser
} {
	var calls []struct {
		Ctx  context.Context
		User mdl.CreateOrganizationUser
	}
	mock.lockCreateOrganizationUser.RLock()
	calls = mock.calls.CreateOrganizationUser
	mock.lockCreateOrganizationUser.RUnlock()
	return calls
}

// OrganizationUsers calls OrganizationUsersFunc.
func (mock *MockedOrganizationCore) OrganizationUsers(ctx context.Context, filter mdl.OrganizationUserFilter, pageSize int, pageOffset int) ([]mdl.User, int, error) {
	if mock.OrganizationUsersFunc == nil {
		panic("MockedOrganizationCore.OrganizationUsersFunc: method is nil but OrganizationCore.OrganizationUsers was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		Filter     mdl.OrganizationUserFilter
		PageSize   int
		PageOffset int
	}{
		Ctx:        ctx,
		Filter:     filter,
		PageSize:   pageSize,
		PageOffset: pageOffset,
	}
	mock.lockOrganizationUsers.Lock()
	mock.calls.OrganizationUsers = append(mock.calls.OrganizationUsers, callInfo)
	mock.lockOrganizationUsers.Unlock()
	return mock.OrganizationUsersFunc(ctx, filter, pageSize, pageOffset)
}

// OrganizationUsersCalls gets all the calls that were made to OrganizationUsers.
// Check the length with:
//
//	len(mockedOrganizationCore.OrganizationUsersCalls())
func (mock *MockedOrganizationCore) OrganizationUsersCalls() []struct {
	Ctx        context.Context
	Filter     mdl.OrganizationUserFilter
	PageSize   int
	PageOffset int
} {
	var calls []struct {
		Ctx        context.Context
		Filter     mdl.OrganizationUserFilter
		PageSize   int
		PageOffset int
	}
	mock.lockOrganizationUsers.RLock()
	calls = mock.calls.OrganizationUsers
	mock.lockOrganizationUsers.RUnlock()
	return calls
}
