// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package grpc

import (
	"context"
	"sync"

	"github.com/google/uuid"
	"github.com/zorcal/theapp/backend/internal/core/mdl"
)

// Ensure, that MockedOrganizationCore does implement OrganizationCore.
// If this is not the case, regenerate this file with moq.
var _ OrganizationCore = &MockedOrganizationCore{}

// MockedOrganizationCore is a mock implementation of OrganizationCore.
//
//	func TestSomethingThatUsesOrganizationCore(t *testing.T) {
//
//		// make and configure a mocked OrganizationCore
//		mockedOrganizationCore := &MockedOrganizationCore{
//			CreateOrganizationFunc: func(ctx context.Context, organization mdl.CreateOrganization) (mdl.Organization, error) {
//				panic("mock out the CreateOrganization method")
//			},
//			IsOrganizationMemberFunc: func(ctx context.Context, userID uuid.UUID, orgID int) (bool, error) {
//				panic("mock out the IsOrganizationMember method")
//			},
//			OrganizationByNameFunc: func(ctx context.Context, name string) (mdl.Organization, error) {
//				panic("mock out the OrganizationByName method")
//			},
//		}
//
//		// use mockedOrganizationCore in code that requires OrganizationCore
//		// and then make assertions.
//
//	}
type MockedOrganizationCore struct {
	// CreateOrganizationFunc mocks the CreateOrganization method.
	CreateOrganizationFunc func(ctx context.Context, organization mdl.CreateOrganization) (mdl.Organization, error)

	// IsOrganizationMemberFunc mocks the IsOrganizationMember method.
	IsOrganizationMemberFunc func(ctx context.Context, userID uuid.UUID, orgID int) (bool, error)

	// OrganizationByNameFunc mocks the OrganizationByName method.
	OrganizationByNameFunc func(ctx context.Context, name string) (mdl.Organization, error)

	// calls tracks calls to the methods.
	calls struct {
		// CreateOrganization holds details about calls to the CreateOrganization method.
		CreateOrganization []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Organization is the organization argument value.
			Organization mdl.CreateOrganization
		}
		// IsOrganizationMember holds details about calls to the IsOrganizationMember method.
		IsOrganizationMember []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID uuid.UUID
			// OrgID is the orgID argument value.
			OrgID int
		}
		// OrganizationByName holds details about calls to the OrganizationByName method.
		OrganizationByName []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
		}
	}
	lockCreateOrganization   sync.RWMutex
	lockIsOrganizationMember sync.RWMutex
	lockOrganizationByName   sync.RWMutex
}

// CreateOrganization calls CreateOrganizationFunc.
func (mock *MockedOrganizationCore) CreateOrganization(ctx context.Context, organization mdl.CreateOrganization) (mdl.Organization, error) {
	if mock.CreateOrganizationFunc == nil {
		panic("MockedOrganizationCore.CreateOrganizationFunc: method is nil but OrganizationCore.CreateOrganization was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		Organization mdl.CreateOrganization
	}{
		Ctx:          ctx,
		Organization: organization,
	}
	mock.lockCreateOrganization.Lock()
	mock.calls.CreateOrganization = append(mock.calls.CreateOrganization, callInfo)
	mock.lockCreateOrganization.Unlock()
	return mock.CreateOrganizationFunc(ctx, organization)
}

// CreateOrganizationCalls gets all the calls that were made to CreateOrganization.
// Check the length with:
//
//	len(mockedOrganizationCore.CreateOrganizationCalls())
func (mock *MockedOrganizationCore) CreateOrganizationCalls() []struct {
	Ctx          context.Context
	Organization mdl.CreateOrganization
} {
	var calls []struct {
		Ctx          context.Context
		Organization mdl.CreateOrganization
	}
	mock.lockCreateOrganization.RLock()
	calls = mock.calls.CreateOrganization
	mock.lockCreateOrganization.RUnlock()
	return calls
}

// IsOrganizationMember calls IsOrganizationMemberFunc.
func (mock *MockedOrganizationCore) IsOrganizationMember(ctx context.Context, userID uuid.UUID, orgID int) (bool, error) {
	if mock.IsOrganizationMemberFunc == nil {
		panic("MockedOrganizationCore.IsOrganizationMemberFunc: method is nil but OrganizationCore.IsOrganizationMember was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID uuid.UUID
		OrgID  int
	}{
		Ctx:    ctx,
		UserID: userID,
		OrgID:  orgID,
	}
	mock.lockIsOrganizationMember.Lock()
	mock.calls.IsOrganizationMember = append(mock.calls.IsOrganizationMember, callInfo)
	mock.lockIsOrganizationMember.Unlock()
	return mock.IsOrganizationMemberFunc(ctx, userID, orgID)
}

// IsOrganizationMemberCalls gets all the calls that were made to IsOrganizationMember.
// Check the length with:
//
//	len(mockedOrganizationCore.IsOrganizationMemberCalls())
func (mock *MockedOrganizationCore) IsOrganizationMemberCalls() []struct {
	Ctx    context.Context
	UserID uuid.UUID
	OrgID  int
} {
	var calls []struct {
		Ctx    context.Context
		UserID uuid.UUID
		OrgID  int
	}
	mock.lockIsOrganizationMember.RLock()
	calls = mock.calls.IsOrganizationMember
	mock.lockIsOrganizationMember.RUnlock()
	return calls
}

// OrganizationByName calls OrganizationByNameFunc.
func (mock *MockedOrganizationCore) OrganizationByName(ctx context.Context, name string) (mdl.Organization, error) {
	if mock.OrganizationByNameFunc == nil {
		panic("MockedOrganizationCore.OrganizationByNameFunc: method is nil but OrganizationCore.OrganizationByName was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Name string
	}{
		Ctx:  ctx,
		Name: name,
	}
	mock.lockOrganizationByName.Lock()
	mock.calls.OrganizationByName = append(mock.calls.OrganizationByName, callInfo)
	mock.lockOrganizationByName.Unlock()
	return mock.OrganizationByNameFunc(ctx, name)
}

// OrganizationByNameCalls gets all the calls that were made to OrganizationByName.
// Check the length with:
//
//	len(mockedOrganizationCore.OrganizationByNameCalls())
func (mock *MockedOrganizationCore) OrganizationByNameCalls() []struct {
	Ctx  context.Context
	Name string
} {
	var calls []struct {
		Ctx  context.Context
		Name string
	}
	mock.lockOrganizationByName.RLock()
	calls = mock.calls.OrganizationByName
	mock.lockOrganizationByName.RUnlock()
	return calls
}
