// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package grpc

import (
	"context"
	"sync"

	"github.com/google/uuid"
	"github.com/zorcal/theapp/backend/internal/core/mdl"
)

// Ensure, that MockedRoleCore does implement RoleCore.
// If this is not the case, regenerate this file with moq.
var _ RoleCore = &MockedRoleCore{}

// MockedRoleCore is a mock implementation of RoleCore.
//
//	func TestSomethingThatUsesRoleCore(t *testing.T) {
//
//		// make and configure a mocked RoleCore
//		mockedRoleCore := &MockedRoleCore{
//			AssignRoleFunc: func(ctx context.Context, orgID int, in mdl.AssignRole) error {
//				panic("mock out the AssignRole method")
//			},
//			CreateRoleFunc: func(ctx context.Context, orgID int, cr mdl.CreateRole) (mdl.RoleCustom, error) {
//				panic("mock out the CreateRole method")
//			},
//			DeleteRoleFunc: func(ctx context.Context, orgID int, id uuid.UUID) error {
//				panic("mock out the DeleteRole method")
//			},
//			ListRoleAssignmentsFunc: func(ctx context.Context, orgID int, userID uuid.UUID, pageSize int, pageOffset int) ([]mdl.RoleAssignment, int, error) {
//				panic("mock out the ListRoleAssignments method")
//			},
//			ModifyRolePermissionsFunc: func(ctx context.Context, orgID int, m mdl.ModifyRolePermissions) (mdl.RoleCustom, error) {
//				panic("mock out the ModifyRolePermissions method")
//			},
//			OrgRolesFunc: func(ctx context.Context, orgID int, pageSize int, pageOffset int) ([]mdl.RoleCustom, int, error) {
//				panic("mock out the OrgRoles method")
//			},
//			RolePermissionsFunc: func(ctx context.Context, orgID int, roleID uuid.UUID, pageSize int, pageOffset int) ([]mdl.Permission, int, error) {
//				panic("mock out the RolePermissions method")
//			},
//			UnassignRoleFunc: func(ctx context.Context, orgID int, in mdl.UnassignRole) error {
//				panic("mock out the UnassignRole method")
//			},
//			UpdateRoleFunc: func(ctx context.Context, orgID int, ur mdl.UpdateRole) (mdl.RoleCustom, error) {
//				panic("mock out the UpdateRole method")
//			},
//		}
//
//		// use mockedRoleCore in code that requires RoleCore
//		// and then make assertions.
//
//	}
type MockedRoleCore struct {
	// AssignRoleFunc mocks the AssignRole method.
	AssignRoleFunc func(ctx context.Context, orgID int, in mdl.AssignRole) error

	// CreateRoleFunc mocks the CreateRole method.
	CreateRoleFunc func(ctx context.Context, orgID int, cr mdl.CreateRole) (mdl.RoleCustom, error)

	// DeleteRoleFunc mocks the DeleteRole method.
	DeleteRoleFunc func(ctx context.Context, orgID int, id uuid.UUID) error

	// ListRoleAssignmentsFunc mocks the ListRoleAssignments method.
	ListRoleAssignmentsFunc func(ctx context.Context, orgID int, userID uuid.UUID, pageSize int, pageOffset int) ([]mdl.RoleAssignment, int, error)

	// ModifyRolePermissionsFunc mocks the ModifyRolePermissions method.
	ModifyRolePermissionsFunc func(ctx context.Context, orgID int, m mdl.ModifyRolePermissions) (mdl.RoleCustom, error)

	// OrgRolesFunc mocks the OrgRoles method.
	OrgRolesFunc func(ctx context.Context, orgID int, pageSize int, pageOffset int) ([]mdl.RoleCustom, int, error)

	// RolePermissionsFunc mocks the RolePermissions method.
	RolePermissionsFunc func(ctx context.Context, orgID int, roleID uuid.UUID, pageSize int, pageOffset int) ([]mdl.Permission, int, error)

	// UnassignRoleFunc mocks the UnassignRole method.
	UnassignRoleFunc func(ctx context.Context, orgID int, in mdl.UnassignRole) error

	// UpdateRoleFunc mocks the UpdateRole method.
	UpdateRoleFunc func(ctx context.Context, orgID int, ur mdl.UpdateRole) (mdl.RoleCustom, error)

	// calls tracks calls to the methods.
	calls struct {
		// AssignRole holds details about calls to the AssignRole method.
		AssignRole []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgID is the orgID argument value.
			OrgID int
			// In is the in argument value.
			In mdl.AssignRole
		}
		// CreateRole holds details about calls to the CreateRole method.
		CreateRole []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgID is the orgID argument value.
			OrgID int
			// Cr is the cr argument value.
			Cr mdl.CreateRole
		}
		// DeleteRole holds details about calls to the DeleteRole method.
		DeleteRole []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgID is the orgID argument value.
			OrgID int
			// ID is the id argument value.
			ID uuid.UUID
		}
		// ListRoleAssignments holds details about calls to the ListRoleAssignments method.
		ListRoleAssignments []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgID is the orgID argument value.
			OrgID int
			// UserID is the userID argument value.
			UserID uuid.UUID
			// PageSize is the pageSize argument value.
			PageSize int
			// PageOffset is the pageOffset argument value.
			PageOffset int
		}
		// ModifyRolePermissions holds details about calls to the ModifyRolePermissions method.
		ModifyRolePermissions []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgID is the orgID argument value.
			OrgID int
			// M is the m argument value.
			M mdl.ModifyRolePermissions
		}
		// OrgRoles holds details about calls to the OrgRoles method.
		OrgRoles []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgID is the orgID argument value.
			OrgID int
			// PageSize is the pageSize argument value.
			PageSize int
			// PageOffset is the pageOffset argument value.
			PageOffset int
		}
		// RolePermissions holds details about calls to the RolePermissions method.
		RolePermissions []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgID is the orgID argument value.
			OrgID int
			// RoleID is the roleID argument value.
			RoleID uuid.UUID
			// PageSize is the pageSize argument value.
			PageSize int
			// PageOffset is the pageOffset argument value.
			PageOffset int
		}
		// UnassignRole holds details about calls to the UnassignRole method.
		UnassignRole []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgID is the orgID argument value.
			OrgID int
			// In is the in argument value.
			In mdl.UnassignRole
		}
		// UpdateRole holds details about calls to the UpdateRole method.
		UpdateRole []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgID is the orgID argument value.
			OrgID int
			// Ur is the ur argument value.
			Ur mdl.UpdateRole
		}
	}
	lockAssignRole            sync.RWMutex
	lockCreateRole            sync.RWMutex
	lockDeleteRole            sync.RWMutex
	lockListRoleAssignments   sync.RWMutex
	lockModifyRolePermissions sync.RWMutex
	lockOrgRoles              sync.RWMutex
	lockRolePermissions       sync.RWMutex
	lockUnassignRole          sync.RWMutex
	lockUpdateRole            sync.RWMutex
}

// AssignRole calls AssignRoleFunc.
func (mock *MockedRoleCore) AssignRole(ctx context.Context, orgID int, in mdl.AssignRole) error {
	if mock.AssignRoleFunc == nil {
		panic("MockedRoleCore.AssignRoleFunc: method is nil but RoleCore.AssignRole was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		OrgID int
		In    mdl.AssignRole
	}{
		Ctx:   ctx,
		OrgID: orgID,
		In:    in,
	}
	mock.lockAssignRole.Lock()
	mock.calls.AssignRole = append(mock.calls.AssignRole, callInfo)
	mock.lockAssignRole.Unlock()
	return mock.AssignRoleFunc(ctx, orgID, in)
}

// AssignRoleCalls gets all the calls that were made to AssignRole.
// Check the length with:
//
//	len(mockedRoleCore.AssignRoleCalls())
func (mock *MockedRoleCore) AssignRoleCalls() []struct {
	Ctx   context.Context
	OrgID int
	In    mdl.AssignRole
} {
	var calls []struct {
		Ctx   context.Context
		OrgID int
		In    mdl.AssignRole
	}
	mock.lockAssignRole.RLock()
	calls = mock.calls.AssignRole
	mock.lockAssignRole.RUnlock()
	return calls
}

// CreateRole calls CreateRoleFunc.
func (mock *MockedRoleCore) CreateRole(ctx context.Context, orgID int, cr mdl.CreateRole) (mdl.RoleCustom, error) {
	if mock.CreateRoleFunc == nil {
		panic("MockedRoleCore.CreateRoleFunc: method is nil but RoleCore.CreateRole was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		OrgID int
		Cr    mdl.CreateRole
	}{
		Ctx:   ctx,
		OrgID: orgID,
		Cr:    cr,
	}
	mock.lockCreateRole.Lock()
	mock.calls.CreateRole = append(mock.calls.CreateRole, callInfo)
	mock.lockCreateRole.Unlock()
	return mock.CreateRoleFunc(ctx, orgID, cr)
}

// CreateRoleCalls gets all the calls that were made to CreateRole.
// Check the length with:
//
//	len(mockedRoleCore.CreateRoleCalls())
func (mock *MockedRoleCore) CreateRoleCalls() []struct {
	Ctx   context.Context
	OrgID int
	Cr    mdl.CreateRole
} {
	var calls []struct {
		Ctx   context.Context
		OrgID int
		Cr    mdl.CreateRole
	}
	mock.lockCreateRole.RLock()
	calls = mock.calls.CreateRole
	mock.lockCreateRole.RUnlock()
	return calls
}

// DeleteRole calls DeleteRoleFunc.
func (mock *MockedRoleCore) DeleteRole(ctx context.Context, orgID int, id uuid.UUID) error {
	if mock.DeleteRoleFunc == nil {
		panic("MockedRoleCore.DeleteRoleFunc: method is nil but RoleCore.DeleteRole was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		OrgID int
		ID    uuid.UUID
	}{
		Ctx:   ctx,
		OrgID: orgID,
		ID:    id,
	}
	mock.lockDeleteRole.Lock()
	mock.calls.DeleteRole = append(mock.calls.DeleteRole, callInfo)
	mock.lockDeleteRole.Unlock()
	return mock.DeleteRoleFunc(ctx, orgID, id)
}

// DeleteRoleCalls gets all the calls that were made to DeleteRole.
// Check the length with:
//
//	len(mockedRoleCore.DeleteRoleCalls())
func (mock *MockedRoleCore) DeleteRoleCalls() []struct {
	Ctx   context.Context
	OrgID int
	ID    uuid.UUID
} {
	var calls []struct {
		Ctx   context.Context
		OrgID int
		ID    uuid.UUID
	}
	mock.lockDeleteRole.RLock()
	calls = mock.calls.DeleteRole
	mock.lockDeleteRole.RUnlock()
	return calls
}

// ListRoleAssignments calls ListRoleAssignmentsFunc.
func (mock *MockedRoleCore) ListRoleAssignments(ctx context.Context, orgID int, userID uuid.UUID, pageSize int, pageOffset int) ([]mdl.RoleAssignment, int, error) {
	if mock.ListRoleAssignmentsFunc == nil {
		panic("MockedRoleCore.ListRoleAssignmentsFunc: method is nil but RoleCore.ListRoleAssignments was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		OrgID      int
		UserID     uuid.UUID
		PageSize   int
		PageOffset int
	}{
		Ctx:        ctx,
		OrgID:      orgID,
		UserID:     userID,
		PageSize:   pageSize,
		PageOffset: pageOffset,
	}
	mock.lockListRoleAssignments.Lock()
	mock.calls.ListRoleAssignments = append(mock.calls.ListRoleAssignments, callInfo)
	mock.lockListRoleAssignments.Unlock()
	return mock.ListRoleAssignmentsFunc(ctx, orgID, userID, pageSize, pageOffset)
}

// ListRoleAssignmentsCalls gets all the calls that were made to ListRoleAssignments.
// Check the length with:
//
//	len(mockedRoleCore.ListRoleAssignmentsCalls())
func (mock *MockedRoleCore) ListRoleAssignmentsCalls() []struct {
	Ctx        context.Context
	OrgID      int
	UserID     uuid.UUID
	PageSize   int
	PageOffset int
} {
	var calls []struct {
		Ctx        context.Context
		OrgID      int
		UserID     uuid.UUID
		PageSize   int
		PageOffset int
	}
	mock.lockListRoleAssignments.RLock()
	calls = mock.calls.ListRoleAssignments
	mock.lockListRoleAssignments.RUnlock()
	return calls
}

// ModifyRolePermissions calls ModifyRolePermissionsFunc.
func (mock *MockedRoleCore) ModifyRolePermissions(ctx context.Context, orgID int, m mdl.ModifyRolePermissions) (mdl.RoleCustom, error) {
	if mock.ModifyRolePermissionsFunc == nil {
		panic("MockedRoleCore.ModifyRolePermissionsFunc: method is nil but RoleCore.ModifyRolePermissions was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		OrgID int
		M     mdl.ModifyRolePermissions
	}{
		Ctx:   ctx,
		OrgID: orgID,
		M:     m,
	}
	mock.lockModifyRolePermissions.Lock()
	mock.calls.ModifyRolePermissions = append(mock.calls.ModifyRolePermissions, callInfo)
	mock.lockModifyRolePermissions.Unlock()
	return mock.ModifyRolePermissionsFunc(ctx, orgID, m)
}

// ModifyRolePermissionsCalls gets all the calls that were made to ModifyRolePermissions.
// Check the length with:
//
//	len(mockedRoleCore.ModifyRolePermissionsCalls())
func (mock *MockedRoleCore) ModifyRolePermissionsCalls() []struct {
	Ctx   context.Context
	OrgID int
	M     mdl.ModifyRolePermissions
} {
	var calls []struct {
		Ctx   context.Context
		OrgID int
		M     mdl.ModifyRolePermissions
	}
	mock.lockModifyRolePermissions.RLock()
	calls = mock.calls.ModifyRolePermissions
	mock.lockModifyRolePermissions.RUnlock()
	return calls
}

// OrgRoles calls OrgRolesFunc.
func (mock *MockedRoleCore) OrgRoles(ctx context.Context, orgID int, pageSize int, pageOffset int) ([]mdl.RoleCustom, int, error) {
	if mock.OrgRolesFunc == nil {
		panic("MockedRoleCore.OrgRolesFunc: method is nil but RoleCore.OrgRoles was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		OrgID      int
		PageSize   int
		PageOffset int
	}{
		Ctx:        ctx,
		OrgID:      orgID,
		PageSize:   pageSize,
		PageOffset: pageOffset,
	}
	mock.lockOrgRoles.Lock()
	mock.calls.OrgRoles = append(mock.calls.OrgRoles, callInfo)
	mock.lockOrgRoles.Unlock()
	return mock.OrgRolesFunc(ctx, orgID, pageSize, pageOffset)
}

// OrgRolesCalls gets all the calls that were made to OrgRoles.
// Check the length with:
//
//	len(mockedRoleCore.OrgRolesCalls())
func (mock *MockedRoleCore) OrgRolesCalls() []struct {
	Ctx        context.Context
	OrgID      int
	PageSize   int
	PageOffset int
} {
	var calls []struct {
		Ctx        context.Context
		OrgID      int
		PageSize   int
		PageOffset int
	}
	mock.lockOrgRoles.RLock()
	calls = mock.calls.OrgRoles
	mock.lockOrgRoles.RUnlock()
	return calls
}

// RolePermissions calls RolePermissionsFunc.
func (mock *MockedRoleCore) RolePermissions(ctx context.Context, orgID int, roleID uuid.UUID, pageSize int, pageOffset int) ([]mdl.Permission, int, error) {
	if mock.RolePermissionsFunc == nil {
		panic("MockedRoleCore.RolePermissionsFunc: method is nil but RoleCore.RolePermissions was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		OrgID      int
		RoleID     uuid.UUID
		PageSize   int
		PageOffset int
	}{
		Ctx:        ctx,
		OrgID:      orgID,
		RoleID:     roleID,
		PageSize:   pageSize,
		PageOffset: pageOffset,
	}
	mock.lockRolePermissions.Lock()
	mock.calls.RolePermissions = append(mock.calls.RolePermissions, callInfo)
	mock.lockRolePermissions.Unlock()
	return mock.RolePermissionsFunc(ctx, orgID, roleID, pageSize, pageOffset)
}

// RolePermissionsCalls gets all the calls that were made to RolePermissions.
// Check the length with:
//
//	len(mockedRoleCore.RolePermissionsCalls())
func (mock *MockedRoleCore) RolePermissionsCalls() []struct {
	Ctx        context.Context
	OrgID      int
	RoleID     uuid.UUID
	PageSize   int
	PageOffset int
} {
	var calls []struct {
		Ctx        context.Context
		OrgID      int
		RoleID     uuid.UUID
		PageSize   int
		PageOffset int
	}
	mock.lockRolePermissions.RLock()
	calls = mock.calls.RolePermissions
	mock.lockRolePermissions.RUnlock()
	return calls
}

// UnassignRole calls UnassignRoleFunc.
func (mock *MockedRoleCore) UnassignRole(ctx context.Context, orgID int, in mdl.UnassignRole) error {
	if mock.UnassignRoleFunc == nil {
		panic("MockedRoleCore.UnassignRoleFunc: method is nil but RoleCore.UnassignRole was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		OrgID int
		In    mdl.UnassignRole
	}{
		Ctx:   ctx,
		OrgID: orgID,
		In:    in,
	}
	mock.lockUnassignRole.Lock()
	mock.calls.UnassignRole = append(mock.calls.UnassignRole, callInfo)
	mock.lockUnassignRole.Unlock()
	return mock.UnassignRoleFunc(ctx, orgID, in)
}

// UnassignRoleCalls gets all the calls that were made to UnassignRole.
// Check the length with:
//
//	len(mockedRoleCore.UnassignRoleCalls())
func (mock *MockedRoleCore) UnassignRoleCalls() []struct {
	Ctx   context.Context
	OrgID int
	In    mdl.UnassignRole
} {
	var calls []struct {
		Ctx   context.Context
		OrgID int
		In    mdl.UnassignRole
	}
	mock.lockUnassignRole.RLock()
	calls = mock.calls.UnassignRole
	mock.lockUnassignRole.RUnlock()
	return calls
}

// UpdateRole calls UpdateRoleFunc.
func (mock *MockedRoleCore) UpdateRole(ctx context.Context, orgID int, ur mdl.UpdateRole) (mdl.RoleCustom, error) {
	if mock.UpdateRoleFunc == nil {
		panic("MockedRoleCore.UpdateRoleFunc: method is nil but RoleCore.UpdateRole was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		OrgID int
		Ur    mdl.UpdateRole
	}{
		Ctx:   ctx,
		OrgID: orgID,
		Ur:    ur,
	}
	mock.lockUpdateRole.Lock()
	mock.calls.UpdateRole = append(mock.calls.UpdateRole, callInfo)
	mock.lockUpdateRole.Unlock()
	return mock.UpdateRoleFunc(ctx, orgID, ur)
}

// UpdateRoleCalls gets all the calls that were made to UpdateRole.
// Check the length with:
//
//	len(mockedRoleCore.UpdateRoleCalls())
func (mock *MockedRoleCore) UpdateRoleCalls() []struct {
	Ctx   context.Context
	OrgID int
	Ur    mdl.UpdateRole
} {
	var calls []struct {
		Ctx   context.Context
		OrgID int
		Ur    mdl.UpdateRole
	}
	mock.lockUpdateRole.RLock()
	calls = mock.calls.UpdateRole
	mock.lockUpdateRole.RUnlock()
	return calls
}
