// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package grpc

import (
	"context"
	"sync"

	"github.com/google/uuid"
	"github.com/zorcal/theapp/backend/internal/core/mdl"
)

// Ensure, that MockedSystemRoleCore does implement SystemRoleCore.
// If this is not the case, regenerate this file with moq.
var _ SystemRoleCore = &MockedSystemRoleCore{}

// MockedSystemRoleCore is a mock implementation of SystemRoleCore.
//
//	func TestSomethingThatUsesSystemRoleCore(t *testing.T) {
//
//		// make and configure a mocked SystemRoleCore
//		mockedSystemRoleCore := &MockedSystemRoleCore{
//			StaticRolePermissionsFunc: func(ctx context.Context, roleName string, pageSize int, pageOffset int) ([]mdl.Permission, int, error) {
//				panic("mock out the StaticRolePermissions method")
//			},
//			SystemRoleAssignmentsFunc: func(ctx context.Context, userID uuid.UUID, pageSize int, pageOffset int) ([]string, int, error) {
//				panic("mock out the SystemRoleAssignments method")
//			},
//		}
//
//		// use mockedSystemRoleCore in code that requires SystemRoleCore
//		// and then make assertions.
//
//	}
type MockedSystemRoleCore struct {
	// StaticRolePermissionsFunc mocks the StaticRolePermissions method.
	StaticRolePermissionsFunc func(ctx context.Context, roleName string, pageSize int, pageOffset int) ([]mdl.Permission, int, error)

	// SystemRoleAssignmentsFunc mocks the SystemRoleAssignments method.
	SystemRoleAssignmentsFunc func(ctx context.Context, userID uuid.UUID, pageSize int, pageOffset int) ([]string, int, error)

	// calls tracks calls to the methods.
	calls struct {
		// StaticRolePermissions holds details about calls to the StaticRolePermissions method.
		StaticRolePermissions []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RoleName is the roleName argument value.
			RoleName string
			// PageSize is the pageSize argument value.
			PageSize int
			// PageOffset is the pageOffset argument value.
			PageOffset int
		}
		// SystemRoleAssignments holds details about calls to the SystemRoleAssignments method.
		SystemRoleAssignments []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID uuid.UUID
			// PageSize is the pageSize argument value.
			PageSize int
			// PageOffset is the pageOffset argument value.
			PageOffset int
		}
	}
	lockStaticRolePermissions sync.RWMutex
	lockSystemRoleAssignments sync.RWMutex
}

// StaticRolePermissions calls StaticRolePermissionsFunc.
func (mock *MockedSystemRoleCore) StaticRolePermissions(ctx context.Context, roleName string, pageSize int, pageOffset int) ([]mdl.Permission, int, error) {
	if mock.StaticRolePermissionsFunc == nil {
		panic("MockedSystemRoleCore.StaticRolePermissionsFunc: method is nil but SystemRoleCore.StaticRolePermissions was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		RoleName   string
		PageSize   int
		PageOffset int
	}{
		Ctx:        ctx,
		RoleName:   roleName,
		PageSize:   pageSize,
		PageOffset: pageOffset,
	}
	mock.lockStaticRolePermissions.Lock()
	mock.calls.StaticRolePermissions = append(mock.calls.StaticRolePermissions, callInfo)
	mock.lockStaticRolePermissions.Unlock()
	return mock.StaticRolePermissionsFunc(ctx, roleName, pageSize, pageOffset)
}

// StaticRolePermissionsCalls gets all the calls that were made to StaticRolePermissions.
// Check the length with:
//
//	len(mockedSystemRoleCore.StaticRolePermissionsCalls())
func (mock *MockedSystemRoleCore) StaticRolePermissionsCalls() []struct {
	Ctx        context.Context
	RoleName   string
	PageSize   int
	PageOffset int
} {
	var calls []struct {
		Ctx        context.Context
		RoleName   string
		PageSize   int
		PageOffset int
	}
	mock.lockStaticRolePermissions.RLock()
	calls = mock.calls.StaticRolePermissions
	mock.lockStaticRolePermissions.RUnlock()
	return calls
}

// SystemRoleAssignments calls SystemRoleAssignmentsFunc.
func (mock *MockedSystemRoleCore) SystemRoleAssignments(ctx context.Context, userID uuid.UUID, pageSize int, pageOffset int) ([]string, int, error) {
	if mock.SystemRoleAssignmentsFunc == nil {
		panic("MockedSystemRoleCore.SystemRoleAssignmentsFunc: method is nil but SystemRoleCore.SystemRoleAssignments was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		UserID     uuid.UUID
		PageSize   int
		PageOffset int
	}{
		Ctx:        ctx,
		UserID:     userID,
		PageSize:   pageSize,
		PageOffset: pageOffset,
	}
	mock.lockSystemRoleAssignments.Lock()
	mock.calls.SystemRoleAssignments = append(mock.calls.SystemRoleAssignments, callInfo)
	mock.lockSystemRoleAssignments.Unlock()
	return mock.SystemRoleAssignmentsFunc(ctx, userID, pageSize, pageOffset)
}

// SystemRoleAssignmentsCalls gets all the calls that were made to SystemRoleAssignments.
// Check the length with:
//
//	len(mockedSystemRoleCore.SystemRoleAssignmentsCalls())
func (mock *MockedSystemRoleCore) SystemRoleAssignmentsCalls() []struct {
	Ctx        context.Context
	UserID     uuid.UUID
	PageSize   int
	PageOffset int
} {
	var calls []struct {
		Ctx        context.Context
		UserID     uuid.UUID
		PageSize   int
		PageOffset int
	}
	mock.lockSystemRoleAssignments.RLock()
	calls = mock.calls.SystemRoleAssignments
	mock.lockSystemRoleAssignments.RUnlock()
	return calls
}
