// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package grpc

import (
	"context"
	"sync"

	"github.com/zorcal/theapp/backend/internal/core/data/order"
	"github.com/zorcal/theapp/backend/internal/core/mdl"
)

// Ensure, that MockedUserCore does implement UserCore.
// If this is not the case, regenerate this file with moq.
var _ UserCore = &MockedUserCore{}

// MockedUserCore is a mock implementation of UserCore.
//
//	func TestSomethingThatUsesUserCore(t *testing.T) {
//
//		// make and configure a mocked UserCore
//		mockedUserCore := &MockedUserCore{
//			ListUsersFunc: func(ctx context.Context, orderBys []order.By[mdl.UserOrderByField], pageSize int, pageOffset int) ([]mdl.User, int, error) {
//				panic("mock out the ListUsers method")
//			},
//		}
//
//		// use mockedUserCore in code that requires UserCore
//		// and then make assertions.
//
//	}
type MockedUserCore struct {
	// ListUsersFunc mocks the ListUsers method.
	ListUsersFunc func(ctx context.Context, orderBys []order.By[mdl.UserOrderByField], pageSize int, pageOffset int) ([]mdl.User, int, error)

	// calls tracks calls to the methods.
	calls struct {
		// ListUsers holds details about calls to the ListUsers method.
		ListUsers []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrderBys is the orderBys argument value.
			OrderBys []order.By[mdl.UserOrderByField]
			// PageSize is the pageSize argument value.
			PageSize int
			// PageOffset is the pageOffset argument value.
			PageOffset int
		}
	}
	lockListUsers sync.RWMutex
}

// ListUsers calls ListUsersFunc.
func (mock *MockedUserCore) ListUsers(ctx context.Context, orderBys []order.By[mdl.UserOrderByField], pageSize int, pageOffset int) ([]mdl.User, int, error) {
	if mock.ListUsersFunc == nil {
		panic("MockedUserCore.ListUsersFunc: method is nil but UserCore.ListUsers was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		OrderBys   []order.By[mdl.UserOrderByField]
		PageSize   int
		PageOffset int
	}{
		Ctx:        ctx,
		OrderBys:   orderBys,
		PageSize:   pageSize,
		PageOffset: pageOffset,
	}
	mock.lockListUsers.Lock()
	mock.calls.ListUsers = append(mock.calls.ListUsers, callInfo)
	mock.lockListUsers.Unlock()
	return mock.ListUsersFunc(ctx, orderBys, pageSize, pageOffset)
}

// ListUsersCalls gets all the calls that were made to ListUsers.
// Check the length with:
//
//	len(mockedUserCore.ListUsersCalls())
func (mock *MockedUserCore) ListUsersCalls() []struct {
	Ctx        context.Context
	OrderBys   []order.By[mdl.UserOrderByField]
	PageSize   int
	PageOffset int
} {
	var calls []struct {
		Ctx        context.Context
		OrderBys   []order.By[mdl.UserOrderByField]
		PageSize   int
		PageOffset int
	}
	mock.lockListUsers.RLock()
	calls = mock.calls.ListUsers
	mock.lockListUsers.RUnlock()
	return calls
}
