// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package grpc

import (
	"context"
	"sync"
)

// Ensure, that MockedWorkflowAuthCore does implement WorkflowAuthCore.
// If this is not the case, regenerate this file with moq.
var _ WorkflowAuthCore = &MockedWorkflowAuthCore{}

// MockedWorkflowAuthCore is a mock implementation of WorkflowAuthCore.
//
//	func TestSomethingThatUsesWorkflowAuthCore(t *testing.T) {
//
//		// make and configure a mocked WorkflowAuthCore
//		mockedWorkflowAuthCore := &MockedWorkflowAuthCore{
//			RequestMagicLinkFunc: func(ctx context.Context, email string) error {
//				panic("mock out the RequestMagicLink method")
//			},
//		}
//
//		// use mockedWorkflowAuthCore in code that requires WorkflowAuthCore
//		// and then make assertions.
//
//	}
type MockedWorkflowAuthCore struct {
	// RequestMagicLinkFunc mocks the RequestMagicLink method.
	RequestMagicLinkFunc func(ctx context.Context, email string) error

	// calls tracks calls to the methods.
	calls struct {
		// RequestMagicLink holds details about calls to the RequestMagicLink method.
		RequestMagicLink []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Email is the email argument value.
			Email string
		}
	}
	lockRequestMagicLink sync.RWMutex
}

// RequestMagicLink calls RequestMagicLinkFunc.
func (mock *MockedWorkflowAuthCore) RequestMagicLink(ctx context.Context, email string) error {
	if mock.RequestMagicLinkFunc == nil {
		panic("MockedWorkflowAuthCore.RequestMagicLinkFunc: method is nil but WorkflowAuthCore.RequestMagicLink was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Email string
	}{
		Ctx:   ctx,
		Email: email,
	}
	mock.lockRequestMagicLink.Lock()
	mock.calls.RequestMagicLink = append(mock.calls.RequestMagicLink, callInfo)
	mock.lockRequestMagicLink.Unlock()
	return mock.RequestMagicLinkFunc(ctx, email)
}

// RequestMagicLinkCalls gets all the calls that were made to RequestMagicLink.
// Check the length with:
//
//	len(mockedWorkflowAuthCore.RequestMagicLinkCalls())
func (mock *MockedWorkflowAuthCore) RequestMagicLinkCalls() []struct {
	Ctx   context.Context
	Email string
} {
	var calls []struct {
		Ctx   context.Context
		Email string
	}
	mock.lockRequestMagicLink.RLock()
	calls = mock.calls.RequestMagicLink
	mock.lockRequestMagicLink.RUnlock()
	return calls
}
