// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package auth

import (
	"context"
	"sync"

	"github.com/zorcal/theapp/backend/internal/core/pgstores/pgauth"
)

// Ensure, that MockedAuthStorer does implement AuthStorer.
// If this is not the case, regenerate this file with moq.
var _ AuthStorer = &MockedAuthStorer{}

// MockedAuthStorer is a mock implementation of AuthStorer.
//
//	func TestSomethingThatUsesAuthStorer(t *testing.T) {
//
//		// make and configure a mocked AuthStorer
//		mockedAuthStorer := &MockedAuthStorer{
//			ConsumeMagicTokenFunc: func(ctx context.Context, id int64) error {
//				panic("mock out the ConsumeMagicToken method")
//			},
//			CreateMagicTokenFunc: func(ctx context.Context, cm pgauth.CreateMagicToken) (pgauth.MagicToken, error) {
//				panic("mock out the CreateMagicToken method")
//			},
//			CreateRefreshTokenFunc: func(ctx context.Context, cr pgauth.CreateRefreshToken) (pgauth.RefreshToken, error) {
//				panic("mock out the CreateRefreshToken method")
//			},
//			MagicTokenByHashFunc: func(ctx context.Context, hash string) (pgauth.MagicToken, error) {
//				panic("mock out the MagicTokenByHash method")
//			},
//			RefreshTokenByHashFunc: func(ctx context.Context, hash string) (pgauth.RefreshToken, error) {
//				panic("mock out the RefreshTokenByHash method")
//			},
//			RevokeRefreshTokenFunc: func(ctx context.Context, id int64) error {
//				panic("mock out the RevokeRefreshToken method")
//			},
//		}
//
//		// use mockedAuthStorer in code that requires AuthStorer
//		// and then make assertions.
//
//	}
type MockedAuthStorer struct {
	// ConsumeMagicTokenFunc mocks the ConsumeMagicToken method.
	ConsumeMagicTokenFunc func(ctx context.Context, id int64) error

	// CreateMagicTokenFunc mocks the CreateMagicToken method.
	CreateMagicTokenFunc func(ctx context.Context, cm pgauth.CreateMagicToken) (pgauth.MagicToken, error)

	// CreateRefreshTokenFunc mocks the CreateRefreshToken method.
	CreateRefreshTokenFunc func(ctx context.Context, cr pgauth.CreateRefreshToken) (pgauth.RefreshToken, error)

	// MagicTokenByHashFunc mocks the MagicTokenByHash method.
	MagicTokenByHashFunc func(ctx context.Context, hash string) (pgauth.MagicToken, error)

	// RefreshTokenByHashFunc mocks the RefreshTokenByHash method.
	RefreshTokenByHashFunc func(ctx context.Context, hash string) (pgauth.RefreshToken, error)

	// RevokeRefreshTokenFunc mocks the RevokeRefreshToken method.
	RevokeRefreshTokenFunc func(ctx context.Context, id int64) error

	// calls tracks calls to the methods.
	calls struct {
		// ConsumeMagicToken holds details about calls to the ConsumeMagicToken method.
		ConsumeMagicToken []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// CreateMagicToken holds details about calls to the CreateMagicToken method.
		CreateMagicToken []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Cm is the cm argument value.
			Cm pgauth.CreateMagicToken
		}
		// CreateRefreshToken holds details about calls to the CreateRefreshToken method.
		CreateRefreshToken []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Cr is the cr argument value.
			Cr pgauth.CreateRefreshToken
		}
		// MagicTokenByHash holds details about calls to the MagicTokenByHash method.
		MagicTokenByHash []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Hash is the hash argument value.
			Hash string
		}
		// RefreshTokenByHash holds details about calls to the RefreshTokenByHash method.
		RefreshTokenByHash []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Hash is the hash argument value.
			Hash string
		}
		// RevokeRefreshToken holds details about calls to the RevokeRefreshToken method.
		RevokeRefreshToken []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
	}
	lockConsumeMagicToken  sync.RWMutex
	lockCreateMagicToken   sync.RWMutex
	lockCreateRefreshToken sync.RWMutex
	lockMagicTokenByHash   sync.RWMutex
	lockRefreshTokenByHash sync.RWMutex
	lockRevokeRefreshToken sync.RWMutex
}

// ConsumeMagicToken calls ConsumeMagicTokenFunc.
func (mock *MockedAuthStorer) ConsumeMagicToken(ctx context.Context, id int64) error {
	if mock.ConsumeMagicTokenFunc == nil {
		panic("MockedAuthStorer.ConsumeMagicTokenFunc: method is nil but AuthStorer.ConsumeMagicToken was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockConsumeMagicToken.Lock()
	mock.calls.ConsumeMagicToken = append(mock.calls.ConsumeMagicToken, callInfo)
	mock.lockConsumeMagicToken.Unlock()
	return mock.ConsumeMagicTokenFunc(ctx, id)
}

// ConsumeMagicTokenCalls gets all the calls that were made to ConsumeMagicToken.
// Check the length with:
//
//	len(mockedAuthStorer.ConsumeMagicTokenCalls())
func (mock *MockedAuthStorer) ConsumeMagicTokenCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockConsumeMagicToken.RLock()
	calls = mock.calls.ConsumeMagicToken
	mock.lockConsumeMagicToken.RUnlock()
	return calls
}

// CreateMagicToken calls CreateMagicTokenFunc.
func (mock *MockedAuthStorer) CreateMagicToken(ctx context.Context, cm pgauth.CreateMagicToken) (pgauth.MagicToken, error) {
	if mock.CreateMagicTokenFunc == nil {
		panic("MockedAuthStorer.CreateMagicTokenFunc: method is nil but AuthStorer.CreateMagicToken was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Cm  pgauth.CreateMagicToken
	}{
		Ctx: ctx,
		Cm:  cm,
	}
	mock.lockCreateMagicToken.Lock()
	mock.calls.CreateMagicToken = append(mock.calls.CreateMagicToken, callInfo)
	mock.lockCreateMagicToken.Unlock()
	return mock.CreateMagicTokenFunc(ctx, cm)
}

// CreateMagicTokenCalls gets all the calls that were made to CreateMagicToken.
// Check the length with:
//
//	len(mockedAuthStorer.CreateMagicTokenCalls())
func (mock *MockedAuthStorer) CreateMagicTokenCalls() []struct {
	Ctx context.Context
	Cm  pgauth.CreateMagicToken
} {
	var calls []struct {
		Ctx context.Context
		Cm  pgauth.CreateMagicToken
	}
	mock.lockCreateMagicToken.RLock()
	calls = mock.calls.CreateMagicToken
	mock.lockCreateMagicToken.RUnlock()
	return calls
}

// CreateRefreshToken calls CreateRefreshTokenFunc.
func (mock *MockedAuthStorer) CreateRefreshToken(ctx context.Context, cr pgauth.CreateRefreshToken) (pgauth.RefreshToken, error) {
	if mock.CreateRefreshTokenFunc == nil {
		panic("MockedAuthStorer.CreateRefreshTokenFunc: method is nil but AuthStorer.CreateRefreshToken was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Cr  pgauth.CreateRefreshToken
	}{
		Ctx: ctx,
		Cr:  cr,
	}
	mock.lockCreateRefreshToken.Lock()
	mock.calls.CreateRefreshToken = append(mock.calls.CreateRefreshToken, callInfo)
	mock.lockCreateRefreshToken.Unlock()
	return mock.CreateRefreshTokenFunc(ctx, cr)
}

// CreateRefreshTokenCalls gets all the calls that were made to CreateRefreshToken.
// Check the length with:
//
//	len(mockedAuthStorer.CreateRefreshTokenCalls())
func (mock *MockedAuthStorer) CreateRefreshTokenCalls() []struct {
	Ctx context.Context
	Cr  pgauth.CreateRefreshToken
} {
	var calls []struct {
		Ctx context.Context
		Cr  pgauth.CreateRefreshToken
	}
	mock.lockCreateRefreshToken.RLock()
	calls = mock.calls.CreateRefreshToken
	mock.lockCreateRefreshToken.RUnlock()
	return calls
}

// MagicTokenByHash calls MagicTokenByHashFunc.
func (mock *MockedAuthStorer) MagicTokenByHash(ctx context.Context, hash string) (pgauth.MagicToken, error) {
	if mock.MagicTokenByHashFunc == nil {
		panic("MockedAuthStorer.MagicTokenByHashFunc: method is nil but AuthStorer.MagicTokenByHash was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Hash string
	}{
		Ctx:  ctx,
		Hash: hash,
	}
	mock.lockMagicTokenByHash.Lock()
	mock.calls.MagicTokenByHash = append(mock.calls.MagicTokenByHash, callInfo)
	mock.lockMagicTokenByHash.Unlock()
	return mock.MagicTokenByHashFunc(ctx, hash)
}

// MagicTokenByHashCalls gets all the calls that were made to MagicTokenByHash.
// Check the length with:
//
//	len(mockedAuthStorer.MagicTokenByHashCalls())
func (mock *MockedAuthStorer) MagicTokenByHashCalls() []struct {
	Ctx  context.Context
	Hash string
} {
	var calls []struct {
		Ctx  context.Context
		Hash string
	}
	mock.lockMagicTokenByHash.RLock()
	calls = mock.calls.MagicTokenByHash
	mock.lockMagicTokenByHash.RUnlock()
	return calls
}

// RefreshTokenByHash calls RefreshTokenByHashFunc.
func (mock *MockedAuthStorer) RefreshTokenByHash(ctx context.Context, hash string) (pgauth.RefreshToken, error) {
	if mock.RefreshTokenByHashFunc == nil {
		panic("MockedAuthStorer.RefreshTokenByHashFunc: method is nil but AuthStorer.RefreshTokenByHash was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Hash string
	}{
		Ctx:  ctx,
		Hash: hash,
	}
	mock.lockRefreshTokenByHash.Lock()
	mock.calls.RefreshTokenByHash = append(mock.calls.RefreshTokenByHash, callInfo)
	mock.lockRefreshTokenByHash.Unlock()
	return mock.RefreshTokenByHashFunc(ctx, hash)
}

// RefreshTokenByHashCalls gets all the calls that were made to RefreshTokenByHash.
// Check the length with:
//
//	len(mockedAuthStorer.RefreshTokenByHashCalls())
func (mock *MockedAuthStorer) RefreshTokenByHashCalls() []struct {
	Ctx  context.Context
	Hash string
} {
	var calls []struct {
		Ctx  context.Context
		Hash string
	}
	mock.lockRefreshTokenByHash.RLock()
	calls = mock.calls.RefreshTokenByHash
	mock.lockRefreshTokenByHash.RUnlock()
	return calls
}

// RevokeRefreshToken calls RevokeRefreshTokenFunc.
func (mock *MockedAuthStorer) RevokeRefreshToken(ctx context.Context, id int64) error {
	if mock.RevokeRefreshTokenFunc == nil {
		panic("MockedAuthStorer.RevokeRefreshTokenFunc: method is nil but AuthStorer.RevokeRefreshToken was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockRevokeRefreshToken.Lock()
	mock.calls.RevokeRefreshToken = append(mock.calls.RevokeRefreshToken, callInfo)
	mock.lockRevokeRefreshToken.Unlock()
	return mock.RevokeRefreshTokenFunc(ctx, id)
}

// RevokeRefreshTokenCalls gets all the calls that were made to RevokeRefreshToken.
// Check the length with:
//
//	len(mockedAuthStorer.RevokeRefreshTokenCalls())
func (mock *MockedAuthStorer) RevokeRefreshTokenCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockRevokeRefreshToken.RLock()
	calls = mock.calls.RevokeRefreshToken
	mock.lockRevokeRefreshToken.RUnlock()
	return calls
}
