// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package auth

import (
	"context"
	"sync"
	"time"

	"github.com/google/uuid"
	"github.com/zorcal/theapp/backend/internal/core/pgstores/pgauth"
)

// Ensure, that MockedAuthStorer does implement AuthStorer.
// If this is not the case, regenerate this file with moq.
var _ AuthStorer = &MockedAuthStorer{}

// MockedAuthStorer is a mock implementation of AuthStorer.
//
//	func TestSomethingThatUsesAuthStorer(t *testing.T) {
//
//		// make and configure a mocked AuthStorer
//		mockedAuthStorer := &MockedAuthStorer{
//			ConsumeMagicLinkTokenFunc: func(ctx context.Context, id int) error {
//				panic("mock out the ConsumeMagicLinkToken method")
//			},
//			ConsumeRefreshTokenFunc: func(ctx context.Context, hash string) (pgauth.RefreshToken, error) {
//				panic("mock out the ConsumeRefreshToken method")
//			},
//			CreateMagicLinkTokenFunc: func(ctx context.Context, cm pgauth.CreateMagicLinkToken) (pgauth.MagicLinkToken, error) {
//				panic("mock out the CreateMagicLinkToken method")
//			},
//			CreateRefreshTokenFunc: func(ctx context.Context, cr pgauth.CreateRefreshToken) (pgauth.RefreshToken, error) {
//				panic("mock out the CreateRefreshToken method")
//			},
//			InvalidateUserMagicLinkTokensFunc: func(ctx context.Context, userID int) error {
//				panic("mock out the InvalidateUserMagicLinkTokens method")
//			},
//			LatestMagicLinkTokenCreatedAtFunc: func(ctx context.Context, userID int) (time.Time, error) {
//				panic("mock out the LatestMagicLinkTokenCreatedAt method")
//			},
//			LockUserFunc: func(ctx context.Context, userID int) error {
//				panic("mock out the LockUser method")
//			},
//			MagicLinkTokenByHashFunc: func(ctx context.Context, hash string) (pgauth.MagicLinkToken, error) {
//				panic("mock out the MagicLinkTokenByHash method")
//			},
//			RevokeAllUserRefreshTokensFunc: func(ctx context.Context, userExternalID uuid.UUID) error {
//				panic("mock out the RevokeAllUserRefreshTokens method")
//			},
//		}
//
//		// use mockedAuthStorer in code that requires AuthStorer
//		// and then make assertions.
//
//	}
type MockedAuthStorer struct {
	// ConsumeMagicLinkTokenFunc mocks the ConsumeMagicLinkToken method.
	ConsumeMagicLinkTokenFunc func(ctx context.Context, id int) error

	// ConsumeRefreshTokenFunc mocks the ConsumeRefreshToken method.
	ConsumeRefreshTokenFunc func(ctx context.Context, hash string) (pgauth.RefreshToken, error)

	// CreateMagicLinkTokenFunc mocks the CreateMagicLinkToken method.
	CreateMagicLinkTokenFunc func(ctx context.Context, cm pgauth.CreateMagicLinkToken) (pgauth.MagicLinkToken, error)

	// CreateRefreshTokenFunc mocks the CreateRefreshToken method.
	CreateRefreshTokenFunc func(ctx context.Context, cr pgauth.CreateRefreshToken) (pgauth.RefreshToken, error)

	// InvalidateUserMagicLinkTokensFunc mocks the InvalidateUserMagicLinkTokens method.
	InvalidateUserMagicLinkTokensFunc func(ctx context.Context, userID int) error

	// LatestMagicLinkTokenCreatedAtFunc mocks the LatestMagicLinkTokenCreatedAt method.
	LatestMagicLinkTokenCreatedAtFunc func(ctx context.Context, userID int) (time.Time, error)

	// LockUserFunc mocks the LockUser method.
	LockUserFunc func(ctx context.Context, userID int) error

	// MagicLinkTokenByHashFunc mocks the MagicLinkTokenByHash method.
	MagicLinkTokenByHashFunc func(ctx context.Context, hash string) (pgauth.MagicLinkToken, error)

	// RevokeAllUserRefreshTokensFunc mocks the RevokeAllUserRefreshTokens method.
	RevokeAllUserRefreshTokensFunc func(ctx context.Context, userExternalID uuid.UUID) error

	// calls tracks calls to the methods.
	calls struct {
		// ConsumeMagicLinkToken holds details about calls to the ConsumeMagicLinkToken method.
		ConsumeMagicLinkToken []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int
		}
		// ConsumeRefreshToken holds details about calls to the ConsumeRefreshToken method.
		ConsumeRefreshToken []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Hash is the hash argument value.
			Hash string
		}
		// CreateMagicLinkToken holds details about calls to the CreateMagicLinkToken method.
		CreateMagicLinkToken []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Cm is the cm argument value.
			Cm pgauth.CreateMagicLinkToken
		}
		// CreateRefreshToken holds details about calls to the CreateRefreshToken method.
		CreateRefreshToken []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Cr is the cr argument value.
			Cr pgauth.CreateRefreshToken
		}
		// InvalidateUserMagicLinkTokens holds details about calls to the InvalidateUserMagicLinkTokens method.
		InvalidateUserMagicLinkTokens []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID int
		}
		// LatestMagicLinkTokenCreatedAt holds details about calls to the LatestMagicLinkTokenCreatedAt method.
		LatestMagicLinkTokenCreatedAt []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID int
		}
		// LockUser holds details about calls to the LockUser method.
		LockUser []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID int
		}
		// MagicLinkTokenByHash holds details about calls to the MagicLinkTokenByHash method.
		MagicLinkTokenByHash []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Hash is the hash argument value.
			Hash string
		}
		// RevokeAllUserRefreshTokens holds details about calls to the RevokeAllUserRefreshTokens method.
		RevokeAllUserRefreshTokens []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserExternalID is the userExternalID argument value.
			UserExternalID uuid.UUID
		}
	}
	lockConsumeMagicLinkToken         sync.RWMutex
	lockConsumeRefreshToken           sync.RWMutex
	lockCreateMagicLinkToken          sync.RWMutex
	lockCreateRefreshToken            sync.RWMutex
	lockInvalidateUserMagicLinkTokens sync.RWMutex
	lockLatestMagicLinkTokenCreatedAt sync.RWMutex
	lockLockUser                      sync.RWMutex
	lockMagicLinkTokenByHash          sync.RWMutex
	lockRevokeAllUserRefreshTokens    sync.RWMutex
}

// ConsumeMagicLinkToken calls ConsumeMagicLinkTokenFunc.
func (mock *MockedAuthStorer) ConsumeMagicLinkToken(ctx context.Context, id int) error {
	if mock.ConsumeMagicLinkTokenFunc == nil {
		panic("MockedAuthStorer.ConsumeMagicLinkTokenFunc: method is nil but AuthStorer.ConsumeMagicLinkToken was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockConsumeMagicLinkToken.Lock()
	mock.calls.ConsumeMagicLinkToken = append(mock.calls.ConsumeMagicLinkToken, callInfo)
	mock.lockConsumeMagicLinkToken.Unlock()
	return mock.ConsumeMagicLinkTokenFunc(ctx, id)
}

// ConsumeMagicLinkTokenCalls gets all the calls that were made to ConsumeMagicLinkToken.
// Check the length with:
//
//	len(mockedAuthStorer.ConsumeMagicLinkTokenCalls())
func (mock *MockedAuthStorer) ConsumeMagicLinkTokenCalls() []struct {
	Ctx context.Context
	ID  int
} {
	var calls []struct {
		Ctx context.Context
		ID  int
	}
	mock.lockConsumeMagicLinkToken.RLock()
	calls = mock.calls.ConsumeMagicLinkToken
	mock.lockConsumeMagicLinkToken.RUnlock()
	return calls
}

// ConsumeRefreshToken calls ConsumeRefreshTokenFunc.
func (mock *MockedAuthStorer) ConsumeRefreshToken(ctx context.Context, hash string) (pgauth.RefreshToken, error) {
	if mock.ConsumeRefreshTokenFunc == nil {
		panic("MockedAuthStorer.ConsumeRefreshTokenFunc: method is nil but AuthStorer.ConsumeRefreshToken was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Hash string
	}{
		Ctx:  ctx,
		Hash: hash,
	}
	mock.lockConsumeRefreshToken.Lock()
	mock.calls.ConsumeRefreshToken = append(mock.calls.ConsumeRefreshToken, callInfo)
	mock.lockConsumeRefreshToken.Unlock()
	return mock.ConsumeRefreshTokenFunc(ctx, hash)
}

// ConsumeRefreshTokenCalls gets all the calls that were made to ConsumeRefreshToken.
// Check the length with:
//
//	len(mockedAuthStorer.ConsumeRefreshTokenCalls())
func (mock *MockedAuthStorer) ConsumeRefreshTokenCalls() []struct {
	Ctx  context.Context
	Hash string
} {
	var calls []struct {
		Ctx  context.Context
		Hash string
	}
	mock.lockConsumeRefreshToken.RLock()
	calls = mock.calls.ConsumeRefreshToken
	mock.lockConsumeRefreshToken.RUnlock()
	return calls
}

// CreateMagicLinkToken calls CreateMagicLinkTokenFunc.
func (mock *MockedAuthStorer) CreateMagicLinkToken(ctx context.Context, cm pgauth.CreateMagicLinkToken) (pgauth.MagicLinkToken, error) {
	if mock.CreateMagicLinkTokenFunc == nil {
		panic("MockedAuthStorer.CreateMagicLinkTokenFunc: method is nil but AuthStorer.CreateMagicLinkToken was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Cm  pgauth.CreateMagicLinkToken
	}{
		Ctx: ctx,
		Cm:  cm,
	}
	mock.lockCreateMagicLinkToken.Lock()
	mock.calls.CreateMagicLinkToken = append(mock.calls.CreateMagicLinkToken, callInfo)
	mock.lockCreateMagicLinkToken.Unlock()
	return mock.CreateMagicLinkTokenFunc(ctx, cm)
}

// CreateMagicLinkTokenCalls gets all the calls that were made to CreateMagicLinkToken.
// Check the length with:
//
//	len(mockedAuthStorer.CreateMagicLinkTokenCalls())
func (mock *MockedAuthStorer) CreateMagicLinkTokenCalls() []struct {
	Ctx context.Context
	Cm  pgauth.CreateMagicLinkToken
} {
	var calls []struct {
		Ctx context.Context
		Cm  pgauth.CreateMagicLinkToken
	}
	mock.lockCreateMagicLinkToken.RLock()
	calls = mock.calls.CreateMagicLinkToken
	mock.lockCreateMagicLinkToken.RUnlock()
	return calls
}

// CreateRefreshToken calls CreateRefreshTokenFunc.
func (mock *MockedAuthStorer) CreateRefreshToken(ctx context.Context, cr pgauth.CreateRefreshToken) (pgauth.RefreshToken, error) {
	if mock.CreateRefreshTokenFunc == nil {
		panic("MockedAuthStorer.CreateRefreshTokenFunc: method is nil but AuthStorer.CreateRefreshToken was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Cr  pgauth.CreateRefreshToken
	}{
		Ctx: ctx,
		Cr:  cr,
	}
	mock.lockCreateRefreshToken.Lock()
	mock.calls.CreateRefreshToken = append(mock.calls.CreateRefreshToken, callInfo)
	mock.lockCreateRefreshToken.Unlock()
	return mock.CreateRefreshTokenFunc(ctx, cr)
}

// CreateRefreshTokenCalls gets all the calls that were made to CreateRefreshToken.
// Check the length with:
//
//	len(mockedAuthStorer.CreateRefreshTokenCalls())
func (mock *MockedAuthStorer) CreateRefreshTokenCalls() []struct {
	Ctx context.Context
	Cr  pgauth.CreateRefreshToken
} {
	var calls []struct {
		Ctx context.Context
		Cr  pgauth.CreateRefreshToken
	}
	mock.lockCreateRefreshToken.RLock()
	calls = mock.calls.CreateRefreshToken
	mock.lockCreateRefreshToken.RUnlock()
	return calls
}

// InvalidateUserMagicLinkTokens calls InvalidateUserMagicLinkTokensFunc.
func (mock *MockedAuthStorer) InvalidateUserMagicLinkTokens(ctx context.Context, userID int) error {
	if mock.InvalidateUserMagicLinkTokensFunc == nil {
		panic("MockedAuthStorer.InvalidateUserMagicLinkTokensFunc: method is nil but AuthStorer.InvalidateUserMagicLinkTokens was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID int
	}{
		Ctx:    ctx,
		UserID: userID,
	}
	mock.lockInvalidateUserMagicLinkTokens.Lock()
	mock.calls.InvalidateUserMagicLinkTokens = append(mock.calls.InvalidateUserMagicLinkTokens, callInfo)
	mock.lockInvalidateUserMagicLinkTokens.Unlock()
	return mock.InvalidateUserMagicLinkTokensFunc(ctx, userID)
}

// InvalidateUserMagicLinkTokensCalls gets all the calls that were made to InvalidateUserMagicLinkTokens.
// Check the length with:
//
//	len(mockedAuthStorer.InvalidateUserMagicLinkTokensCalls())
func (mock *MockedAuthStorer) InvalidateUserMagicLinkTokensCalls() []struct {
	Ctx    context.Context
	UserID int
} {
	var calls []struct {
		Ctx    context.Context
		UserID int
	}
	mock.lockInvalidateUserMagicLinkTokens.RLock()
	calls = mock.calls.InvalidateUserMagicLinkTokens
	mock.lockInvalidateUserMagicLinkTokens.RUnlock()
	return calls
}

// LatestMagicLinkTokenCreatedAt calls LatestMagicLinkTokenCreatedAtFunc.
func (mock *MockedAuthStorer) LatestMagicLinkTokenCreatedAt(ctx context.Context, userID int) (time.Time, error) {
	if mock.LatestMagicLinkTokenCreatedAtFunc == nil {
		panic("MockedAuthStorer.LatestMagicLinkTokenCreatedAtFunc: method is nil but AuthStorer.LatestMagicLinkTokenCreatedAt was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID int
	}{
		Ctx:    ctx,
		UserID: userID,
	}
	mock.lockLatestMagicLinkTokenCreatedAt.Lock()
	mock.calls.LatestMagicLinkTokenCreatedAt = append(mock.calls.LatestMagicLinkTokenCreatedAt, callInfo)
	mock.lockLatestMagicLinkTokenCreatedAt.Unlock()
	return mock.LatestMagicLinkTokenCreatedAtFunc(ctx, userID)
}

// LatestMagicLinkTokenCreatedAtCalls gets all the calls that were made to LatestMagicLinkTokenCreatedAt.
// Check the length with:
//
//	len(mockedAuthStorer.LatestMagicLinkTokenCreatedAtCalls())
func (mock *MockedAuthStorer) LatestMagicLinkTokenCreatedAtCalls() []struct {
	Ctx    context.Context
	UserID int
} {
	var calls []struct {
		Ctx    context.Context
		UserID int
	}
	mock.lockLatestMagicLinkTokenCreatedAt.RLock()
	calls = mock.calls.LatestMagicLinkTokenCreatedAt
	mock.lockLatestMagicLinkTokenCreatedAt.RUnlock()
	return calls
}

// LockUser calls LockUserFunc.
func (mock *MockedAuthStorer) LockUser(ctx context.Context, userID int) error {
	if mock.LockUserFunc == nil {
		panic("MockedAuthStorer.LockUserFunc: method is nil but AuthStorer.LockUser was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID int
	}{
		Ctx:    ctx,
		UserID: userID,
	}
	mock.lockLockUser.Lock()
	mock.calls.LockUser = append(mock.calls.LockUser, callInfo)
	mock.lockLockUser.Unlock()
	return mock.LockUserFunc(ctx, userID)
}

// LockUserCalls gets all the calls that were made to LockUser.
// Check the length with:
//
//	len(mockedAuthStorer.LockUserCalls())
func (mock *MockedAuthStorer) LockUserCalls() []struct {
	Ctx    context.Context
	UserID int
} {
	var calls []struct {
		Ctx    context.Context
		UserID int
	}
	mock.lockLockUser.RLock()
	calls = mock.calls.LockUser
	mock.lockLockUser.RUnlock()
	return calls
}

// MagicLinkTokenByHash calls MagicLinkTokenByHashFunc.
func (mock *MockedAuthStorer) MagicLinkTokenByHash(ctx context.Context, hash string) (pgauth.MagicLinkToken, error) {
	if mock.MagicLinkTokenByHashFunc == nil {
		panic("MockedAuthStorer.MagicLinkTokenByHashFunc: method is nil but AuthStorer.MagicLinkTokenByHash was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Hash string
	}{
		Ctx:  ctx,
		Hash: hash,
	}
	mock.lockMagicLinkTokenByHash.Lock()
	mock.calls.MagicLinkTokenByHash = append(mock.calls.MagicLinkTokenByHash, callInfo)
	mock.lockMagicLinkTokenByHash.Unlock()
	return mock.MagicLinkTokenByHashFunc(ctx, hash)
}

// MagicLinkTokenByHashCalls gets all the calls that were made to MagicLinkTokenByHash.
// Check the length with:
//
//	len(mockedAuthStorer.MagicLinkTokenByHashCalls())
func (mock *MockedAuthStorer) MagicLinkTokenByHashCalls() []struct {
	Ctx  context.Context
	Hash string
} {
	var calls []struct {
		Ctx  context.Context
		Hash string
	}
	mock.lockMagicLinkTokenByHash.RLock()
	calls = mock.calls.MagicLinkTokenByHash
	mock.lockMagicLinkTokenByHash.RUnlock()
	return calls
}

// RevokeAllUserRefreshTokens calls RevokeAllUserRefreshTokensFunc.
func (mock *MockedAuthStorer) RevokeAllUserRefreshTokens(ctx context.Context, userExternalID uuid.UUID) error {
	if mock.RevokeAllUserRefreshTokensFunc == nil {
		panic("MockedAuthStorer.RevokeAllUserRefreshTokensFunc: method is nil but AuthStorer.RevokeAllUserRefreshTokens was just called")
	}
	callInfo := struct {
		Ctx            context.Context
		UserExternalID uuid.UUID
	}{
		Ctx:            ctx,
		UserExternalID: userExternalID,
	}
	mock.lockRevokeAllUserRefreshTokens.Lock()
	mock.calls.RevokeAllUserRefreshTokens = append(mock.calls.RevokeAllUserRefreshTokens, callInfo)
	mock.lockRevokeAllUserRefreshTokens.Unlock()
	return mock.RevokeAllUserRefreshTokensFunc(ctx, userExternalID)
}

// RevokeAllUserRefreshTokensCalls gets all the calls that were made to RevokeAllUserRefreshTokens.
// Check the length with:
//
//	len(mockedAuthStorer.RevokeAllUserRefreshTokensCalls())
func (mock *MockedAuthStorer) RevokeAllUserRefreshTokensCalls() []struct {
	Ctx            context.Context
	UserExternalID uuid.UUID
} {
	var calls []struct {
		Ctx            context.Context
		UserExternalID uuid.UUID
	}
	mock.lockRevokeAllUserRefreshTokens.RLock()
	calls = mock.calls.RevokeAllUserRefreshTokens
	mock.lockRevokeAllUserRefreshTokens.RUnlock()
	return calls
}
