// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package auth

import (
	"context"
	"sync"

	"github.com/google/uuid"
	"github.com/zorcal/theapp/backend/internal/core/pgstores/pgrbac"
)

// Ensure, that MockedPermissionStorer does implement PermissionStorer.
// If this is not the case, regenerate this file with moq.
var _ PermissionStorer = &MockedPermissionStorer{}

// MockedPermissionStorer is a mock implementation of PermissionStorer.
//
//	func TestSomethingThatUsesPermissionStorer(t *testing.T) {
//
//		// make and configure a mocked PermissionStorer
//		mockedPermissionStorer := &MockedPermissionStorer{
//			OrgPermissionsByProjectIDFunc: func(ctx context.Context, userID uuid.UUID, projectID int) (pgrbac.OrgPermissions, error) {
//				panic("mock out the OrgPermissionsByProjectID method")
//			},
//			PermissionsByScopeFunc: func(ctx context.Context, userID uuid.UUID, projectID int) (pgrbac.PermissionsByScope, error) {
//				panic("mock out the PermissionsByScope method")
//			},
//			ProjectPermissionsFunc: func(ctx context.Context, userID uuid.UUID, projectID int) (pgrbac.ProjectPermissions, error) {
//				panic("mock out the ProjectPermissions method")
//			},
//			SystemPermissionsFunc: func(ctx context.Context, userID uuid.UUID) ([]string, error) {
//				panic("mock out the SystemPermissions method")
//			},
//		}
//
//		// use mockedPermissionStorer in code that requires PermissionStorer
//		// and then make assertions.
//
//	}
type MockedPermissionStorer struct {
	// OrgPermissionsByProjectIDFunc mocks the OrgPermissionsByProjectID method.
	OrgPermissionsByProjectIDFunc func(ctx context.Context, userID uuid.UUID, projectID int) (pgrbac.OrgPermissions, error)

	// PermissionsByScopeFunc mocks the PermissionsByScope method.
	PermissionsByScopeFunc func(ctx context.Context, userID uuid.UUID, projectID int) (pgrbac.PermissionsByScope, error)

	// ProjectPermissionsFunc mocks the ProjectPermissions method.
	ProjectPermissionsFunc func(ctx context.Context, userID uuid.UUID, projectID int) (pgrbac.ProjectPermissions, error)

	// SystemPermissionsFunc mocks the SystemPermissions method.
	SystemPermissionsFunc func(ctx context.Context, userID uuid.UUID) ([]string, error)

	// calls tracks calls to the methods.
	calls struct {
		// OrgPermissionsByProjectID holds details about calls to the OrgPermissionsByProjectID method.
		OrgPermissionsByProjectID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID uuid.UUID
			// ProjectID is the projectID argument value.
			ProjectID int
		}
		// PermissionsByScope holds details about calls to the PermissionsByScope method.
		PermissionsByScope []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID uuid.UUID
			// ProjectID is the projectID argument value.
			ProjectID int
		}
		// ProjectPermissions holds details about calls to the ProjectPermissions method.
		ProjectPermissions []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID uuid.UUID
			// ProjectID is the projectID argument value.
			ProjectID int
		}
		// SystemPermissions holds details about calls to the SystemPermissions method.
		SystemPermissions []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID uuid.UUID
		}
	}
	lockOrgPermissionsByProjectID sync.RWMutex
	lockPermissionsByScope        sync.RWMutex
	lockProjectPermissions        sync.RWMutex
	lockSystemPermissions         sync.RWMutex
}

// OrgPermissionsByProjectID calls OrgPermissionsByProjectIDFunc.
func (mock *MockedPermissionStorer) OrgPermissionsByProjectID(ctx context.Context, userID uuid.UUID, projectID int) (pgrbac.OrgPermissions, error) {
	if mock.OrgPermissionsByProjectIDFunc == nil {
		panic("MockedPermissionStorer.OrgPermissionsByProjectIDFunc: method is nil but PermissionStorer.OrgPermissionsByProjectID was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		UserID    uuid.UUID
		ProjectID int
	}{
		Ctx:       ctx,
		UserID:    userID,
		ProjectID: projectID,
	}
	mock.lockOrgPermissionsByProjectID.Lock()
	mock.calls.OrgPermissionsByProjectID = append(mock.calls.OrgPermissionsByProjectID, callInfo)
	mock.lockOrgPermissionsByProjectID.Unlock()
	return mock.OrgPermissionsByProjectIDFunc(ctx, userID, projectID)
}

// OrgPermissionsByProjectIDCalls gets all the calls that were made to OrgPermissionsByProjectID.
// Check the length with:
//
//	len(mockedPermissionStorer.OrgPermissionsByProjectIDCalls())
func (mock *MockedPermissionStorer) OrgPermissionsByProjectIDCalls() []struct {
	Ctx       context.Context
	UserID    uuid.UUID
	ProjectID int
} {
	var calls []struct {
		Ctx       context.Context
		UserID    uuid.UUID
		ProjectID int
	}
	mock.lockOrgPermissionsByProjectID.RLock()
	calls = mock.calls.OrgPermissionsByProjectID
	mock.lockOrgPermissionsByProjectID.RUnlock()
	return calls
}

// PermissionsByScope calls PermissionsByScopeFunc.
func (mock *MockedPermissionStorer) PermissionsByScope(ctx context.Context, userID uuid.UUID, projectID int) (pgrbac.PermissionsByScope, error) {
	if mock.PermissionsByScopeFunc == nil {
		panic("MockedPermissionStorer.PermissionsByScopeFunc: method is nil but PermissionStorer.PermissionsByScope was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		UserID    uuid.UUID
		ProjectID int
	}{
		Ctx:       ctx,
		UserID:    userID,
		ProjectID: projectID,
	}
	mock.lockPermissionsByScope.Lock()
	mock.calls.PermissionsByScope = append(mock.calls.PermissionsByScope, callInfo)
	mock.lockPermissionsByScope.Unlock()
	return mock.PermissionsByScopeFunc(ctx, userID, projectID)
}

// PermissionsByScopeCalls gets all the calls that were made to PermissionsByScope.
// Check the length with:
//
//	len(mockedPermissionStorer.PermissionsByScopeCalls())
func (mock *MockedPermissionStorer) PermissionsByScopeCalls() []struct {
	Ctx       context.Context
	UserID    uuid.UUID
	ProjectID int
} {
	var calls []struct {
		Ctx       context.Context
		UserID    uuid.UUID
		ProjectID int
	}
	mock.lockPermissionsByScope.RLock()
	calls = mock.calls.PermissionsByScope
	mock.lockPermissionsByScope.RUnlock()
	return calls
}

// ProjectPermissions calls ProjectPermissionsFunc.
func (mock *MockedPermissionStorer) ProjectPermissions(ctx context.Context, userID uuid.UUID, projectID int) (pgrbac.ProjectPermissions, error) {
	if mock.ProjectPermissionsFunc == nil {
		panic("MockedPermissionStorer.ProjectPermissionsFunc: method is nil but PermissionStorer.ProjectPermissions was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		UserID    uuid.UUID
		ProjectID int
	}{
		Ctx:       ctx,
		UserID:    userID,
		ProjectID: projectID,
	}
	mock.lockProjectPermissions.Lock()
	mock.calls.ProjectPermissions = append(mock.calls.ProjectPermissions, callInfo)
	mock.lockProjectPermissions.Unlock()
	return mock.ProjectPermissionsFunc(ctx, userID, projectID)
}

// ProjectPermissionsCalls gets all the calls that were made to ProjectPermissions.
// Check the length with:
//
//	len(mockedPermissionStorer.ProjectPermissionsCalls())
func (mock *MockedPermissionStorer) ProjectPermissionsCalls() []struct {
	Ctx       context.Context
	UserID    uuid.UUID
	ProjectID int
} {
	var calls []struct {
		Ctx       context.Context
		UserID    uuid.UUID
		ProjectID int
	}
	mock.lockProjectPermissions.RLock()
	calls = mock.calls.ProjectPermissions
	mock.lockProjectPermissions.RUnlock()
	return calls
}

// SystemPermissions calls SystemPermissionsFunc.
func (mock *MockedPermissionStorer) SystemPermissions(ctx context.Context, userID uuid.UUID) ([]string, error) {
	if mock.SystemPermissionsFunc == nil {
		panic("MockedPermissionStorer.SystemPermissionsFunc: method is nil but PermissionStorer.SystemPermissions was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID uuid.UUID
	}{
		Ctx:    ctx,
		UserID: userID,
	}
	mock.lockSystemPermissions.Lock()
	mock.calls.SystemPermissions = append(mock.calls.SystemPermissions, callInfo)
	mock.lockSystemPermissions.Unlock()
	return mock.SystemPermissionsFunc(ctx, userID)
}

// SystemPermissionsCalls gets all the calls that were made to SystemPermissions.
// Check the length with:
//
//	len(mockedPermissionStorer.SystemPermissionsCalls())
func (mock *MockedPermissionStorer) SystemPermissionsCalls() []struct {
	Ctx    context.Context
	UserID uuid.UUID
} {
	var calls []struct {
		Ctx    context.Context
		UserID uuid.UUID
	}
	mock.lockSystemPermissions.RLock()
	calls = mock.calls.SystemPermissions
	mock.lockSystemPermissions.RUnlock()
	return calls
}
