// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package auth

import (
	"context"
	"sync"

	"github.com/google/uuid"
	"github.com/zorcal/theapp/backend/internal/core/pgstores/pgrbac"
)

// Ensure, that MockedPermissionStorer does implement PermissionStorer.
// If this is not the case, regenerate this file with moq.
var _ PermissionStorer = &MockedPermissionStorer{}

// MockedPermissionStorer is a mock implementation of PermissionStorer.
//
//	func TestSomethingThatUsesPermissionStorer(t *testing.T) {
//
//		// make and configure a mocked PermissionStorer
//		mockedPermissionStorer := &MockedPermissionStorer{
//			OrgPermissionsByProjectIDFunc: func(ctx context.Context, userID uuid.UUID, projectID int) (pgrbac.OrgPermissions, error) {
//				panic("mock out the OrgPermissionsByProjectID method")
//			},
//			ProjectPermissionsFunc: func(ctx context.Context, userID uuid.UUID, projectID int) (pgrbac.ProjectPermissions, error) {
//				panic("mock out the ProjectPermissions method")
//			},
//			UserSystemPermissionsByExternalIDFunc: func(ctx context.Context, userID uuid.UUID) ([]string, error) {
//				panic("mock out the UserSystemPermissionsByExternalID method")
//			},
//		}
//
//		// use mockedPermissionStorer in code that requires PermissionStorer
//		// and then make assertions.
//
//	}
type MockedPermissionStorer struct {
	// OrgPermissionsByProjectIDFunc mocks the OrgPermissionsByProjectID method.
	OrgPermissionsByProjectIDFunc func(ctx context.Context, userID uuid.UUID, projectID int) (pgrbac.OrgPermissions, error)

	// ProjectPermissionsFunc mocks the ProjectPermissions method.
	ProjectPermissionsFunc func(ctx context.Context, userID uuid.UUID, projectID int) (pgrbac.ProjectPermissions, error)

	// UserSystemPermissionsByExternalIDFunc mocks the UserSystemPermissionsByExternalID method.
	UserSystemPermissionsByExternalIDFunc func(ctx context.Context, userID uuid.UUID) ([]string, error)

	// calls tracks calls to the methods.
	calls struct {
		// OrgPermissionsByProjectID holds details about calls to the OrgPermissionsByProjectID method.
		OrgPermissionsByProjectID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID uuid.UUID
			// ProjectID is the projectID argument value.
			ProjectID int
		}
		// ProjectPermissions holds details about calls to the ProjectPermissions method.
		ProjectPermissions []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID uuid.UUID
			// ProjectID is the projectID argument value.
			ProjectID int
		}
		// UserSystemPermissionsByExternalID holds details about calls to the UserSystemPermissionsByExternalID method.
		UserSystemPermissionsByExternalID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID uuid.UUID
		}
	}
	lockOrgPermissionsByProjectID         sync.RWMutex
	lockProjectPermissions                sync.RWMutex
	lockUserSystemPermissionsByExternalID sync.RWMutex
}

// OrgPermissionsByProjectID calls OrgPermissionsByProjectIDFunc.
func (mock *MockedPermissionStorer) OrgPermissionsByProjectID(ctx context.Context, userID uuid.UUID, projectID int) (pgrbac.OrgPermissions, error) {
	if mock.OrgPermissionsByProjectIDFunc == nil {
		panic("MockedPermissionStorer.OrgPermissionsByProjectIDFunc: method is nil but PermissionStorer.OrgPermissionsByProjectID was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		UserID    uuid.UUID
		ProjectID int
	}{
		Ctx:       ctx,
		UserID:    userID,
		ProjectID: projectID,
	}
	mock.lockOrgPermissionsByProjectID.Lock()
	mock.calls.OrgPermissionsByProjectID = append(mock.calls.OrgPermissionsByProjectID, callInfo)
	mock.lockOrgPermissionsByProjectID.Unlock()
	return mock.OrgPermissionsByProjectIDFunc(ctx, userID, projectID)
}

// OrgPermissionsByProjectIDCalls gets all the calls that were made to OrgPermissionsByProjectID.
// Check the length with:
//
//	len(mockedPermissionStorer.OrgPermissionsByProjectIDCalls())
func (mock *MockedPermissionStorer) OrgPermissionsByProjectIDCalls() []struct {
	Ctx       context.Context
	UserID    uuid.UUID
	ProjectID int
} {
	var calls []struct {
		Ctx       context.Context
		UserID    uuid.UUID
		ProjectID int
	}
	mock.lockOrgPermissionsByProjectID.RLock()
	calls = mock.calls.OrgPermissionsByProjectID
	mock.lockOrgPermissionsByProjectID.RUnlock()
	return calls
}

// ProjectPermissions calls ProjectPermissionsFunc.
func (mock *MockedPermissionStorer) ProjectPermissions(ctx context.Context, userID uuid.UUID, projectID int) (pgrbac.ProjectPermissions, error) {
	if mock.ProjectPermissionsFunc == nil {
		panic("MockedPermissionStorer.ProjectPermissionsFunc: method is nil but PermissionStorer.ProjectPermissions was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		UserID    uuid.UUID
		ProjectID int
	}{
		Ctx:       ctx,
		UserID:    userID,
		ProjectID: projectID,
	}
	mock.lockProjectPermissions.Lock()
	mock.calls.ProjectPermissions = append(mock.calls.ProjectPermissions, callInfo)
	mock.lockProjectPermissions.Unlock()
	return mock.ProjectPermissionsFunc(ctx, userID, projectID)
}

// ProjectPermissionsCalls gets all the calls that were made to ProjectPermissions.
// Check the length with:
//
//	len(mockedPermissionStorer.ProjectPermissionsCalls())
func (mock *MockedPermissionStorer) ProjectPermissionsCalls() []struct {
	Ctx       context.Context
	UserID    uuid.UUID
	ProjectID int
} {
	var calls []struct {
		Ctx       context.Context
		UserID    uuid.UUID
		ProjectID int
	}
	mock.lockProjectPermissions.RLock()
	calls = mock.calls.ProjectPermissions
	mock.lockProjectPermissions.RUnlock()
	return calls
}

// UserSystemPermissionsByExternalID calls UserSystemPermissionsByExternalIDFunc.
func (mock *MockedPermissionStorer) UserSystemPermissionsByExternalID(ctx context.Context, userID uuid.UUID) ([]string, error) {
	if mock.UserSystemPermissionsByExternalIDFunc == nil {
		panic("MockedPermissionStorer.UserSystemPermissionsByExternalIDFunc: method is nil but PermissionStorer.UserSystemPermissionsByExternalID was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID uuid.UUID
	}{
		Ctx:    ctx,
		UserID: userID,
	}
	mock.lockUserSystemPermissionsByExternalID.Lock()
	mock.calls.UserSystemPermissionsByExternalID = append(mock.calls.UserSystemPermissionsByExternalID, callInfo)
	mock.lockUserSystemPermissionsByExternalID.Unlock()
	return mock.UserSystemPermissionsByExternalIDFunc(ctx, userID)
}

// UserSystemPermissionsByExternalIDCalls gets all the calls that were made to UserSystemPermissionsByExternalID.
// Check the length with:
//
//	len(mockedPermissionStorer.UserSystemPermissionsByExternalIDCalls())
func (mock *MockedPermissionStorer) UserSystemPermissionsByExternalIDCalls() []struct {
	Ctx    context.Context
	UserID uuid.UUID
} {
	var calls []struct {
		Ctx    context.Context
		UserID uuid.UUID
	}
	mock.lockUserSystemPermissionsByExternalID.RLock()
	calls = mock.calls.UserSystemPermissionsByExternalID
	mock.lockUserSystemPermissionsByExternalID.RUnlock()
	return calls
}
