// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package auth

import (
	"context"
	"sync"

	"github.com/zorcal/theapp/backend/internal/core/pgstores/pguser"
)

// Ensure, that MockedUserStorer does implement UserStorer.
// If this is not the case, regenerate this file with moq.
var _ UserStorer = &MockedUserStorer{}

// MockedUserStorer is a mock implementation of UserStorer.
//
//	func TestSomethingThatUsesUserStorer(t *testing.T) {
//
//		// make and configure a mocked UserStorer
//		mockedUserStorer := &MockedUserStorer{
//			CreateUserFunc: func(ctx context.Context, cu pguser.CreateUser) (pguser.User, error) {
//				panic("mock out the CreateUser method")
//			},
//			UserByEmailFunc: func(ctx context.Context, email string) (pguser.User, error) {
//				panic("mock out the UserByEmail method")
//			},
//		}
//
//		// use mockedUserStorer in code that requires UserStorer
//		// and then make assertions.
//
//	}
type MockedUserStorer struct {
	// CreateUserFunc mocks the CreateUser method.
	CreateUserFunc func(ctx context.Context, cu pguser.CreateUser) (pguser.User, error)

	// UserByEmailFunc mocks the UserByEmail method.
	UserByEmailFunc func(ctx context.Context, email string) (pguser.User, error)

	// calls tracks calls to the methods.
	calls struct {
		// CreateUser holds details about calls to the CreateUser method.
		CreateUser []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Cu is the cu argument value.
			Cu pguser.CreateUser
		}
		// UserByEmail holds details about calls to the UserByEmail method.
		UserByEmail []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Email is the email argument value.
			Email string
		}
	}
	lockCreateUser  sync.RWMutex
	lockUserByEmail sync.RWMutex
}

// CreateUser calls CreateUserFunc.
func (mock *MockedUserStorer) CreateUser(ctx context.Context, cu pguser.CreateUser) (pguser.User, error) {
	if mock.CreateUserFunc == nil {
		panic("MockedUserStorer.CreateUserFunc: method is nil but UserStorer.CreateUser was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Cu  pguser.CreateUser
	}{
		Ctx: ctx,
		Cu:  cu,
	}
	mock.lockCreateUser.Lock()
	mock.calls.CreateUser = append(mock.calls.CreateUser, callInfo)
	mock.lockCreateUser.Unlock()
	return mock.CreateUserFunc(ctx, cu)
}

// CreateUserCalls gets all the calls that were made to CreateUser.
// Check the length with:
//
//	len(mockedUserStorer.CreateUserCalls())
func (mock *MockedUserStorer) CreateUserCalls() []struct {
	Ctx context.Context
	Cu  pguser.CreateUser
} {
	var calls []struct {
		Ctx context.Context
		Cu  pguser.CreateUser
	}
	mock.lockCreateUser.RLock()
	calls = mock.calls.CreateUser
	mock.lockCreateUser.RUnlock()
	return calls
}

// UserByEmail calls UserByEmailFunc.
func (mock *MockedUserStorer) UserByEmail(ctx context.Context, email string) (pguser.User, error) {
	if mock.UserByEmailFunc == nil {
		panic("MockedUserStorer.UserByEmailFunc: method is nil but UserStorer.UserByEmail was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Email string
	}{
		Ctx:   ctx,
		Email: email,
	}
	mock.lockUserByEmail.Lock()
	mock.calls.UserByEmail = append(mock.calls.UserByEmail, callInfo)
	mock.lockUserByEmail.Unlock()
	return mock.UserByEmailFunc(ctx, email)
}

// UserByEmailCalls gets all the calls that were made to UserByEmail.
// Check the length with:
//
//	len(mockedUserStorer.UserByEmailCalls())
func (mock *MockedUserStorer) UserByEmailCalls() []struct {
	Ctx   context.Context
	Email string
} {
	var calls []struct {
		Ctx   context.Context
		Email string
	}
	mock.lockUserByEmail.RLock()
	calls = mock.calls.UserByEmail
	mock.lockUserByEmail.RUnlock()
	return calls
}
