// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package user

import (
	"context"
	"sync"

	"github.com/google/uuid"
	"github.com/zorcal/theapp/backend/internal/core/pgstores/pguser"
	"github.com/zorcal/theapp/backend/internal/data/order"
)

// Ensure, that MockedUserStorer does implement UserStorer.
// If this is not the case, regenerate this file with moq.
var _ UserStorer = &MockedUserStorer{}

// MockedUserStorer is a mock implementation of UserStorer.
//
//	func TestSomethingThatUsesUserStorer(t *testing.T) {
//
//		// make and configure a mocked UserStorer
//		mockedUserStorer := &MockedUserStorer{
//			CreateUserFunc: func(ctx context.Context, cu pguser.CreateUser) (pguser.User, error) {
//				panic("mock out the CreateUser method")
//			},
//			SoftDeleteUserFunc: func(ctx context.Context, id uuid.UUID) error {
//				panic("mock out the SoftDeleteUser method")
//			},
//			UpdateUserFunc: func(ctx context.Context, uu pguser.UpdateUser) (pguser.User, error) {
//				panic("mock out the UpdateUser method")
//			},
//			UserByEmailFunc: func(ctx context.Context, email string) (pguser.User, error) {
//				panic("mock out the UserByEmail method")
//			},
//			UserByExternalIDFunc: func(ctx context.Context, id uuid.UUID) (pguser.User, error) {
//				panic("mock out the UserByExternalID method")
//			},
//			UsersFunc: func(ctx context.Context, filter pguser.Filter, orderBys []order.By[pguser.OrderByField], pageSize int, pageOffset int) ([]pguser.User, int, error) {
//				panic("mock out the Users method")
//			},
//		}
//
//		// use mockedUserStorer in code that requires UserStorer
//		// and then make assertions.
//
//	}
type MockedUserStorer struct {
	// CreateUserFunc mocks the CreateUser method.
	CreateUserFunc func(ctx context.Context, cu pguser.CreateUser) (pguser.User, error)

	// SoftDeleteUserFunc mocks the SoftDeleteUser method.
	SoftDeleteUserFunc func(ctx context.Context, id uuid.UUID) error

	// UpdateUserFunc mocks the UpdateUser method.
	UpdateUserFunc func(ctx context.Context, uu pguser.UpdateUser) (pguser.User, error)

	// UserByEmailFunc mocks the UserByEmail method.
	UserByEmailFunc func(ctx context.Context, email string) (pguser.User, error)

	// UserByExternalIDFunc mocks the UserByExternalID method.
	UserByExternalIDFunc func(ctx context.Context, id uuid.UUID) (pguser.User, error)

	// UsersFunc mocks the Users method.
	UsersFunc func(ctx context.Context, filter pguser.Filter, orderBys []order.By[pguser.OrderByField], pageSize int, pageOffset int) ([]pguser.User, int, error)

	// calls tracks calls to the methods.
	calls struct {
		// CreateUser holds details about calls to the CreateUser method.
		CreateUser []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Cu is the cu argument value.
			Cu pguser.CreateUser
		}
		// SoftDeleteUser holds details about calls to the SoftDeleteUser method.
		SoftDeleteUser []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
		}
		// UpdateUser holds details about calls to the UpdateUser method.
		UpdateUser []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Uu is the uu argument value.
			Uu pguser.UpdateUser
		}
		// UserByEmail holds details about calls to the UserByEmail method.
		UserByEmail []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Email is the email argument value.
			Email string
		}
		// UserByExternalID holds details about calls to the UserByExternalID method.
		UserByExternalID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
		}
		// Users holds details about calls to the Users method.
		Users []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Filter is the filter argument value.
			Filter pguser.Filter
			// OrderBys is the orderBys argument value.
			OrderBys []order.By[pguser.OrderByField]
			// PageSize is the pageSize argument value.
			PageSize int
			// PageOffset is the pageOffset argument value.
			PageOffset int
		}
	}
	lockCreateUser       sync.RWMutex
	lockSoftDeleteUser   sync.RWMutex
	lockUpdateUser       sync.RWMutex
	lockUserByEmail      sync.RWMutex
	lockUserByExternalID sync.RWMutex
	lockUsers            sync.RWMutex
}

// CreateUser calls CreateUserFunc.
func (mock *MockedUserStorer) CreateUser(ctx context.Context, cu pguser.CreateUser) (pguser.User, error) {
	if mock.CreateUserFunc == nil {
		panic("MockedUserStorer.CreateUserFunc: method is nil but UserStorer.CreateUser was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Cu  pguser.CreateUser
	}{
		Ctx: ctx,
		Cu:  cu,
	}
	mock.lockCreateUser.Lock()
	mock.calls.CreateUser = append(mock.calls.CreateUser, callInfo)
	mock.lockCreateUser.Unlock()
	return mock.CreateUserFunc(ctx, cu)
}

// CreateUserCalls gets all the calls that were made to CreateUser.
// Check the length with:
//
//	len(mockedUserStorer.CreateUserCalls())
func (mock *MockedUserStorer) CreateUserCalls() []struct {
	Ctx context.Context
	Cu  pguser.CreateUser
} {
	var calls []struct {
		Ctx context.Context
		Cu  pguser.CreateUser
	}
	mock.lockCreateUser.RLock()
	calls = mock.calls.CreateUser
	mock.lockCreateUser.RUnlock()
	return calls
}

// SoftDeleteUser calls SoftDeleteUserFunc.
func (mock *MockedUserStorer) SoftDeleteUser(ctx context.Context, id uuid.UUID) error {
	if mock.SoftDeleteUserFunc == nil {
		panic("MockedUserStorer.SoftDeleteUserFunc: method is nil but UserStorer.SoftDeleteUser was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  uuid.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockSoftDeleteUser.Lock()
	mock.calls.SoftDeleteUser = append(mock.calls.SoftDeleteUser, callInfo)
	mock.lockSoftDeleteUser.Unlock()
	return mock.SoftDeleteUserFunc(ctx, id)
}

// SoftDeleteUserCalls gets all the calls that were made to SoftDeleteUser.
// Check the length with:
//
//	len(mockedUserStorer.SoftDeleteUserCalls())
func (mock *MockedUserStorer) SoftDeleteUserCalls() []struct {
	Ctx context.Context
	ID  uuid.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  uuid.UUID
	}
	mock.lockSoftDeleteUser.RLock()
	calls = mock.calls.SoftDeleteUser
	mock.lockSoftDeleteUser.RUnlock()
	return calls
}

// UpdateUser calls UpdateUserFunc.
func (mock *MockedUserStorer) UpdateUser(ctx context.Context, uu pguser.UpdateUser) (pguser.User, error) {
	if mock.UpdateUserFunc == nil {
		panic("MockedUserStorer.UpdateUserFunc: method is nil but UserStorer.UpdateUser was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Uu  pguser.UpdateUser
	}{
		Ctx: ctx,
		Uu:  uu,
	}
	mock.lockUpdateUser.Lock()
	mock.calls.UpdateUser = append(mock.calls.UpdateUser, callInfo)
	mock.lockUpdateUser.Unlock()
	return mock.UpdateUserFunc(ctx, uu)
}

// UpdateUserCalls gets all the calls that were made to UpdateUser.
// Check the length with:
//
//	len(mockedUserStorer.UpdateUserCalls())
func (mock *MockedUserStorer) UpdateUserCalls() []struct {
	Ctx context.Context
	Uu  pguser.UpdateUser
} {
	var calls []struct {
		Ctx context.Context
		Uu  pguser.UpdateUser
	}
	mock.lockUpdateUser.RLock()
	calls = mock.calls.UpdateUser
	mock.lockUpdateUser.RUnlock()
	return calls
}

// UserByEmail calls UserByEmailFunc.
func (mock *MockedUserStorer) UserByEmail(ctx context.Context, email string) (pguser.User, error) {
	if mock.UserByEmailFunc == nil {
		panic("MockedUserStorer.UserByEmailFunc: method is nil but UserStorer.UserByEmail was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Email string
	}{
		Ctx:   ctx,
		Email: email,
	}
	mock.lockUserByEmail.Lock()
	mock.calls.UserByEmail = append(mock.calls.UserByEmail, callInfo)
	mock.lockUserByEmail.Unlock()
	return mock.UserByEmailFunc(ctx, email)
}

// UserByEmailCalls gets all the calls that were made to UserByEmail.
// Check the length with:
//
//	len(mockedUserStorer.UserByEmailCalls())
func (mock *MockedUserStorer) UserByEmailCalls() []struct {
	Ctx   context.Context
	Email string
} {
	var calls []struct {
		Ctx   context.Context
		Email string
	}
	mock.lockUserByEmail.RLock()
	calls = mock.calls.UserByEmail
	mock.lockUserByEmail.RUnlock()
	return calls
}

// UserByExternalID calls UserByExternalIDFunc.
func (mock *MockedUserStorer) UserByExternalID(ctx context.Context, id uuid.UUID) (pguser.User, error) {
	if mock.UserByExternalIDFunc == nil {
		panic("MockedUserStorer.UserByExternalIDFunc: method is nil but UserStorer.UserByExternalID was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  uuid.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockUserByExternalID.Lock()
	mock.calls.UserByExternalID = append(mock.calls.UserByExternalID, callInfo)
	mock.lockUserByExternalID.Unlock()
	return mock.UserByExternalIDFunc(ctx, id)
}

// UserByExternalIDCalls gets all the calls that were made to UserByExternalID.
// Check the length with:
//
//	len(mockedUserStorer.UserByExternalIDCalls())
func (mock *MockedUserStorer) UserByExternalIDCalls() []struct {
	Ctx context.Context
	ID  uuid.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  uuid.UUID
	}
	mock.lockUserByExternalID.RLock()
	calls = mock.calls.UserByExternalID
	mock.lockUserByExternalID.RUnlock()
	return calls
}

// Users calls UsersFunc.
func (mock *MockedUserStorer) Users(ctx context.Context, filter pguser.Filter, orderBys []order.By[pguser.OrderByField], pageSize int, pageOffset int) ([]pguser.User, int, error) {
	if mock.UsersFunc == nil {
		panic("MockedUserStorer.UsersFunc: method is nil but UserStorer.Users was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		Filter     pguser.Filter
		OrderBys   []order.By[pguser.OrderByField]
		PageSize   int
		PageOffset int
	}{
		Ctx:        ctx,
		Filter:     filter,
		OrderBys:   orderBys,
		PageSize:   pageSize,
		PageOffset: pageOffset,
	}
	mock.lockUsers.Lock()
	mock.calls.Users = append(mock.calls.Users, callInfo)
	mock.lockUsers.Unlock()
	return mock.UsersFunc(ctx, filter, orderBys, pageSize, pageOffset)
}

// UsersCalls gets all the calls that were made to Users.
// Check the length with:
//
//	len(mockedUserStorer.UsersCalls())
func (mock *MockedUserStorer) UsersCalls() []struct {
	Ctx        context.Context
	Filter     pguser.Filter
	OrderBys   []order.By[pguser.OrderByField]
	PageSize   int
	PageOffset int
} {
	var calls []struct {
		Ctx        context.Context
		Filter     pguser.Filter
		OrderBys   []order.By[pguser.OrderByField]
		PageSize   int
		PageOffset int
	}
	mock.lockUsers.RLock()
	calls = mock.calls.Users
	mock.lockUsers.RUnlock()
	return calls
}

// Ensure, that MockedRBACStorer does implement RBACStorer.
// If this is not the case, regenerate this file with moq.
var _ RBACStorer = &MockedRBACStorer{}

// MockedRBACStorer is a mock implementation of RBACStorer.
//
//	func TestSomethingThatUsesRBACStorer(t *testing.T) {
//
//		// make and configure a mocked RBACStorer
//		mockedRBACStorer := &MockedRBACStorer{
//			FullyPrivilegedUserRemainsAfterDeleteFunc: func(ctx context.Context, id uuid.UUID) (bool, error) {
//				panic("mock out the FullyPrivilegedUserRemainsAfterDelete method")
//			},
//			LockSystemRoleManagementFunc: func(ctx context.Context) error {
//				panic("mock out the LockSystemRoleManagement method")
//			},
//		}
//
//		// use mockedRBACStorer in code that requires RBACStorer
//		// and then make assertions.
//
//	}
type MockedRBACStorer struct {
	// FullyPrivilegedUserRemainsAfterDeleteFunc mocks the FullyPrivilegedUserRemainsAfterDelete method.
	FullyPrivilegedUserRemainsAfterDeleteFunc func(ctx context.Context, id uuid.UUID) (bool, error)

	// LockSystemRoleManagementFunc mocks the LockSystemRoleManagement method.
	LockSystemRoleManagementFunc func(ctx context.Context) error

	// calls tracks calls to the methods.
	calls struct {
		// FullyPrivilegedUserRemainsAfterDelete holds details about calls to the FullyPrivilegedUserRemainsAfterDelete method.
		FullyPrivilegedUserRemainsAfterDelete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
		}
		// LockSystemRoleManagement holds details about calls to the LockSystemRoleManagement method.
		LockSystemRoleManagement []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockFullyPrivilegedUserRemainsAfterDelete sync.RWMutex
	lockLockSystemRoleManagement              sync.RWMutex
}

// FullyPrivilegedUserRemainsAfterDelete calls FullyPrivilegedUserRemainsAfterDeleteFunc.
func (mock *MockedRBACStorer) FullyPrivilegedUserRemainsAfterDelete(ctx context.Context, id uuid.UUID) (bool, error) {
	if mock.FullyPrivilegedUserRemainsAfterDeleteFunc == nil {
		panic("MockedRBACStorer.FullyPrivilegedUserRemainsAfterDeleteFunc: method is nil but RBACStorer.FullyPrivilegedUserRemainsAfterDelete was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  uuid.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockFullyPrivilegedUserRemainsAfterDelete.Lock()
	mock.calls.FullyPrivilegedUserRemainsAfterDelete = append(mock.calls.FullyPrivilegedUserRemainsAfterDelete, callInfo)
	mock.lockFullyPrivilegedUserRemainsAfterDelete.Unlock()
	return mock.FullyPrivilegedUserRemainsAfterDeleteFunc(ctx, id)
}

// FullyPrivilegedUserRemainsAfterDeleteCalls gets all the calls that were made to FullyPrivilegedUserRemainsAfterDelete.
// Check the length with:
//
//	len(mockedRBACStorer.FullyPrivilegedUserRemainsAfterDeleteCalls())
func (mock *MockedRBACStorer) FullyPrivilegedUserRemainsAfterDeleteCalls() []struct {
	Ctx context.Context
	ID  uuid.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  uuid.UUID
	}
	mock.lockFullyPrivilegedUserRemainsAfterDelete.RLock()
	calls = mock.calls.FullyPrivilegedUserRemainsAfterDelete
	mock.lockFullyPrivilegedUserRemainsAfterDelete.RUnlock()
	return calls
}

// LockSystemRoleManagement calls LockSystemRoleManagementFunc.
func (mock *MockedRBACStorer) LockSystemRoleManagement(ctx context.Context) error {
	if mock.LockSystemRoleManagementFunc == nil {
		panic("MockedRBACStorer.LockSystemRoleManagementFunc: method is nil but RBACStorer.LockSystemRoleManagement was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockLockSystemRoleManagement.Lock()
	mock.calls.LockSystemRoleManagement = append(mock.calls.LockSystemRoleManagement, callInfo)
	mock.lockLockSystemRoleManagement.Unlock()
	return mock.LockSystemRoleManagementFunc(ctx)
}

// LockSystemRoleManagementCalls gets all the calls that were made to LockSystemRoleManagement.
// Check the length with:
//
//	len(mockedRBACStorer.LockSystemRoleManagementCalls())
func (mock *MockedRBACStorer) LockSystemRoleManagementCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockLockSystemRoleManagement.RLock()
	calls = mock.calls.LockSystemRoleManagement
	mock.lockLockSystemRoleManagement.RUnlock()
	return calls
}
