// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: auth.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message for RequestMagicLink.
type RequestMagicLinkRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Email address to send the sign-in link to.
	Email         string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestMagicLinkRequest) Reset() {
	*x = RequestMagicLinkRequest{}
	mi := &file_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestMagicLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestMagicLinkRequest) ProtoMessage() {}

func (x *RequestMagicLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestMagicLinkRequest.ProtoReflect.Descriptor instead.
func (*RequestMagicLinkRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{0}
}

func (x *RequestMagicLinkRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

// Request message for VerifyMagicLink.
type VerifyMagicLinkRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The token from the magic-link URL query parameter.
	Token         string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyMagicLinkRequest) Reset() {
	*x = VerifyMagicLinkRequest{}
	mi := &file_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyMagicLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyMagicLinkRequest) ProtoMessage() {}

func (x *VerifyMagicLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyMagicLinkRequest.ProtoReflect.Descriptor instead.
func (*VerifyMagicLinkRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{1}
}

func (x *VerifyMagicLinkRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// Request message for RefreshAccessToken.
type RefreshAccessTokenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The refresh token issued by a previous VerifyMagicLink or RefreshAccessToken call.
	RefreshToken  string `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshAccessTokenRequest) Reset() {
	*x = RefreshAccessTokenRequest{}
	mi := &file_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshAccessTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshAccessTokenRequest) ProtoMessage() {}

func (x *RefreshAccessTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshAccessTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshAccessTokenRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{2}
}

func (x *RefreshAccessTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

// Request message for RevokeRefreshToken.
type RevokeRefreshTokenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The refresh token to revoke.
	RefreshToken  string `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeRefreshTokenRequest) Reset() {
	*x = RevokeRefreshTokenRequest{}
	mi := &file_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeRefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeRefreshTokenRequest) ProtoMessage() {}

func (x *RevokeRefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeRefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RevokeRefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{3}
}

func (x *RevokeRefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

// TokenPair holds a short-lived JWT access token and a long-lived refresh token.
type TokenPair struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JWT bearer token. Include as: Authorization: Bearer <access_token>.
	AccessToken string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	// Opaque refresh token. Use with RefreshAccessToken to obtain a new pair.
	RefreshToken string `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	// Remaining lifetime of access_token in seconds.
	ExpiresIn     int64 `protobuf:"varint,3,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenPair) Reset() {
	*x = TokenPair{}
	mi := &file_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenPair) ProtoMessage() {}

func (x *TokenPair) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenPair.ProtoReflect.Descriptor instead.
func (*TokenPair) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{4}
}

func (x *TokenPair) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *TokenPair) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *TokenPair) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

var File_auth_proto protoreflect.FileDescriptor

const file_auth_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"auth.proto\x12\ttheapp.v1\x1a\x1bgoogle/protobuf/empty.proto\"/\n" +
	"\x17RequestMagicLinkRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\".\n" +
	"\x16VerifyMagicLinkRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"@\n" +
	"\x19RefreshAccessTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"@\n" +
	"\x19RevokeRefreshTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"r\n" +
	"\tTokenPair\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x03 \x01(\x03R\texpiresIn2\xcf\x02\n" +
	"\vAuthService\x12N\n" +
	"\x10RequestMagicLink\x12\".theapp.v1.RequestMagicLinkRequest\x1a\x16.google.protobuf.Empty\x12J\n" +
	"\x0fVerifyMagicLink\x12!.theapp.v1.VerifyMagicLinkRequest\x1a\x14.theapp.v1.TokenPair\x12P\n" +
	"\x12RefreshAccessToken\x12$.theapp.v1.RefreshAccessTokenRequest\x1a\x14.theapp.v1.TokenPair\x12R\n" +
	"\x12RevokeRefreshToken\x12$.theapp.v1.RevokeRefreshTokenRequest\x1a\x16.google.protobuf.EmptyB\xa2\x01\n" +
	"\rcom.theapp.v1B\tAuthProtoP\x01ZAgithub.com/zorcal/theapp/backend/internal/api/grpc/internal/pb;pb\xa2\x02\x03TXX\xaa\x02\tTheapp.V1\xca\x02\tTheapp\\V1\xe2\x02\x15Theapp\\V1\\GPBMetadata\xea\x02\n" +
	"Theapp::V1b\x06proto3"

var (
	file_auth_proto_rawDescOnce sync.Once
	file_auth_proto_rawDescData []byte
)

func file_auth_proto_rawDescGZIP() []byte {
	file_auth_proto_rawDescOnce.Do(func() {
		file_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)))
	})
	return file_auth_proto_rawDescData
}

var file_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_auth_proto_goTypes = []any{
	(*RequestMagicLinkRequest)(nil),   // 0: theapp.v1.RequestMagicLinkRequest
	(*VerifyMagicLinkRequest)(nil),    // 1: theapp.v1.VerifyMagicLinkRequest
	(*RefreshAccessTokenRequest)(nil), // 2: theapp.v1.RefreshAccessTokenRequest
	(*RevokeRefreshTokenRequest)(nil), // 3: theapp.v1.RevokeRefreshTokenRequest
	(*TokenPair)(nil),                 // 4: theapp.v1.TokenPair
	(*emptypb.Empty)(nil),             // 5: google.protobuf.Empty
}
var file_auth_proto_depIdxs = []int32{
	0, // 0: theapp.v1.AuthService.RequestMagicLink:input_type -> theapp.v1.RequestMagicLinkRequest
	1, // 1: theapp.v1.AuthService.VerifyMagicLink:input_type -> theapp.v1.VerifyMagicLinkRequest
	2, // 2: theapp.v1.AuthService.RefreshAccessToken:input_type -> theapp.v1.RefreshAccessTokenRequest
	3, // 3: theapp.v1.AuthService.RevokeRefreshToken:input_type -> theapp.v1.RevokeRefreshTokenRequest
	5, // 4: theapp.v1.AuthService.RequestMagicLink:output_type -> google.protobuf.Empty
	4, // 5: theapp.v1.AuthService.VerifyMagicLink:output_type -> theapp.v1.TokenPair
	4, // 6: theapp.v1.AuthService.RefreshAccessToken:output_type -> theapp.v1.TokenPair
	5, // 7: theapp.v1.AuthService.RevokeRefreshToken:output_type -> google.protobuf.Empty
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_auth_proto_init() }
func file_auth_proto_init() {
	if File_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_proto_goTypes,
		DependencyIndexes: file_auth_proto_depIdxs,
		MessageInfos:      file_auth_proto_msgTypes,
	}.Build()
	File_auth_proto = out.File
	file_auth_proto_goTypes = nil
	file_auth_proto_depIdxs = nil
}
