// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: error.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A stable, machine-readable reason for an application-level failure.
//
// The gRPC status code remains the broad failure category. ErrorDetail is attached only when
// clients may need to distinguish this condition from other failures with the same status.
type ErrorCode int32

const (
	ErrorCode_ERROR_CODE_UNSPECIFIED                        ErrorCode = 0
	ErrorCode_ERROR_CODE_ETAG_MISMATCH                      ErrorCode = 1
	ErrorCode_ERROR_CODE_MANAGED_ROLE                       ErrorCode = 2
	ErrorCode_ERROR_CODE_INVALID_ROLE_ASSIGNMENT_SCOPE      ErrorCode = 3
	ErrorCode_ERROR_CODE_LAST_FULLY_PRIVILEGED_SYSTEM_ADMIN ErrorCode = 4
	ErrorCode_ERROR_CODE_CONTROL_PROJECT_NAME_CONFLICT      ErrorCode = 5
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "ERROR_CODE_UNSPECIFIED",
		1: "ERROR_CODE_ETAG_MISMATCH",
		2: "ERROR_CODE_MANAGED_ROLE",
		3: "ERROR_CODE_INVALID_ROLE_ASSIGNMENT_SCOPE",
		4: "ERROR_CODE_LAST_FULLY_PRIVILEGED_SYSTEM_ADMIN",
		5: "ERROR_CODE_CONTROL_PROJECT_NAME_CONFLICT",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_UNSPECIFIED":                        0,
		"ERROR_CODE_ETAG_MISMATCH":                      1,
		"ERROR_CODE_MANAGED_ROLE":                       2,
		"ERROR_CODE_INVALID_ROLE_ASSIGNMENT_SCOPE":      3,
		"ERROR_CODE_LAST_FULLY_PRIVILEGED_SYSTEM_ADMIN": 4,
		"ERROR_CODE_CONTROL_PROJECT_NAME_CONFLICT":      5,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_error_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_error_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_error_proto_rawDescGZIP(), []int{0}
}

// Structured application-specific detail attached to google.rpc.Status.details.
type ErrorDetail struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Code  ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=theapp.v1.ErrorCode" json:"code,omitempty"`
	// Values relevant to this occurrence. Metadata keys are part of the API contract only when
	// documented for a particular error code.
	Metadata      map[string]string `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDetail) Reset() {
	*x = ErrorDetail{}
	mi := &file_error_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetail) ProtoMessage() {}

func (x *ErrorDetail) ProtoReflect() protoreflect.Message {
	mi := &file_error_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetail.ProtoReflect.Descriptor instead.
func (*ErrorDetail) Descriptor() ([]byte, []int) {
	return file_error_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorDetail) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

func (x *ErrorDetail) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_error_proto protoreflect.FileDescriptor

const file_error_proto_rawDesc = "" +
	"\n" +
	"\verror.proto\x12\ttheapp.v1\"\xb6\x01\n" +
	"\vErrorDetail\x12(\n" +
	"\x04code\x18\x01 \x01(\x0e2\x14.theapp.v1.ErrorCodeR\x04code\x12@\n" +
	"\bmetadata\x18\x02 \x03(\v2$.theapp.v1.ErrorDetail.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\xf1\x01\n" +
	"\tErrorCode\x12\x1a\n" +
	"\x16ERROR_CODE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18ERROR_CODE_ETAG_MISMATCH\x10\x01\x12\x1b\n" +
	"\x17ERROR_CODE_MANAGED_ROLE\x10\x02\x12,\n" +
	"(ERROR_CODE_INVALID_ROLE_ASSIGNMENT_SCOPE\x10\x03\x121\n" +
	"-ERROR_CODE_LAST_FULLY_PRIVILEGED_SYSTEM_ADMIN\x10\x04\x12,\n" +
	"(ERROR_CODE_CONTROL_PROJECT_NAME_CONFLICT\x10\x05B\xa3\x01\n" +
	"\rcom.theapp.v1B\n" +
	"ErrorProtoP\x01ZAgithub.com/zorcal/theapp/backend/internal/api/grpc/internal/pb;pb\xa2\x02\x03TXX\xaa\x02\tTheapp.V1\xca\x02\tTheapp\\V1\xe2\x02\x15Theapp\\V1\\GPBMetadata\xea\x02\n" +
	"Theapp::V1b\x06proto3"

var (
	file_error_proto_rawDescOnce sync.Once
	file_error_proto_rawDescData []byte
)

func file_error_proto_rawDescGZIP() []byte {
	file_error_proto_rawDescOnce.Do(func() {
		file_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_error_proto_rawDesc), len(file_error_proto_rawDesc)))
	})
	return file_error_proto_rawDescData
}

var file_error_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_error_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_error_proto_goTypes = []any{
	(ErrorCode)(0),      // 0: theapp.v1.ErrorCode
	(*ErrorDetail)(nil), // 1: theapp.v1.ErrorDetail
	nil,                 // 2: theapp.v1.ErrorDetail.MetadataEntry
}
var file_error_proto_depIdxs = []int32{
	0, // 0: theapp.v1.ErrorDetail.code:type_name -> theapp.v1.ErrorCode
	2, // 1: theapp.v1.ErrorDetail.metadata:type_name -> theapp.v1.ErrorDetail.MetadataEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_error_proto_init() }
func file_error_proto_init() {
	if File_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_error_proto_rawDesc), len(file_error_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_error_proto_goTypes,
		DependencyIndexes: file_error_proto_depIdxs,
		EnumInfos:         file_error_proto_enumTypes,
		MessageInfos:      file_error_proto_msgTypes,
	}.Build()
	File_error_proto = out.File
	file_error_proto_goTypes = nil
	file_error_proto_depIdxs = nil
}
