// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: organization.proto

package pb

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	_ "google.golang.org/genproto/googleapis/rpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Organization represents a tenant.
type Organization struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the organization.
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Display name of the organization.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Unique identifier for the project anchoring organization-level administration.
	ControlProjectId int32 `protobuf:"varint,3,opt,name=control_project_id,json=controlProjectId,proto3" json:"control_project_id,omitempty"`
	// Timestamp when the organization was created.
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// Timestamp when the organization was last updated.
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Organization) Reset() {
	*x = Organization{}
	mi := &file_organization_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Organization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Organization) ProtoMessage() {}

func (x *Organization) ProtoReflect() protoreflect.Message {
	mi := &file_organization_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Organization.ProtoReflect.Descriptor instead.
func (*Organization) Descriptor() ([]byte, []int) {
	return file_organization_proto_rawDescGZIP(), []int{0}
}

func (x *Organization) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Organization) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Organization) GetControlProjectId() int32 {
	if x != nil {
		return x.ControlProjectId
	}
	return 0
}

func (x *Organization) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Organization) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

// Request message for creating an organization.
type CreateOrganizationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Organization to create. Only name is accepted as input.
	Organization *Organization `protobuf:"bytes,1,opt,name=organization,proto3" json:"organization,omitempty"`
	// Display name for the organization's initial non-control project.
	ProjectName   string `protobuf:"bytes,2,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrganizationRequest) Reset() {
	*x = CreateOrganizationRequest{}
	mi := &file_organization_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrganizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrganizationRequest) ProtoMessage() {}

func (x *CreateOrganizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_organization_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrganizationRequest.ProtoReflect.Descriptor instead.
func (*CreateOrganizationRequest) Descriptor() ([]byte, []int) {
	return file_organization_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOrganizationRequest) GetOrganization() *Organization {
	if x != nil {
		return x.Organization
	}
	return nil
}

func (x *CreateOrganizationRequest) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

// Request message for creating or assigning an organization user.
type CreateOrganizationUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Email address identifying the system user.
	Email         string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrganizationUserRequest) Reset() {
	*x = CreateOrganizationUserRequest{}
	mi := &file_organization_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrganizationUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrganizationUserRequest) ProtoMessage() {}

func (x *CreateOrganizationUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_organization_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrganizationUserRequest.ProtoReflect.Descriptor instead.
func (*CreateOrganizationUserRequest) Descriptor() ([]byte, []int) {
	return file_organization_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOrganizationUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type OrganizationUserFilter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Restrict results to organization members with effective access to this project.
	ProjectId     int32 `protobuf:"varint,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrganizationUserFilter) Reset() {
	*x = OrganizationUserFilter{}
	mi := &file_organization_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrganizationUserFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrganizationUserFilter) ProtoMessage() {}

func (x *OrganizationUserFilter) ProtoReflect() protoreflect.Message {
	mi := &file_organization_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrganizationUserFilter.ProtoReflect.Descriptor instead.
func (*OrganizationUserFilter) Descriptor() ([]byte, []int) {
	return file_organization_proto_rawDescGZIP(), []int{3}
}

func (x *OrganizationUserFilter) GetProjectId() int32 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

type ListOrganizationUsersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum number of users to return. Defaults to 50 and is capped at 100.
	PageSize int32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Opaque token returned by the previous page.
	PageToken string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Optional criteria restricting the users returned.
	Filter        *OrganizationUserFilter `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrganizationUsersRequest) Reset() {
	*x = ListOrganizationUsersRequest{}
	mi := &file_organization_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrganizationUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrganizationUsersRequest) ProtoMessage() {}

func (x *ListOrganizationUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_organization_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrganizationUsersRequest.ProtoReflect.Descriptor instead.
func (*ListOrganizationUsersRequest) Descriptor() ([]byte, []int) {
	return file_organization_proto_rawDescGZIP(), []int{4}
}

func (x *ListOrganizationUsersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListOrganizationUsersRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListOrganizationUsersRequest) GetFilter() *OrganizationUserFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type ListOrganizationUsersResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Organization users in email order.
	Users []*User `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	// Total number of users matching the filter, independent of pagination.
	TotalSize int32 `protobuf:"varint,2,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	// Opaque token for the next page, or empty when this is the final page.
	NextPageToken string `protobuf:"bytes,3,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrganizationUsersResponse) Reset() {
	*x = ListOrganizationUsersResponse{}
	mi := &file_organization_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrganizationUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrganizationUsersResponse) ProtoMessage() {}

func (x *ListOrganizationUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_organization_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrganizationUsersResponse.ProtoReflect.Descriptor instead.
func (*ListOrganizationUsersResponse) Descriptor() ([]byte, []int) {
	return file_organization_proto_rawDescGZIP(), []int{5}
}

func (x *ListOrganizationUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ListOrganizationUsersResponse) GetTotalSize() int32 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *ListOrganizationUsersResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_organization_proto protoreflect.FileDescriptor

const file_organization_proto_rawDesc = "" +
	"\n" +
	"\x12organization.proto\x12\ttheapp.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17google/rpc/status.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\n" +
	"user.proto\"\xee\x01\n" +
	"\fOrganization\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x05B\x03\xe0A\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x121\n" +
	"\x12control_project_id\x18\x03 \x01(\x05B\x03\xe0A\x03R\x10controlProjectId\x12@\n" +
	"\vcreate_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"createTime\x12@\n" +
	"\vupdate_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"updateTime\"\x85\x01\n" +
	"\x19CreateOrganizationRequest\x12@\n" +
	"\forganization\x18\x01 \x01(\v2\x17.theapp.v1.OrganizationB\x03\xe0A\x02R\forganization\x12&\n" +
	"\fproject_name\x18\x02 \x01(\tB\x03\xe0A\x02R\vprojectName\":\n" +
	"\x1dCreateOrganizationUserRequest\x12\x19\n" +
	"\x05email\x18\x01 \x01(\tB\x03\xe0A\x02R\x05email\"7\n" +
	"\x16OrganizationUserFilter\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\x05R\tprojectId\"\x95\x01\n" +
	"\x1cListOrganizationUsersRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x129\n" +
	"\x06filter\x18\x03 \x01(\v2!.theapp.v1.OrganizationUserFilterR\x06filter\"\x8d\x01\n" +
	"\x1dListOrganizationUsersResponse\x12%\n" +
	"\x05users\x18\x01 \x03(\v2\x0f.theapp.v1.UserR\x05users\x12\x1d\n" +
	"\n" +
	"total_size\x18\x02 \x01(\x05R\ttotalSize\x12&\n" +
	"\x0fnext_page_token\x18\x03 \x01(\tR\rnextPageToken2\xe0\x0f\n" +
	"\n" +
	"OrgService\x12\xb6\x06\n" +
	"\x12CreateOrganization\x12$.theapp.v1.CreateOrganizationRequest\x1a\x17.theapp.v1.Organization\"\xe0\x05\x92A\xc0\x05J\x81\x02\n" +
	"\x03400\x12\xf9\x01\n" +
	"\xde\x01gRPC INVALID_ARGUMENT. A default project name that conflicts with the control project includes ErrorDetail.code ERROR_CODE_CONTROL_PROJECT_NAME_CONFLICT; ordinary validation errors do not include an application error code.\x12\x16\n" +
	"\x14\x1a\x12.google.rpc.StatusJ@\n" +
	"\x03401\x129\n" +
	"\x1fMissing or invalid credentials.\x12\x16\n" +
	"\x14\x1a\x12.google.rpc.StatusJn\n" +
	"\x03403\x12g\n" +
	"MOrganization creation authority or system-organization membership is missing.\x12\x16\n" +
	"\x14\x1a\x12.google.rpc.StatusJA\n" +
	"\x03404\x12:\n" +
	" Authenticated creator not found.\x12\x16\n" +
	"\x14\x1a\x12.google.rpc.StatusJB\n" +
	"\x03409\x12;\n" +
	"!Organization name already exists.\x12\x16\n" +
	"\x14\x1a\x12.google.rpc.StatusJ9\n" +
	"\x03500\x122\n" +
	"\x18Unexpected server error.\x12\x16\n" +
	"\x14\x1a\x12.google.rpc.StatusrF\n" +
	"D\n" +
	"\fx-project-id\x120ID of the system organization's control project.\x18\x03(\x01\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/organizations\x12\x91\x04\n" +
	"\x16CreateOrganizationUser\x12(.theapp.v1.CreateOrganizationUserRequest\x1a\x0f.theapp.v1.User\"\xbb\x03\x92A\x95\x03JC\n" +
	"\x03400\x12<\n" +
	"\"Invalid email or project metadata.\x12\x16\n" +
	"\x14\x1a\x12.google.rpc.StatusJ@\n" +
	"\x03401\x129\n" +
	"\x1fMissing or invalid credentials.\x12\x16\n" +
	"\x14\x1a\x12.google.rpc.StatusJ\x91\x01\n" +
	"\x03403\x12\x89\x01\n" +
	"oOrganization-user creation access is missing or the selected project is not the organization's control project.\x12\x16\n" +
	"\x14\x1a\x12.google.rpc.StatusJ9\n" +
	"\x03500\x122\n" +
	"\x18Unexpected server error.\x12\x16\n" +
	"\x14\x1a\x12.google.rpc.Statusr=\n" +
	";\n" +
	"\fx-project-id\x12'ID of the organization control project.\x18\x03(\x01\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/v1/organizations/users\x12\x84\x05\n" +
	"\x15ListOrganizationUsers\x12'.theapp.v1.ListOrganizationUsersRequest\x1a(.theapp.v1.ListOrganizationUsersResponse\"\x97\x04\x92A\xf4\x03JT\n" +
	"\x03400\x12M\n" +
	"3Invalid pagination, filtering, or project metadata.\x12\x16\n" +
	"\x14\x1a\x12.google.rpc.StatusJ@\n" +
	"\x03401\x129\n" +
	"\x1fMissing or invalid credentials.\x12\x16\n" +
	"\x14\x1a\x12.google.rpc.StatusJ\x8d\x01\n" +
	"\x03403\x12\x85\x01\n" +
	"kOrganization-user read access is missing or the selected project is not the organization's control project.\x12\x16\n" +
	"\x14\x1a\x12.google.rpc.StatusJP\n" +
	"\x03404\x12I\n" +
	"/Filtered project not found in the organization.\x12\x16\n" +
	"\x14\x1a\x12.google.rpc.StatusJ9\n" +
	"\x03500\x122\n" +
	"\x18Unexpected server error.\x12\x16\n" +
	"\x14\x1a\x12.google.rpc.Statusr=\n" +
	";\n" +
	"\fx-project-id\x12'ID of the organization control project.\x18\x03(\x01\x82\xd3\xe4\x93\x02\x19\x12\x17/v1/organizations/usersB\xd7\x02\x92A\xa9\x01\x12\x1d\n" +
	"\x17theapp Organization API2\x02v1Zv\n" +
	"t\n" +
	"\n" +
	"BearerAuth\x12f\b\x02\x12QAccess token from VerifyMagicLink or RefreshAccessToken. Format: 'Bearer {token}'\x1a\rAuthorization \x02b\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\n" +
	"\rcom.theapp.v1B\x11OrganizationProtoP\x01ZAgithub.com/zorcal/theapp/backend/internal/api/grpc/internal/pb;pb\xa2\x02\x03TXX\xaa\x02\tTheapp.V1\xca\x02\tTheapp\\V1\xe2\x02\x15Theapp\\V1\\GPBMetadata\xea\x02\n" +
	"Theapp::V1b\x06proto3"

var (
	file_organization_proto_rawDescOnce sync.Once
	file_organization_proto_rawDescData []byte
)

func file_organization_proto_rawDescGZIP() []byte {
	file_organization_proto_rawDescOnce.Do(func() {
		file_organization_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_organization_proto_rawDesc), len(file_organization_proto_rawDesc)))
	})
	return file_organization_proto_rawDescData
}

var file_organization_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_organization_proto_goTypes = []any{
	(*Organization)(nil),                  // 0: theapp.v1.Organization
	(*CreateOrganizationRequest)(nil),     // 1: theapp.v1.CreateOrganizationRequest
	(*CreateOrganizationUserRequest)(nil), // 2: theapp.v1.CreateOrganizationUserRequest
	(*OrganizationUserFilter)(nil),        // 3: theapp.v1.OrganizationUserFilter
	(*ListOrganizationUsersRequest)(nil),  // 4: theapp.v1.ListOrganizationUsersRequest
	(*ListOrganizationUsersResponse)(nil), // 5: theapp.v1.ListOrganizationUsersResponse
	(*timestamppb.Timestamp)(nil),         // 6: google.protobuf.Timestamp
	(*User)(nil),                          // 7: theapp.v1.User
}
var file_organization_proto_depIdxs = []int32{
	6, // 0: theapp.v1.Organization.create_time:type_name -> google.protobuf.Timestamp
	6, // 1: theapp.v1.Organization.update_time:type_name -> google.protobuf.Timestamp
	0, // 2: theapp.v1.CreateOrganizationRequest.organization:type_name -> theapp.v1.Organization
	3, // 3: theapp.v1.ListOrganizationUsersRequest.filter:type_name -> theapp.v1.OrganizationUserFilter
	7, // 4: theapp.v1.ListOrganizationUsersResponse.users:type_name -> theapp.v1.User
	1, // 5: theapp.v1.OrgService.CreateOrganization:input_type -> theapp.v1.CreateOrganizationRequest
	2, // 6: theapp.v1.OrgService.CreateOrganizationUser:input_type -> theapp.v1.CreateOrganizationUserRequest
	4, // 7: theapp.v1.OrgService.ListOrganizationUsers:input_type -> theapp.v1.ListOrganizationUsersRequest
	0, // 8: theapp.v1.OrgService.CreateOrganization:output_type -> theapp.v1.Organization
	7, // 9: theapp.v1.OrgService.CreateOrganizationUser:output_type -> theapp.v1.User
	5, // 10: theapp.v1.OrgService.ListOrganizationUsers:output_type -> theapp.v1.ListOrganizationUsersResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_organization_proto_init() }
func file_organization_proto_init() {
	if File_organization_proto != nil {
		return
	}
	file_user_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_organization_proto_rawDesc), len(file_organization_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_organization_proto_goTypes,
		DependencyIndexes: file_organization_proto_depIdxs,
		MessageInfos:      file_organization_proto_msgTypes,
	}.Build()
	File_organization_proto = out.File
	file_organization_proto_goTypes = nil
	file_organization_proto_depIdxs = nil
}
