// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: permission.proto

package pb

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Permission is a capability that can be granted through a role.
type Permission int32

const (
	Permission_PERMISSION_UNSPECIFIED          Permission = 0
	Permission_PERMISSION_USER_READ            Permission = 1
	Permission_PERMISSION_USER_CREATE          Permission = 2
	Permission_PERMISSION_USER_UPDATE          Permission = 3
	Permission_PERMISSION_SYSTEM_ROLE_READ     Permission = 4
	Permission_PERMISSION_SYSTEM_ROLE_ASSIGN   Permission = 5
	Permission_PERMISSION_SYSTEM_ROLE_UNASSIGN Permission = 6
	Permission_PERMISSION_CUSTOM_ROLE_CREATE   Permission = 7
	Permission_PERMISSION_CUSTOM_ROLE_READ     Permission = 8
	Permission_PERMISSION_CUSTOM_ROLE_UPDATE   Permission = 9
	Permission_PERMISSION_CUSTOM_ROLE_DELETE   Permission = 10
)

// Enum value maps for Permission.
var (
	Permission_name = map[int32]string{
		0:  "PERMISSION_UNSPECIFIED",
		1:  "PERMISSION_USER_READ",
		2:  "PERMISSION_USER_CREATE",
		3:  "PERMISSION_USER_UPDATE",
		4:  "PERMISSION_SYSTEM_ROLE_READ",
		5:  "PERMISSION_SYSTEM_ROLE_ASSIGN",
		6:  "PERMISSION_SYSTEM_ROLE_UNASSIGN",
		7:  "PERMISSION_CUSTOM_ROLE_CREATE",
		8:  "PERMISSION_CUSTOM_ROLE_READ",
		9:  "PERMISSION_CUSTOM_ROLE_UPDATE",
		10: "PERMISSION_CUSTOM_ROLE_DELETE",
	}
	Permission_value = map[string]int32{
		"PERMISSION_UNSPECIFIED":          0,
		"PERMISSION_USER_READ":            1,
		"PERMISSION_USER_CREATE":          2,
		"PERMISSION_USER_UPDATE":          3,
		"PERMISSION_SYSTEM_ROLE_READ":     4,
		"PERMISSION_SYSTEM_ROLE_ASSIGN":   5,
		"PERMISSION_SYSTEM_ROLE_UNASSIGN": 6,
		"PERMISSION_CUSTOM_ROLE_CREATE":   7,
		"PERMISSION_CUSTOM_ROLE_READ":     8,
		"PERMISSION_CUSTOM_ROLE_UPDATE":   9,
		"PERMISSION_CUSTOM_ROLE_DELETE":   10,
	}
)

func (x Permission) Enum() *Permission {
	p := new(Permission)
	*p = x
	return p
}

func (x Permission) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Permission) Descriptor() protoreflect.EnumDescriptor {
	return file_permission_proto_enumTypes[0].Descriptor()
}

func (Permission) Type() protoreflect.EnumType {
	return &file_permission_proto_enumTypes[0]
}

func (x Permission) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Permission.Descriptor instead.
func (Permission) EnumDescriptor() ([]byte, []int) {
	return file_permission_proto_rawDescGZIP(), []int{0}
}

// Request message for listing custom-role-assignable permissions.
type ListPermissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPermissionsRequest) Reset() {
	*x = ListPermissionsRequest{}
	mi := &file_permission_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPermissionsRequest) ProtoMessage() {}

func (x *ListPermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_permission_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPermissionsRequest.ProtoReflect.Descriptor instead.
func (*ListPermissionsRequest) Descriptor() ([]byte, []int) {
	return file_permission_proto_rawDescGZIP(), []int{0}
}

// Response message for listing custom-role-assignable permissions.
type ListPermissionsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Permissions that may be granted through a custom role.
	Permissions   []Permission `protobuf:"varint,1,rep,packed,name=permissions,proto3,enum=theapp.v1.Permission" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPermissionsResponse) Reset() {
	*x = ListPermissionsResponse{}
	mi := &file_permission_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPermissionsResponse) ProtoMessage() {}

func (x *ListPermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_permission_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPermissionsResponse.ProtoReflect.Descriptor instead.
func (*ListPermissionsResponse) Descriptor() ([]byte, []int) {
	return file_permission_proto_rawDescGZIP(), []int{1}
}

func (x *ListPermissionsResponse) GetPermissions() []Permission {
	if x != nil {
		return x.Permissions
	}
	return nil
}

var File_permission_proto protoreflect.FileDescriptor

const file_permission_proto_rawDesc = "" +
	"\n" +
	"\x10permission.proto\x12\ttheapp.v1\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\x18\n" +
	"\x16ListPermissionsRequest\"R\n" +
	"\x17ListPermissionsResponse\x127\n" +
	"\vpermissions\x18\x01 \x03(\x0e2\x15.theapp.v1.PermissionR\vpermissions*\xed\x02\n" +
	"\n" +
	"Permission\x12\x1a\n" +
	"\x16PERMISSION_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14PERMISSION_USER_READ\x10\x01\x12\x1a\n" +
	"\x16PERMISSION_USER_CREATE\x10\x02\x12\x1a\n" +
	"\x16PERMISSION_USER_UPDATE\x10\x03\x12\x1f\n" +
	"\x1bPERMISSION_SYSTEM_ROLE_READ\x10\x04\x12!\n" +
	"\x1dPERMISSION_SYSTEM_ROLE_ASSIGN\x10\x05\x12#\n" +
	"\x1fPERMISSION_SYSTEM_ROLE_UNASSIGN\x10\x06\x12!\n" +
	"\x1dPERMISSION_CUSTOM_ROLE_CREATE\x10\a\x12\x1f\n" +
	"\x1bPERMISSION_CUSTOM_ROLE_READ\x10\b\x12!\n" +
	"\x1dPERMISSION_CUSTOM_ROLE_UPDATE\x10\t\x12!\n" +
	"\x1dPERMISSION_CUSTOM_ROLE_DELETE\x10\n" +
	"2\x86\x01\n" +
	"\x11PermissionService\x12q\n" +
	"\x0fListPermissions\x12!.theapp.v1.ListPermissionsRequest\x1a\".theapp.v1.ListPermissionsResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/permissionsB\xd3\x02\x92A\xa7\x01\x12\x1b\n" +
	"\x15theapp Permission API2\x02v1Zv\n" +
	"t\n" +
	"\n" +
	"BearerAuth\x12f\b\x02\x12QAccess token from VerifyMagicLink or RefreshAccessToken. Format: 'Bearer {token}'\x1a\rAuthorization \x02b\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\n" +
	"\rcom.theapp.v1B\x0fPermissionProtoP\x01ZAgithub.com/zorcal/theapp/backend/internal/api/grpc/internal/pb;pb\xa2\x02\x03TXX\xaa\x02\tTheapp.V1\xca\x02\tTheapp\\V1\xe2\x02\x15Theapp\\V1\\GPBMetadata\xea\x02\n" +
	"Theapp::V1b\x06proto3"

var (
	file_permission_proto_rawDescOnce sync.Once
	file_permission_proto_rawDescData []byte
)

func file_permission_proto_rawDescGZIP() []byte {
	file_permission_proto_rawDescOnce.Do(func() {
		file_permission_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_permission_proto_rawDesc), len(file_permission_proto_rawDesc)))
	})
	return file_permission_proto_rawDescData
}

var file_permission_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_permission_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_permission_proto_goTypes = []any{
	(Permission)(0),                 // 0: theapp.v1.Permission
	(*ListPermissionsRequest)(nil),  // 1: theapp.v1.ListPermissionsRequest
	(*ListPermissionsResponse)(nil), // 2: theapp.v1.ListPermissionsResponse
}
var file_permission_proto_depIdxs = []int32{
	0, // 0: theapp.v1.ListPermissionsResponse.permissions:type_name -> theapp.v1.Permission
	1, // 1: theapp.v1.PermissionService.ListPermissions:input_type -> theapp.v1.ListPermissionsRequest
	2, // 2: theapp.v1.PermissionService.ListPermissions:output_type -> theapp.v1.ListPermissionsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_permission_proto_init() }
func file_permission_proto_init() {
	if File_permission_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_permission_proto_rawDesc), len(file_permission_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_permission_proto_goTypes,
		DependencyIndexes: file_permission_proto_depIdxs,
		EnumInfos:         file_permission_proto_enumTypes,
		MessageInfos:      file_permission_proto_msgTypes,
	}.Build()
	File_permission_proto = out.File
	file_permission_proto_goTypes = nil
	file_permission_proto_depIdxs = nil
}
