// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: project.proto

package pb

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	_ "google.golang.org/genproto/googleapis/rpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Project represents a project within an organization.
type Project struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the project.
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Unique identifier for the organization that owns the project.
	OrganizationId int32 `protobuf:"varint,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	// Display name of the project.
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Whether the project anchors organization-level administrative operations.
	IsControl bool `protobuf:"varint,4,opt,name=is_control,json=isControl,proto3" json:"is_control,omitempty"`
	// Timestamp when the project was created.
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// Timestamp when the project was last updated.
	UpdateTime *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	// The ETag for the current version of the project. Helps to prevent
	// simultaneous updates of a project from overwriting each other ("mid-air
	// collisions").
	//
	// If this is provided on update, it must match the server's ETag.
	Etag          string `protobuf:"bytes,7,opt,name=etag,proto3" json:"etag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Project) Reset() {
	*x = Project{}
	mi := &file_project_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{0}
}

func (x *Project) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Project) GetOrganizationId() int32 {
	if x != nil {
		return x.OrganizationId
	}
	return 0
}

func (x *Project) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Project) GetIsControl() bool {
	if x != nil {
		return x.IsControl
	}
	return false
}

func (x *Project) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Project) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

func (x *Project) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

// Request message for listing accessible projects.
type ListProjectsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum number of projects to return.
	PageSize int32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Token for fetching the next page of results.
	PageToken string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Filter criteria. All fields are optional; omitted fields match all projects.
	Filter        *ProjectFilter `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectsRequest) Reset() {
	*x = ListProjectsRequest{}
	mi := &file_project_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsRequest) ProtoMessage() {}

func (x *ListProjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsRequest.ProtoReflect.Descriptor instead.
func (*ListProjectsRequest) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{1}
}

func (x *ListProjectsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListProjectsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListProjectsRequest) GetFilter() *ProjectFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

// Filter criteria for listing projects.
type ProjectFilter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Match projects whose name starts with this prefix.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectFilter) Reset() {
	*x = ProjectFilter{}
	mi := &file_project_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectFilter) ProtoMessage() {}

func (x *ProjectFilter) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectFilter.ProtoReflect.Descriptor instead.
func (*ProjectFilter) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{2}
}

func (x *ProjectFilter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Response message for listing accessible projects.
type ListProjectsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Projects accessible to the authenticated caller.
	Projects []*Project `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	// Total number of accessible projects.
	TotalSize int32 `protobuf:"varint,2,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	// Token for fetching the next page of results, if applicable.
	NextPageToken string `protobuf:"bytes,3,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectsResponse) Reset() {
	*x = ListProjectsResponse{}
	mi := &file_project_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsResponse) ProtoMessage() {}

func (x *ListProjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsResponse.ProtoReflect.Descriptor instead.
func (*ListProjectsResponse) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{3}
}

func (x *ListProjectsResponse) GetProjects() []*Project {
	if x != nil {
		return x.Projects
	}
	return nil
}

func (x *ListProjectsResponse) GetTotalSize() int32 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *ListProjectsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_project_proto protoreflect.FileDescriptor

const file_project_proto_rawDesc = "" +
	"\n" +
	"\rproject.proto\x12\ttheapp.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/api/field_info.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17google/rpc/status.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xa9\x02\n" +
	"\aProject\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x05B\x03\xe0A\x03R\x02id\x12,\n" +
	"\x0forganization_id\x18\x02 \x01(\x05B\x03\xe0A\x03R\x0eorganizationId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\"\n" +
	"\n" +
	"is_control\x18\x04 \x01(\bB\x03\xe0A\x03R\tisControl\x12@\n" +
	"\vcreate_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"createTime\x12@\n" +
	"\vupdate_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"updateTime\x12\x1f\n" +
	"\x04etag\x18\a \x01(\tB\v\xe0A\x03\xe2\x8c\xcf\xd7\b\x02\b\x01R\x04etag\"\x83\x01\n" +
	"\x13ListProjectsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x120\n" +
	"\x06filter\x18\x03 \x01(\v2\x18.theapp.v1.ProjectFilterR\x06filter\"#\n" +
	"\rProjectFilter\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x8d\x01\n" +
	"\x14ListProjectsResponse\x12.\n" +
	"\bprojects\x18\x01 \x03(\v2\x12.theapp.v1.ProjectR\bprojects\x12\x1d\n" +
	"\n" +
	"total_size\x18\x02 \x01(\x05R\ttotalSize\x12&\n" +
	"\x0fnext_page_token\x18\x03 \x01(\tR\rnextPageToken2\xf0\x02\n" +
	"\x0eProjectService\x12\xdd\x02\n" +
	"\fListProjects\x12\x1e.theapp.v1.ListProjectsRequest\x1a\x1f.theapp.v1.ListProjectsResponse\"\x8b\x02\x92A\xf3\x01J4\n" +
	"\x03400\x12-\n" +
	"\x13Invalid pagination.\x12\x16\n" +
	"\x14\x1a\x12.google.rpc.StatusJ@\n" +
	"\x03401\x129\n" +
	"\x1fMissing or invalid credentials.\x12\x16\n" +
	"\x14\x1a\x12.google.rpc.StatusJ>\n" +
	"\x03404\x127\n" +
	"\x1dAuthenticated user not found.\x12\x16\n" +
	"\x14\x1a\x12.google.rpc.StatusJ9\n" +
	"\x03500\x122\n" +
	"\x18Unexpected server error.\x12\x16\n" +
	"\x14\x1a\x12.google.rpc.Status\x82\xd3\xe4\x93\x02\x0e\x12\f/v1/projectsB\xcd\x02\x92A\xa4\x01\x12\x18\n" +
	"\x12theapp Project API2\x02v1Zv\n" +
	"t\n" +
	"\n" +
	"BearerAuth\x12f\b\x02\x12QAccess token from VerifyMagicLink or RefreshAccessToken. Format: 'Bearer {token}'\x1a\rAuthorization \x02b\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\n" +
	"\rcom.theapp.v1B\fProjectProtoP\x01ZAgithub.com/zorcal/theapp/backend/internal/api/grpc/internal/pb;pb\xa2\x02\x03TXX\xaa\x02\tTheapp.V1\xca\x02\tTheapp\\V1\xe2\x02\x15Theapp\\V1\\GPBMetadata\xea\x02\n" +
	"Theapp::V1b\x06proto3"

var (
	file_project_proto_rawDescOnce sync.Once
	file_project_proto_rawDescData []byte
)

func file_project_proto_rawDescGZIP() []byte {
	file_project_proto_rawDescOnce.Do(func() {
		file_project_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_project_proto_rawDesc), len(file_project_proto_rawDesc)))
	})
	return file_project_proto_rawDescData
}

var file_project_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_project_proto_goTypes = []any{
	(*Project)(nil),               // 0: theapp.v1.Project
	(*ListProjectsRequest)(nil),   // 1: theapp.v1.ListProjectsRequest
	(*ProjectFilter)(nil),         // 2: theapp.v1.ProjectFilter
	(*ListProjectsResponse)(nil),  // 3: theapp.v1.ListProjectsResponse
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_project_proto_depIdxs = []int32{
	4, // 0: theapp.v1.Project.create_time:type_name -> google.protobuf.Timestamp
	4, // 1: theapp.v1.Project.update_time:type_name -> google.protobuf.Timestamp
	2, // 2: theapp.v1.ListProjectsRequest.filter:type_name -> theapp.v1.ProjectFilter
	0, // 3: theapp.v1.ListProjectsResponse.projects:type_name -> theapp.v1.Project
	1, // 4: theapp.v1.ProjectService.ListProjects:input_type -> theapp.v1.ListProjectsRequest
	3, // 5: theapp.v1.ProjectService.ListProjects:output_type -> theapp.v1.ListProjectsResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_project_proto_init() }
func file_project_proto_init() {
	if File_project_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_project_proto_rawDesc), len(file_project_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_project_proto_goTypes,
		DependencyIndexes: file_project_proto_depIdxs,
		MessageInfos:      file_project_proto_msgTypes,
	}.Build()
	File_project_proto = out.File
	file_project_proto_goTypes = nil
	file_project_proto_depIdxs = nil
}
