// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: role.proto

package pb

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Role is a custom role owned by an organization.
type Role struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the role.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Name of the role.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Permissions granted to the role.
	Permissions []Permission `protobuf:"varint,3,rep,packed,name=permissions,proto3,enum=theapp.v1.Permission" json:"permissions,omitempty"`
	// Timestamp when the role was created.
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// Timestamp when the role was last updated.
	UpdateTime *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	// ETag for the current version of the role.
	Etag          string `protobuf:"bytes,6,opt,name=etag,proto3" json:"etag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Role) Reset() {
	*x = Role{}
	mi := &file_role_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Role) ProtoMessage() {}

func (x *Role) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Role.ProtoReflect.Descriptor instead.
func (*Role) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{0}
}

func (x *Role) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Role) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Role) GetPermissions() []Permission {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *Role) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Role) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

func (x *Role) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

// Request message for creating a custom role.
type CreateRoleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The role to create.
	Role          *Role `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleRequest) Reset() {
	*x = CreateRoleRequest{}
	mi := &file_role_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleRequest) ProtoMessage() {}

func (x *CreateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleRequest.ProtoReflect.Descriptor instead.
func (*CreateRoleRequest) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRoleRequest) GetRole() *Role {
	if x != nil {
		return x.Role
	}
	return nil
}

// Request message for getting a custom role.
type GetRoleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the role to get.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoleRequest) Reset() {
	*x = GetRoleRequest{}
	mi := &file_role_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleRequest) ProtoMessage() {}

func (x *GetRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleRequest.ProtoReflect.Descriptor instead.
func (*GetRoleRequest) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{2}
}

func (x *GetRoleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Request message for listing custom roles.
type ListRolesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum number of roles to return.
	PageSize int32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Token for fetching the next page.
	PageToken     string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRolesRequest) Reset() {
	*x = ListRolesRequest{}
	mi := &file_role_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRolesRequest) ProtoMessage() {}

func (x *ListRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRolesRequest.ProtoReflect.Descriptor instead.
func (*ListRolesRequest) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{3}
}

func (x *ListRolesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListRolesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// Response message for listing custom roles.
type ListRolesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Custom roles owned by the caller's organization.
	Roles []*Role `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	// Total number of matching roles.
	TotalSize int32 `protobuf:"varint,2,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	// Token for fetching the next page.
	NextPageToken string `protobuf:"bytes,3,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRolesResponse) Reset() {
	*x = ListRolesResponse{}
	mi := &file_role_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRolesResponse) ProtoMessage() {}

func (x *ListRolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRolesResponse.ProtoReflect.Descriptor instead.
func (*ListRolesResponse) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{4}
}

func (x *ListRolesResponse) GetRoles() []*Role {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *ListRolesResponse) GetTotalSize() int32 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *ListRolesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// Request message for listing a user's project-scoped custom-role assignments.
type ListProjectRoleAssignmentsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the user whose assignments to list.
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Maximum number of assignments to return.
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Token for fetching the next page.
	PageToken     string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectRoleAssignmentsRequest) Reset() {
	*x = ListProjectRoleAssignmentsRequest{}
	mi := &file_role_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectRoleAssignmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectRoleAssignmentsRequest) ProtoMessage() {}

func (x *ListProjectRoleAssignmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectRoleAssignmentsRequest.ProtoReflect.Descriptor instead.
func (*ListProjectRoleAssignmentsRequest) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{5}
}

func (x *ListProjectRoleAssignmentsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListProjectRoleAssignmentsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListProjectRoleAssignmentsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// Response message for listing a user's project-scoped custom-role assignments.
type ListProjectRoleAssignmentsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Custom roles assigned directly in the request's project.
	Roles []*Role `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	// Total number of matching assignments.
	TotalSize int32 `protobuf:"varint,2,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	// Token for fetching the next page.
	NextPageToken string `protobuf:"bytes,3,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectRoleAssignmentsResponse) Reset() {
	*x = ListProjectRoleAssignmentsResponse{}
	mi := &file_role_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectRoleAssignmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectRoleAssignmentsResponse) ProtoMessage() {}

func (x *ListProjectRoleAssignmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectRoleAssignmentsResponse.ProtoReflect.Descriptor instead.
func (*ListProjectRoleAssignmentsResponse) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{6}
}

func (x *ListProjectRoleAssignmentsResponse) GetRoles() []*Role {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *ListProjectRoleAssignmentsResponse) GetTotalSize() int32 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *ListProjectRoleAssignmentsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// Request message for listing a user's organization-scoped custom-role assignments.
type ListOrganizationRoleAssignmentsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the user whose assignments to list.
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Maximum number of assignments to return.
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Token for fetching the next page.
	PageToken     string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrganizationRoleAssignmentsRequest) Reset() {
	*x = ListOrganizationRoleAssignmentsRequest{}
	mi := &file_role_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrganizationRoleAssignmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrganizationRoleAssignmentsRequest) ProtoMessage() {}

func (x *ListOrganizationRoleAssignmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrganizationRoleAssignmentsRequest.ProtoReflect.Descriptor instead.
func (*ListOrganizationRoleAssignmentsRequest) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{7}
}

func (x *ListOrganizationRoleAssignmentsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListOrganizationRoleAssignmentsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListOrganizationRoleAssignmentsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// Response message for listing a user's organization-scoped custom-role assignments.
type ListOrganizationRoleAssignmentsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Custom roles assigned across the request project's organization.
	Roles []*Role `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	// Total number of matching assignments.
	TotalSize int32 `protobuf:"varint,2,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	// Token for fetching the next page.
	NextPageToken string `protobuf:"bytes,3,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrganizationRoleAssignmentsResponse) Reset() {
	*x = ListOrganizationRoleAssignmentsResponse{}
	mi := &file_role_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrganizationRoleAssignmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrganizationRoleAssignmentsResponse) ProtoMessage() {}

func (x *ListOrganizationRoleAssignmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrganizationRoleAssignmentsResponse.ProtoReflect.Descriptor instead.
func (*ListOrganizationRoleAssignmentsResponse) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{8}
}

func (x *ListOrganizationRoleAssignmentsResponse) GetRoles() []*Role {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *ListOrganizationRoleAssignmentsResponse) GetTotalSize() int32 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *ListOrganizationRoleAssignmentsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// Request message for updating a custom role.
type UpdateRoleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The role to update.
	Role *Role `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	// Fields to update.
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoleRequest) Reset() {
	*x = UpdateRoleRequest{}
	mi := &file_role_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleRequest) ProtoMessage() {}

func (x *UpdateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleRequest.ProtoReflect.Descriptor instead.
func (*UpdateRoleRequest) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateRoleRequest) GetRole() *Role {
	if x != nil {
		return x.Role
	}
	return nil
}

func (x *UpdateRoleRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

// Request message for modifying a custom role's permissions.
type ModifyRolePermissionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the role to modify.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Permission names to add to the role.
	AddPermissions []Permission `protobuf:"varint,2,rep,packed,name=add_permissions,json=addPermissions,proto3,enum=theapp.v1.Permission" json:"add_permissions,omitempty"`
	// Permission names to remove from the role.
	RemovePermissions []Permission `protobuf:"varint,3,rep,packed,name=remove_permissions,json=removePermissions,proto3,enum=theapp.v1.Permission" json:"remove_permissions,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ModifyRolePermissionsRequest) Reset() {
	*x = ModifyRolePermissionsRequest{}
	mi := &file_role_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModifyRolePermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyRolePermissionsRequest) ProtoMessage() {}

func (x *ModifyRolePermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyRolePermissionsRequest.ProtoReflect.Descriptor instead.
func (*ModifyRolePermissionsRequest) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{10}
}

func (x *ModifyRolePermissionsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ModifyRolePermissionsRequest) GetAddPermissions() []Permission {
	if x != nil {
		return x.AddPermissions
	}
	return nil
}

func (x *ModifyRolePermissionsRequest) GetRemovePermissions() []Permission {
	if x != nil {
		return x.RemovePermissions
	}
	return nil
}

// Request message for deleting a custom role.
type DeleteRoleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the role to delete.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoleRequest) Reset() {
	*x = DeleteRoleRequest{}
	mi := &file_role_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoleRequest) ProtoMessage() {}

func (x *DeleteRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoleRequest.ProtoReflect.Descriptor instead.
func (*DeleteRoleRequest) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteRoleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Response message for deleting a custom role.
type DeleteRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoleResponse) Reset() {
	*x = DeleteRoleResponse{}
	mi := &file_role_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoleResponse) ProtoMessage() {}

func (x *DeleteRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoleResponse.ProtoReflect.Descriptor instead.
func (*DeleteRoleResponse) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{12}
}

// Request message for assigning a custom role in the request's project.
type AssignRoleToProjectRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the role to assign.
	RoleId string `protobuf:"bytes,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	// ID of the user to assign the role to.
	UserId        string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignRoleToProjectRequest) Reset() {
	*x = AssignRoleToProjectRequest{}
	mi := &file_role_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignRoleToProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignRoleToProjectRequest) ProtoMessage() {}

func (x *AssignRoleToProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignRoleToProjectRequest.ProtoReflect.Descriptor instead.
func (*AssignRoleToProjectRequest) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{13}
}

func (x *AssignRoleToProjectRequest) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *AssignRoleToProjectRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Response message for assigning a custom role in a project.
type AssignRoleToProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignRoleToProjectResponse) Reset() {
	*x = AssignRoleToProjectResponse{}
	mi := &file_role_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignRoleToProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignRoleToProjectResponse) ProtoMessage() {}

func (x *AssignRoleToProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignRoleToProjectResponse.ProtoReflect.Descriptor instead.
func (*AssignRoleToProjectResponse) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{14}
}

// Request message for unassigning a custom role in the request's project.
type UnassignRoleFromProjectRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the role to unassign.
	RoleId string `protobuf:"bytes,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	// ID of the user to unassign the role from.
	UserId        string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnassignRoleFromProjectRequest) Reset() {
	*x = UnassignRoleFromProjectRequest{}
	mi := &file_role_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnassignRoleFromProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnassignRoleFromProjectRequest) ProtoMessage() {}

func (x *UnassignRoleFromProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnassignRoleFromProjectRequest.ProtoReflect.Descriptor instead.
func (*UnassignRoleFromProjectRequest) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{15}
}

func (x *UnassignRoleFromProjectRequest) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *UnassignRoleFromProjectRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Response message for unassigning a custom role from a project.
type UnassignRoleFromProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnassignRoleFromProjectResponse) Reset() {
	*x = UnassignRoleFromProjectResponse{}
	mi := &file_role_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnassignRoleFromProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnassignRoleFromProjectResponse) ProtoMessage() {}

func (x *UnassignRoleFromProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnassignRoleFromProjectResponse.ProtoReflect.Descriptor instead.
func (*UnassignRoleFromProjectResponse) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{16}
}

// Request message for assigning a custom role across the request project's organization.
type AssignRoleToOrganizationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the role to assign.
	RoleId string `protobuf:"bytes,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	// ID of the user to assign the role to.
	UserId        string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignRoleToOrganizationRequest) Reset() {
	*x = AssignRoleToOrganizationRequest{}
	mi := &file_role_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignRoleToOrganizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignRoleToOrganizationRequest) ProtoMessage() {}

func (x *AssignRoleToOrganizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignRoleToOrganizationRequest.ProtoReflect.Descriptor instead.
func (*AssignRoleToOrganizationRequest) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{17}
}

func (x *AssignRoleToOrganizationRequest) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *AssignRoleToOrganizationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Response message for assigning a custom role across an organization.
type AssignRoleToOrganizationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignRoleToOrganizationResponse) Reset() {
	*x = AssignRoleToOrganizationResponse{}
	mi := &file_role_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignRoleToOrganizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignRoleToOrganizationResponse) ProtoMessage() {}

func (x *AssignRoleToOrganizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignRoleToOrganizationResponse.ProtoReflect.Descriptor instead.
func (*AssignRoleToOrganizationResponse) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{18}
}

// Request message for unassigning a custom role across the request project's organization.
type UnassignRoleFromOrganizationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the role to unassign.
	RoleId string `protobuf:"bytes,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	// ID of the user to unassign the role from.
	UserId        string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnassignRoleFromOrganizationRequest) Reset() {
	*x = UnassignRoleFromOrganizationRequest{}
	mi := &file_role_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnassignRoleFromOrganizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnassignRoleFromOrganizationRequest) ProtoMessage() {}

func (x *UnassignRoleFromOrganizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnassignRoleFromOrganizationRequest.ProtoReflect.Descriptor instead.
func (*UnassignRoleFromOrganizationRequest) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{19}
}

func (x *UnassignRoleFromOrganizationRequest) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *UnassignRoleFromOrganizationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Response message for unassigning a custom role from an organization.
type UnassignRoleFromOrganizationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnassignRoleFromOrganizationResponse) Reset() {
	*x = UnassignRoleFromOrganizationResponse{}
	mi := &file_role_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnassignRoleFromOrganizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnassignRoleFromOrganizationResponse) ProtoMessage() {}

func (x *UnassignRoleFromOrganizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnassignRoleFromOrganizationResponse.ProtoReflect.Descriptor instead.
func (*UnassignRoleFromOrganizationResponse) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{20}
}

var File_role_proto protoreflect.FileDescriptor

const file_role_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"role.proto\x12\ttheapp.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/api/field_info.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x10permission.proto\"\x95\x02\n" +
	"\x04Role\x12\x1b\n" +
	"\x02id\x18\x01 \x01(\tB\v\xe0A\x03\xe2\x8c\xcf\xd7\b\x02\b\x01R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x127\n" +
	"\vpermissions\x18\x03 \x03(\x0e2\x15.theapp.v1.PermissionR\vpermissions\x12@\n" +
	"\vcreate_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"createTime\x12@\n" +
	"\vupdate_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"updateTime\x12\x1f\n" +
	"\x04etag\x18\x06 \x01(\tB\v\xe0A\x03\xe2\x8c\xcf\xd7\b\x02\b\x01R\x04etag\"=\n" +
	"\x11CreateRoleRequest\x12(\n" +
	"\x04role\x18\x01 \x01(\v2\x0f.theapp.v1.RoleB\x03\xe0A\x02R\x04role\"-\n" +
	"\x0eGetRoleRequest\x12\x1b\n" +
	"\x02id\x18\x01 \x01(\tB\v\xe0A\x02\xe2\x8c\xcf\xd7\b\x02\b\x01R\x02id\"N\n" +
	"\x10ListRolesRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"\x81\x01\n" +
	"\x11ListRolesResponse\x12%\n" +
	"\x05roles\x18\x01 \x03(\v2\x0f.theapp.v1.RoleR\x05roles\x12\x1d\n" +
	"\n" +
	"total_size\x18\x02 \x01(\x05R\ttotalSize\x12&\n" +
	"\x0fnext_page_token\x18\x03 \x01(\tR\rnextPageToken\"\x85\x01\n" +
	"!ListProjectRoleAssignmentsRequest\x12$\n" +
	"\auser_id\x18\x01 \x01(\tB\v\xe0A\x02\xe2\x8c\xcf\xd7\b\x02\b\x01R\x06userId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"\x92\x01\n" +
	"\"ListProjectRoleAssignmentsResponse\x12%\n" +
	"\x05roles\x18\x01 \x03(\v2\x0f.theapp.v1.RoleR\x05roles\x12\x1d\n" +
	"\n" +
	"total_size\x18\x02 \x01(\x05R\ttotalSize\x12&\n" +
	"\x0fnext_page_token\x18\x03 \x01(\tR\rnextPageToken\"\x8a\x01\n" +
	"&ListOrganizationRoleAssignmentsRequest\x12$\n" +
	"\auser_id\x18\x01 \x01(\tB\v\xe0A\x02\xe2\x8c\xcf\xd7\b\x02\b\x01R\x06userId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"\x97\x01\n" +
	"'ListOrganizationRoleAssignmentsResponse\x12%\n" +
	"\x05roles\x18\x01 \x03(\v2\x0f.theapp.v1.RoleR\x05roles\x12\x1d\n" +
	"\n" +
	"total_size\x18\x02 \x01(\x05R\ttotalSize\x12&\n" +
	"\x0fnext_page_token\x18\x03 \x01(\tR\rnextPageToken\"\x7f\n" +
	"\x11UpdateRoleRequest\x12(\n" +
	"\x04role\x18\x01 \x01(\v2\x0f.theapp.v1.RoleB\x03\xe0A\x02R\x04role\x12@\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x02R\n" +
	"updateMask\"\xc1\x01\n" +
	"\x1cModifyRolePermissionsRequest\x12\x1b\n" +
	"\x02id\x18\x01 \x01(\tB\v\xe0A\x02\xe2\x8c\xcf\xd7\b\x02\b\x01R\x02id\x12>\n" +
	"\x0fadd_permissions\x18\x02 \x03(\x0e2\x15.theapp.v1.PermissionR\x0eaddPermissions\x12D\n" +
	"\x12remove_permissions\x18\x03 \x03(\x0e2\x15.theapp.v1.PermissionR\x11removePermissions\"0\n" +
	"\x11DeleteRoleRequest\x12\x1b\n" +
	"\x02id\x18\x01 \x01(\tB\v\xe0A\x02\xe2\x8c\xcf\xd7\b\x02\b\x01R\x02id\"\x14\n" +
	"\x12DeleteRoleResponse\"h\n" +
	"\x1aAssignRoleToProjectRequest\x12$\n" +
	"\arole_id\x18\x01 \x01(\tB\v\xe0A\x02\xe2\x8c\xcf\xd7\b\x02\b\x01R\x06roleId\x12$\n" +
	"\auser_id\x18\x02 \x01(\tB\v\xe0A\x02\xe2\x8c\xcf\xd7\b\x02\b\x01R\x06userId\"\x1d\n" +
	"\x1bAssignRoleToProjectResponse\"l\n" +
	"\x1eUnassignRoleFromProjectRequest\x12$\n" +
	"\arole_id\x18\x01 \x01(\tB\v\xe0A\x02\xe2\x8c\xcf\xd7\b\x02\b\x01R\x06roleId\x12$\n" +
	"\auser_id\x18\x02 \x01(\tB\v\xe0A\x02\xe2\x8c\xcf\xd7\b\x02\b\x01R\x06userId\"!\n" +
	"\x1fUnassignRoleFromProjectResponse\"m\n" +
	"\x1fAssignRoleToOrganizationRequest\x12$\n" +
	"\arole_id\x18\x01 \x01(\tB\v\xe0A\x02\xe2\x8c\xcf\xd7\b\x02\b\x01R\x06roleId\x12$\n" +
	"\auser_id\x18\x02 \x01(\tB\v\xe0A\x02\xe2\x8c\xcf\xd7\b\x02\b\x01R\x06userId\"\"\n" +
	" AssignRoleToOrganizationResponse\"q\n" +
	"#UnassignRoleFromOrganizationRequest\x12$\n" +
	"\arole_id\x18\x01 \x01(\tB\v\xe0A\x02\xe2\x8c\xcf\xd7\b\x02\b\x01R\x06roleId\x12$\n" +
	"\auser_id\x18\x02 \x01(\tB\v\xe0A\x02\xe2\x8c\xcf\xd7\b\x02\b\x01R\x06userId\"&\n" +
	"$UnassignRoleFromOrganizationResponse2\xb3\x13\n" +
	"\vRoleService\x12\x97\x01\n" +
	"\n" +
	"CreateRole\x12\x1c.theapp.v1.CreateRoleRequest\x1a\x0f.theapp.v1.Role\"Z\x92ACrA\n" +
	"?\n" +
	"\fx-project-id\x12+ID of a project in the role's organization.\x18\x03(\x01\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/roles\x12\x93\x01\n" +
	"\aGetRole\x12\x19.theapp.v1.GetRoleRequest\x1a\x0f.theapp.v1.Role\"\\\x92ACrA\n" +
	"?\n" +
	"\fx-project-id\x12+ID of a project in the role's organization.\x18\x03(\x01\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/roles/{id}\x12\x9f\x01\n" +
	"\tListRoles\x12\x1b.theapp.v1.ListRolesRequest\x1a\x1c.theapp.v1.ListRolesResponse\"W\x92ACrA\n" +
	"?\n" +
	"\fx-project-id\x12+ID of a project in the role's organization.\x18\x03(\x01\x82\xd3\xe4\x93\x02\v\x12\t/v1/roles\x12\xe6\x01\n" +
	"\x1aListProjectRoleAssignments\x12,.theapp.v1.ListProjectRoleAssignmentsRequest\x1a-.theapp.v1.ListProjectRoleAssignmentsResponse\"k\x92ADrB\n" +
	"@\n" +
	"\fx-project-id\x12,ID of the project whose assignments to list.\x18\x03(\x01\x82\xd3\xe4\x93\x02\x1e\x12\x1c/v1/project-role-assignments\x12\x8d\x02\n" +
	"\x1fListOrganizationRoleAssignments\x121.theapp.v1.ListOrganizationRoleAssignmentsRequest\x1a2.theapp.v1.ListOrganizationRoleAssignmentsResponse\"\x82\x01\x92AVrT\n" +
	"R\n" +
	"\fx-project-id\x12>ID of a project in the organization whose assignments to list.\x18\x03(\x01\x82\xd3\xe4\x93\x02#\x12!/v1/organization-role-assignments\x12\xa1\x01\n" +
	"\n" +
	"UpdateRole\x12\x1c.theapp.v1.UpdateRoleRequest\x1a\x0f.theapp.v1.Role\"d\x92ACrA\n" +
	"?\n" +
	"\fx-project-id\x12+ID of a project in the role's organization.\x18\x03(\x01\x82\xd3\xe4\x93\x02\x18:\x01*2\x13/v1/roles/{role.id}\x12\xc4\x01\n" +
	"\x15ModifyRolePermissions\x12'.theapp.v1.ModifyRolePermissionsRequest\x1a\x0f.theapp.v1.Role\"q\x92ACrA\n" +
	"?\n" +
	"\fx-project-id\x12+ID of a project in the role's organization.\x18\x03(\x01\x82\xd3\xe4\x93\x02%:\x01*\" /v1/roles/{id}:modifyPermissions\x12\xa7\x01\n" +
	"\n" +
	"DeleteRole\x12\x1c.theapp.v1.DeleteRoleRequest\x1a\x1d.theapp.v1.DeleteRoleResponse\"\\\x92ACrA\n" +
	"?\n" +
	"\fx-project-id\x12+ID of a project in the role's organization.\x18\x03(\x01\x82\xd3\xe4\x93\x02\x10*\x0e/v1/roles/{id}\x12\xd2\x01\n" +
	"\x13AssignRoleToProject\x12%.theapp.v1.AssignRoleToProjectRequest\x1a&.theapp.v1.AssignRoleToProjectResponse\"l\x92AErC\n" +
	"A\n" +
	"\fx-project-id\x12-ID of the project where the role is assigned.\x18\x03(\x01\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/v1/roles:assignToProject\x12\xe4\x01\n" +
	"\x17UnassignRoleFromProject\x12).theapp.v1.UnassignRoleFromProjectRequest\x1a*.theapp.v1.UnassignRoleFromProjectResponse\"r\x92AGrE\n" +
	"C\n" +
	"\fx-project-id\x12/ID of the project where the role is unassigned.\x18\x03(\x01\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/v1/roles:unassignFromProject\x12\xf9\x01\n" +
	"\x18AssignRoleToOrganization\x12*.theapp.v1.AssignRoleToOrganizationRequest\x1a+.theapp.v1.AssignRoleToOrganizationResponse\"\x83\x01\x92AWrU\n" +
	"S\n" +
	"\fx-project-id\x12?ID of a project in the organization where the role is assigned.\x18\x03(\x01\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/v1/roles:assignToOrganization\x12\x8b\x02\n" +
	"\x1cUnassignRoleFromOrganization\x12..theapp.v1.UnassignRoleFromOrganizationRequest\x1a/.theapp.v1.UnassignRoleFromOrganizationResponse\"\x89\x01\x92AYrW\n" +
	"U\n" +
	"\fx-project-id\x12AID of a project in the organization where the role is unassigned.\x18\x03(\x01\x82\xd3\xe4\x93\x02':\x01*\"\"/v1/roles:unassignFromOrganizationB\xc7\x02\x92A\xa1\x01\x12\x15\n" +
	"\x0ftheapp Role API2\x02v1Zv\n" +
	"t\n" +
	"\n" +
	"BearerAuth\x12f\b\x02\x12QAccess token from VerifyMagicLink or RefreshAccessToken. Format: 'Bearer {token}'\x1a\rAuthorization \x02b\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\n" +
	"\rcom.theapp.v1B\tRoleProtoP\x01ZAgithub.com/zorcal/theapp/backend/internal/api/grpc/internal/pb;pb\xa2\x02\x03TXX\xaa\x02\tTheapp.V1\xca\x02\tTheapp\\V1\xe2\x02\x15Theapp\\V1\\GPBMetadata\xea\x02\n" +
	"Theapp::V1b\x06proto3"

var (
	file_role_proto_rawDescOnce sync.Once
	file_role_proto_rawDescData []byte
)

func file_role_proto_rawDescGZIP() []byte {
	file_role_proto_rawDescOnce.Do(func() {
		file_role_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_role_proto_rawDesc), len(file_role_proto_rawDesc)))
	})
	return file_role_proto_rawDescData
}

var file_role_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_role_proto_goTypes = []any{
	(*Role)(nil),                                    // 0: theapp.v1.Role
	(*CreateRoleRequest)(nil),                       // 1: theapp.v1.CreateRoleRequest
	(*GetRoleRequest)(nil),                          // 2: theapp.v1.GetRoleRequest
	(*ListRolesRequest)(nil),                        // 3: theapp.v1.ListRolesRequest
	(*ListRolesResponse)(nil),                       // 4: theapp.v1.ListRolesResponse
	(*ListProjectRoleAssignmentsRequest)(nil),       // 5: theapp.v1.ListProjectRoleAssignmentsRequest
	(*ListProjectRoleAssignmentsResponse)(nil),      // 6: theapp.v1.ListProjectRoleAssignmentsResponse
	(*ListOrganizationRoleAssignmentsRequest)(nil),  // 7: theapp.v1.ListOrganizationRoleAssignmentsRequest
	(*ListOrganizationRoleAssignmentsResponse)(nil), // 8: theapp.v1.ListOrganizationRoleAssignmentsResponse
	(*UpdateRoleRequest)(nil),                       // 9: theapp.v1.UpdateRoleRequest
	(*ModifyRolePermissionsRequest)(nil),            // 10: theapp.v1.ModifyRolePermissionsRequest
	(*DeleteRoleRequest)(nil),                       // 11: theapp.v1.DeleteRoleRequest
	(*DeleteRoleResponse)(nil),                      // 12: theapp.v1.DeleteRoleResponse
	(*AssignRoleToProjectRequest)(nil),              // 13: theapp.v1.AssignRoleToProjectRequest
	(*AssignRoleToProjectResponse)(nil),             // 14: theapp.v1.AssignRoleToProjectResponse
	(*UnassignRoleFromProjectRequest)(nil),          // 15: theapp.v1.UnassignRoleFromProjectRequest
	(*UnassignRoleFromProjectResponse)(nil),         // 16: theapp.v1.UnassignRoleFromProjectResponse
	(*AssignRoleToOrganizationRequest)(nil),         // 17: theapp.v1.AssignRoleToOrganizationRequest
	(*AssignRoleToOrganizationResponse)(nil),        // 18: theapp.v1.AssignRoleToOrganizationResponse
	(*UnassignRoleFromOrganizationRequest)(nil),     // 19: theapp.v1.UnassignRoleFromOrganizationRequest
	(*UnassignRoleFromOrganizationResponse)(nil),    // 20: theapp.v1.UnassignRoleFromOrganizationResponse
	(Permission)(0),                                 // 21: theapp.v1.Permission
	(*timestamppb.Timestamp)(nil),                   // 22: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil),                   // 23: google.protobuf.FieldMask
}
var file_role_proto_depIdxs = []int32{
	21, // 0: theapp.v1.Role.permissions:type_name -> theapp.v1.Permission
	22, // 1: theapp.v1.Role.create_time:type_name -> google.protobuf.Timestamp
	22, // 2: theapp.v1.Role.update_time:type_name -> google.protobuf.Timestamp
	0,  // 3: theapp.v1.CreateRoleRequest.role:type_name -> theapp.v1.Role
	0,  // 4: theapp.v1.ListRolesResponse.roles:type_name -> theapp.v1.Role
	0,  // 5: theapp.v1.ListProjectRoleAssignmentsResponse.roles:type_name -> theapp.v1.Role
	0,  // 6: theapp.v1.ListOrganizationRoleAssignmentsResponse.roles:type_name -> theapp.v1.Role
	0,  // 7: theapp.v1.UpdateRoleRequest.role:type_name -> theapp.v1.Role
	23, // 8: theapp.v1.UpdateRoleRequest.update_mask:type_name -> google.protobuf.FieldMask
	21, // 9: theapp.v1.ModifyRolePermissionsRequest.add_permissions:type_name -> theapp.v1.Permission
	21, // 10: theapp.v1.ModifyRolePermissionsRequest.remove_permissions:type_name -> theapp.v1.Permission
	1,  // 11: theapp.v1.RoleService.CreateRole:input_type -> theapp.v1.CreateRoleRequest
	2,  // 12: theapp.v1.RoleService.GetRole:input_type -> theapp.v1.GetRoleRequest
	3,  // 13: theapp.v1.RoleService.ListRoles:input_type -> theapp.v1.ListRolesRequest
	5,  // 14: theapp.v1.RoleService.ListProjectRoleAssignments:input_type -> theapp.v1.ListProjectRoleAssignmentsRequest
	7,  // 15: theapp.v1.RoleService.ListOrganizationRoleAssignments:input_type -> theapp.v1.ListOrganizationRoleAssignmentsRequest
	9,  // 16: theapp.v1.RoleService.UpdateRole:input_type -> theapp.v1.UpdateRoleRequest
	10, // 17: theapp.v1.RoleService.ModifyRolePermissions:input_type -> theapp.v1.ModifyRolePermissionsRequest
	11, // 18: theapp.v1.RoleService.DeleteRole:input_type -> theapp.v1.DeleteRoleRequest
	13, // 19: theapp.v1.RoleService.AssignRoleToProject:input_type -> theapp.v1.AssignRoleToProjectRequest
	15, // 20: theapp.v1.RoleService.UnassignRoleFromProject:input_type -> theapp.v1.UnassignRoleFromProjectRequest
	17, // 21: theapp.v1.RoleService.AssignRoleToOrganization:input_type -> theapp.v1.AssignRoleToOrganizationRequest
	19, // 22: theapp.v1.RoleService.UnassignRoleFromOrganization:input_type -> theapp.v1.UnassignRoleFromOrganizationRequest
	0,  // 23: theapp.v1.RoleService.CreateRole:output_type -> theapp.v1.Role
	0,  // 24: theapp.v1.RoleService.GetRole:output_type -> theapp.v1.Role
	4,  // 25: theapp.v1.RoleService.ListRoles:output_type -> theapp.v1.ListRolesResponse
	6,  // 26: theapp.v1.RoleService.ListProjectRoleAssignments:output_type -> theapp.v1.ListProjectRoleAssignmentsResponse
	8,  // 27: theapp.v1.RoleService.ListOrganizationRoleAssignments:output_type -> theapp.v1.ListOrganizationRoleAssignmentsResponse
	0,  // 28: theapp.v1.RoleService.UpdateRole:output_type -> theapp.v1.Role
	0,  // 29: theapp.v1.RoleService.ModifyRolePermissions:output_type -> theapp.v1.Role
	12, // 30: theapp.v1.RoleService.DeleteRole:output_type -> theapp.v1.DeleteRoleResponse
	14, // 31: theapp.v1.RoleService.AssignRoleToProject:output_type -> theapp.v1.AssignRoleToProjectResponse
	16, // 32: theapp.v1.RoleService.UnassignRoleFromProject:output_type -> theapp.v1.UnassignRoleFromProjectResponse
	18, // 33: theapp.v1.RoleService.AssignRoleToOrganization:output_type -> theapp.v1.AssignRoleToOrganizationResponse
	20, // 34: theapp.v1.RoleService.UnassignRoleFromOrganization:output_type -> theapp.v1.UnassignRoleFromOrganizationResponse
	23, // [23:35] is the sub-list for method output_type
	11, // [11:23] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_role_proto_init() }
func file_role_proto_init() {
	if File_role_proto != nil {
		return
	}
	file_permission_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_role_proto_rawDesc), len(file_role_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_role_proto_goTypes,
		DependencyIndexes: file_role_proto_depIdxs,
		MessageInfos:      file_role_proto_msgTypes,
	}.Build()
	File_role_proto = out.File
	file_role_proto_goTypes = nil
	file_role_proto_depIdxs = nil
}
