// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: system_role.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SystemRoleService_ListSystemRoles_FullMethodName           = "/theapp.v1.SystemRoleService/ListSystemRoles"
	SystemRoleService_AssignSystemRole_FullMethodName          = "/theapp.v1.SystemRoleService/AssignSystemRole"
	SystemRoleService_UnassignSystemRole_FullMethodName        = "/theapp.v1.SystemRoleService/UnassignSystemRole"
	SystemRoleService_ListSystemRoleAssignments_FullMethodName = "/theapp.v1.SystemRoleService/ListSystemRoleAssignments"
)

// SystemRoleServiceClient is the client API for SystemRoleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SystemRoleService lists seeded system roles and manages their user
// assignments. System-role definitions cannot be created, updated, or deleted
// through the API. Every call is anchored on the "theapp" organization's
// control project: x-project-id must be that project's ID.
type SystemRoleServiceClient interface {
	// Lists the system roles available to assign.
	ListSystemRoles(ctx context.Context, in *ListSystemRolesRequest, opts ...grpc.CallOption) (*ListSystemRolesResponse, error)
	// Assigns a system role to a user.
	AssignSystemRole(ctx context.Context, in *AssignSystemRoleRequest, opts ...grpc.CallOption) (*AssignSystemRoleResponse, error)
	// Unassigns a system role from a user.
	UnassignSystemRole(ctx context.Context, in *UnassignSystemRoleRequest, opts ...grpc.CallOption) (*UnassignSystemRoleResponse, error)
	// Lists the system roles a user holds.
	ListSystemRoleAssignments(ctx context.Context, in *ListSystemRoleAssignmentsRequest, opts ...grpc.CallOption) (*ListSystemRoleAssignmentsResponse, error)
}

type systemRoleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSystemRoleServiceClient(cc grpc.ClientConnInterface) SystemRoleServiceClient {
	return &systemRoleServiceClient{cc}
}

func (c *systemRoleServiceClient) ListSystemRoles(ctx context.Context, in *ListSystemRolesRequest, opts ...grpc.CallOption) (*ListSystemRolesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSystemRolesResponse)
	err := c.cc.Invoke(ctx, SystemRoleService_ListSystemRoles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemRoleServiceClient) AssignSystemRole(ctx context.Context, in *AssignSystemRoleRequest, opts ...grpc.CallOption) (*AssignSystemRoleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssignSystemRoleResponse)
	err := c.cc.Invoke(ctx, SystemRoleService_AssignSystemRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemRoleServiceClient) UnassignSystemRole(ctx context.Context, in *UnassignSystemRoleRequest, opts ...grpc.CallOption) (*UnassignSystemRoleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnassignSystemRoleResponse)
	err := c.cc.Invoke(ctx, SystemRoleService_UnassignSystemRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemRoleServiceClient) ListSystemRoleAssignments(ctx context.Context, in *ListSystemRoleAssignmentsRequest, opts ...grpc.CallOption) (*ListSystemRoleAssignmentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSystemRoleAssignmentsResponse)
	err := c.cc.Invoke(ctx, SystemRoleService_ListSystemRoleAssignments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SystemRoleServiceServer is the server API for SystemRoleService service.
// All implementations should embed UnimplementedSystemRoleServiceServer
// for forward compatibility.
//
// SystemRoleService lists seeded system roles and manages their user
// assignments. System-role definitions cannot be created, updated, or deleted
// through the API. Every call is anchored on the "theapp" organization's
// control project: x-project-id must be that project's ID.
type SystemRoleServiceServer interface {
	// Lists the system roles available to assign.
	ListSystemRoles(context.Context, *ListSystemRolesRequest) (*ListSystemRolesResponse, error)
	// Assigns a system role to a user.
	AssignSystemRole(context.Context, *AssignSystemRoleRequest) (*AssignSystemRoleResponse, error)
	// Unassigns a system role from a user.
	UnassignSystemRole(context.Context, *UnassignSystemRoleRequest) (*UnassignSystemRoleResponse, error)
	// Lists the system roles a user holds.
	ListSystemRoleAssignments(context.Context, *ListSystemRoleAssignmentsRequest) (*ListSystemRoleAssignmentsResponse, error)
}

// UnimplementedSystemRoleServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSystemRoleServiceServer struct{}

func (UnimplementedSystemRoleServiceServer) ListSystemRoles(context.Context, *ListSystemRolesRequest) (*ListSystemRolesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSystemRoles not implemented")
}
func (UnimplementedSystemRoleServiceServer) AssignSystemRole(context.Context, *AssignSystemRoleRequest) (*AssignSystemRoleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AssignSystemRole not implemented")
}
func (UnimplementedSystemRoleServiceServer) UnassignSystemRole(context.Context, *UnassignSystemRoleRequest) (*UnassignSystemRoleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnassignSystemRole not implemented")
}
func (UnimplementedSystemRoleServiceServer) ListSystemRoleAssignments(context.Context, *ListSystemRoleAssignmentsRequest) (*ListSystemRoleAssignmentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSystemRoleAssignments not implemented")
}
func (UnimplementedSystemRoleServiceServer) testEmbeddedByValue() {}

// UnsafeSystemRoleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SystemRoleServiceServer will
// result in compilation errors.
type UnsafeSystemRoleServiceServer interface {
	mustEmbedUnimplementedSystemRoleServiceServer()
}

func RegisterSystemRoleServiceServer(s grpc.ServiceRegistrar, srv SystemRoleServiceServer) {
	// If the following call panics, it indicates UnimplementedSystemRoleServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SystemRoleService_ServiceDesc, srv)
}

func _SystemRoleService_ListSystemRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSystemRolesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemRoleServiceServer).ListSystemRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemRoleService_ListSystemRoles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemRoleServiceServer).ListSystemRoles(ctx, req.(*ListSystemRolesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemRoleService_AssignSystemRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignSystemRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemRoleServiceServer).AssignSystemRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemRoleService_AssignSystemRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemRoleServiceServer).AssignSystemRole(ctx, req.(*AssignSystemRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemRoleService_UnassignSystemRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnassignSystemRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemRoleServiceServer).UnassignSystemRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemRoleService_UnassignSystemRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemRoleServiceServer).UnassignSystemRole(ctx, req.(*UnassignSystemRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemRoleService_ListSystemRoleAssignments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSystemRoleAssignmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemRoleServiceServer).ListSystemRoleAssignments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemRoleService_ListSystemRoleAssignments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemRoleServiceServer).ListSystemRoleAssignments(ctx, req.(*ListSystemRoleAssignmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SystemRoleService_ServiceDesc is the grpc.ServiceDesc for SystemRoleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SystemRoleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "theapp.v1.SystemRoleService",
	HandlerType: (*SystemRoleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListSystemRoles",
			Handler:    _SystemRoleService_ListSystemRoles_Handler,
		},
		{
			MethodName: "AssignSystemRole",
			Handler:    _SystemRoleService_AssignSystemRole_Handler,
		},
		{
			MethodName: "UnassignSystemRole",
			Handler:    _SystemRoleService_UnassignSystemRole_Handler,
		},
		{
			MethodName: "ListSystemRoleAssignments",
			Handler:    _SystemRoleService_ListSystemRoleAssignments_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "system_role.proto",
}
