// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package org

import (
	"context"
	"sync"

	"github.com/zorcal/theapp/backend/internal/core/pgstores/pgorg"
)

// Ensure, that MockedOrgStorer does implement OrgStorer.
// If this is not the case, regenerate this file with moq.
var _ OrgStorer = &MockedOrgStorer{}

// MockedOrgStorer is a mock implementation of OrgStorer.
//
//	func TestSomethingThatUsesOrgStorer(t *testing.T) {
//
//		// make and configure a mocked OrgStorer
//		mockedOrgStorer := &MockedOrgStorer{
//			CreateOrganizationFunc: func(ctx context.Context, co pgorg.CreateOrganization) (pgorg.Organization, error) {
//				panic("mock out the CreateOrganization method")
//			},
//			CreateProjectFunc: func(ctx context.Context, cp pgorg.CreateProject) (pgorg.Project, error) {
//				panic("mock out the CreateProject method")
//			},
//			OrganizationByNameFunc: func(ctx context.Context, name string) (pgorg.Organization, error) {
//				panic("mock out the OrganizationByName method")
//			},
//			ProjectByNameFunc: func(ctx context.Context, orgID int, name string) (pgorg.Project, error) {
//				panic("mock out the ProjectByName method")
//			},
//		}
//
//		// use mockedOrgStorer in code that requires OrgStorer
//		// and then make assertions.
//
//	}
type MockedOrgStorer struct {
	// CreateOrganizationFunc mocks the CreateOrganization method.
	CreateOrganizationFunc func(ctx context.Context, co pgorg.CreateOrganization) (pgorg.Organization, error)

	// CreateProjectFunc mocks the CreateProject method.
	CreateProjectFunc func(ctx context.Context, cp pgorg.CreateProject) (pgorg.Project, error)

	// OrganizationByNameFunc mocks the OrganizationByName method.
	OrganizationByNameFunc func(ctx context.Context, name string) (pgorg.Organization, error)

	// ProjectByNameFunc mocks the ProjectByName method.
	ProjectByNameFunc func(ctx context.Context, orgID int, name string) (pgorg.Project, error)

	// calls tracks calls to the methods.
	calls struct {
		// CreateOrganization holds details about calls to the CreateOrganization method.
		CreateOrganization []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Co is the co argument value.
			Co pgorg.CreateOrganization
		}
		// CreateProject holds details about calls to the CreateProject method.
		CreateProject []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Cp is the cp argument value.
			Cp pgorg.CreateProject
		}
		// OrganizationByName holds details about calls to the OrganizationByName method.
		OrganizationByName []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
		}
		// ProjectByName holds details about calls to the ProjectByName method.
		ProjectByName []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgID is the orgID argument value.
			OrgID int
			// Name is the name argument value.
			Name string
		}
	}
	lockCreateOrganization sync.RWMutex
	lockCreateProject      sync.RWMutex
	lockOrganizationByName sync.RWMutex
	lockProjectByName      sync.RWMutex
}

// CreateOrganization calls CreateOrganizationFunc.
func (mock *MockedOrgStorer) CreateOrganization(ctx context.Context, co pgorg.CreateOrganization) (pgorg.Organization, error) {
	if mock.CreateOrganizationFunc == nil {
		panic("MockedOrgStorer.CreateOrganizationFunc: method is nil but OrgStorer.CreateOrganization was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Co  pgorg.CreateOrganization
	}{
		Ctx: ctx,
		Co:  co,
	}
	mock.lockCreateOrganization.Lock()
	mock.calls.CreateOrganization = append(mock.calls.CreateOrganization, callInfo)
	mock.lockCreateOrganization.Unlock()
	return mock.CreateOrganizationFunc(ctx, co)
}

// CreateOrganizationCalls gets all the calls that were made to CreateOrganization.
// Check the length with:
//
//	len(mockedOrgStorer.CreateOrganizationCalls())
func (mock *MockedOrgStorer) CreateOrganizationCalls() []struct {
	Ctx context.Context
	Co  pgorg.CreateOrganization
} {
	var calls []struct {
		Ctx context.Context
		Co  pgorg.CreateOrganization
	}
	mock.lockCreateOrganization.RLock()
	calls = mock.calls.CreateOrganization
	mock.lockCreateOrganization.RUnlock()
	return calls
}

// CreateProject calls CreateProjectFunc.
func (mock *MockedOrgStorer) CreateProject(ctx context.Context, cp pgorg.CreateProject) (pgorg.Project, error) {
	if mock.CreateProjectFunc == nil {
		panic("MockedOrgStorer.CreateProjectFunc: method is nil but OrgStorer.CreateProject was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Cp  pgorg.CreateProject
	}{
		Ctx: ctx,
		Cp:  cp,
	}
	mock.lockCreateProject.Lock()
	mock.calls.CreateProject = append(mock.calls.CreateProject, callInfo)
	mock.lockCreateProject.Unlock()
	return mock.CreateProjectFunc(ctx, cp)
}

// CreateProjectCalls gets all the calls that were made to CreateProject.
// Check the length with:
//
//	len(mockedOrgStorer.CreateProjectCalls())
func (mock *MockedOrgStorer) CreateProjectCalls() []struct {
	Ctx context.Context
	Cp  pgorg.CreateProject
} {
	var calls []struct {
		Ctx context.Context
		Cp  pgorg.CreateProject
	}
	mock.lockCreateProject.RLock()
	calls = mock.calls.CreateProject
	mock.lockCreateProject.RUnlock()
	return calls
}

// OrganizationByName calls OrganizationByNameFunc.
func (mock *MockedOrgStorer) OrganizationByName(ctx context.Context, name string) (pgorg.Organization, error) {
	if mock.OrganizationByNameFunc == nil {
		panic("MockedOrgStorer.OrganizationByNameFunc: method is nil but OrgStorer.OrganizationByName was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Name string
	}{
		Ctx:  ctx,
		Name: name,
	}
	mock.lockOrganizationByName.Lock()
	mock.calls.OrganizationByName = append(mock.calls.OrganizationByName, callInfo)
	mock.lockOrganizationByName.Unlock()
	return mock.OrganizationByNameFunc(ctx, name)
}

// OrganizationByNameCalls gets all the calls that were made to OrganizationByName.
// Check the length with:
//
//	len(mockedOrgStorer.OrganizationByNameCalls())
func (mock *MockedOrgStorer) OrganizationByNameCalls() []struct {
	Ctx  context.Context
	Name string
} {
	var calls []struct {
		Ctx  context.Context
		Name string
	}
	mock.lockOrganizationByName.RLock()
	calls = mock.calls.OrganizationByName
	mock.lockOrganizationByName.RUnlock()
	return calls
}

// ProjectByName calls ProjectByNameFunc.
func (mock *MockedOrgStorer) ProjectByName(ctx context.Context, orgID int, name string) (pgorg.Project, error) {
	if mock.ProjectByNameFunc == nil {
		panic("MockedOrgStorer.ProjectByNameFunc: method is nil but OrgStorer.ProjectByName was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		OrgID int
		Name  string
	}{
		Ctx:   ctx,
		OrgID: orgID,
		Name:  name,
	}
	mock.lockProjectByName.Lock()
	mock.calls.ProjectByName = append(mock.calls.ProjectByName, callInfo)
	mock.lockProjectByName.Unlock()
	return mock.ProjectByNameFunc(ctx, orgID, name)
}

// ProjectByNameCalls gets all the calls that were made to ProjectByName.
// Check the length with:
//
//	len(mockedOrgStorer.ProjectByNameCalls())
func (mock *MockedOrgStorer) ProjectByNameCalls() []struct {
	Ctx   context.Context
	OrgID int
	Name  string
} {
	var calls []struct {
		Ctx   context.Context
		OrgID int
		Name  string
	}
	mock.lockProjectByName.RLock()
	calls = mock.calls.ProjectByName
	mock.lockProjectByName.RUnlock()
	return calls
}
