// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package org

import (
	"context"
	"sync"

	"github.com/google/uuid"
	"github.com/zorcal/theapp/backend/internal/core/pgstores/pgorg"
	"github.com/zorcal/theapp/backend/internal/core/pgstores/pgrbac"
)

// Ensure, that MockedOrgStorer does implement OrgStorer.
// If this is not the case, regenerate this file with moq.
var _ OrgStorer = &MockedOrgStorer{}

// MockedOrgStorer is a mock implementation of OrgStorer.
//
//	func TestSomethingThatUsesOrgStorer(t *testing.T) {
//
//		// make and configure a mocked OrgStorer
//		mockedOrgStorer := &MockedOrgStorer{
//			AccessibleProjectsFunc: func(ctx context.Context, userID uuid.UUID, filter pgorg.ProjectFilter, pageSize int, pageOffset int) ([]pgorg.Project, int, error) {
//				panic("mock out the AccessibleProjects method")
//			},
//			AddOrganizationMemberFunc: func(ctx context.Context, userID uuid.UUID, orgID int) error {
//				panic("mock out the AddOrganizationMember method")
//			},
//			CreateOrganizationFunc: func(ctx context.Context, co pgorg.CreateOrganization) (pgorg.Organization, error) {
//				panic("mock out the CreateOrganization method")
//			},
//			CreateProjectFunc: func(ctx context.Context, cp pgorg.CreateProject) (pgorg.Project, error) {
//				panic("mock out the CreateProject method")
//			},
//			IsOrganizationMemberFunc: func(ctx context.Context, userID uuid.UUID, orgID int) (bool, error) {
//				panic("mock out the IsOrganizationMember method")
//			},
//			OrganizationByNameFunc: func(ctx context.Context, name string) (pgorg.Organization, error) {
//				panic("mock out the OrganizationByName method")
//			},
//			ProjectByNameFunc: func(ctx context.Context, orgID int, name string) (pgorg.Project, error) {
//				panic("mock out the ProjectByName method")
//			},
//		}
//
//		// use mockedOrgStorer in code that requires OrgStorer
//		// and then make assertions.
//
//	}
type MockedOrgStorer struct {
	// AccessibleProjectsFunc mocks the AccessibleProjects method.
	AccessibleProjectsFunc func(ctx context.Context, userID uuid.UUID, filter pgorg.ProjectFilter, pageSize int, pageOffset int) ([]pgorg.Project, int, error)

	// AddOrganizationMemberFunc mocks the AddOrganizationMember method.
	AddOrganizationMemberFunc func(ctx context.Context, userID uuid.UUID, orgID int) error

	// CreateOrganizationFunc mocks the CreateOrganization method.
	CreateOrganizationFunc func(ctx context.Context, co pgorg.CreateOrganization) (pgorg.Organization, error)

	// CreateProjectFunc mocks the CreateProject method.
	CreateProjectFunc func(ctx context.Context, cp pgorg.CreateProject) (pgorg.Project, error)

	// IsOrganizationMemberFunc mocks the IsOrganizationMember method.
	IsOrganizationMemberFunc func(ctx context.Context, userID uuid.UUID, orgID int) (bool, error)

	// OrganizationByNameFunc mocks the OrganizationByName method.
	OrganizationByNameFunc func(ctx context.Context, name string) (pgorg.Organization, error)

	// ProjectByNameFunc mocks the ProjectByName method.
	ProjectByNameFunc func(ctx context.Context, orgID int, name string) (pgorg.Project, error)

	// calls tracks calls to the methods.
	calls struct {
		// AccessibleProjects holds details about calls to the AccessibleProjects method.
		AccessibleProjects []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID uuid.UUID
			// Filter is the filter argument value.
			Filter pgorg.ProjectFilter
			// PageSize is the pageSize argument value.
			PageSize int
			// PageOffset is the pageOffset argument value.
			PageOffset int
		}
		// AddOrganizationMember holds details about calls to the AddOrganizationMember method.
		AddOrganizationMember []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID uuid.UUID
			// OrgID is the orgID argument value.
			OrgID int
		}
		// CreateOrganization holds details about calls to the CreateOrganization method.
		CreateOrganization []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Co is the co argument value.
			Co pgorg.CreateOrganization
		}
		// CreateProject holds details about calls to the CreateProject method.
		CreateProject []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Cp is the cp argument value.
			Cp pgorg.CreateProject
		}
		// IsOrganizationMember holds details about calls to the IsOrganizationMember method.
		IsOrganizationMember []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID uuid.UUID
			// OrgID is the orgID argument value.
			OrgID int
		}
		// OrganizationByName holds details about calls to the OrganizationByName method.
		OrganizationByName []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
		}
		// ProjectByName holds details about calls to the ProjectByName method.
		ProjectByName []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgID is the orgID argument value.
			OrgID int
			// Name is the name argument value.
			Name string
		}
	}
	lockAccessibleProjects    sync.RWMutex
	lockAddOrganizationMember sync.RWMutex
	lockCreateOrganization    sync.RWMutex
	lockCreateProject         sync.RWMutex
	lockIsOrganizationMember  sync.RWMutex
	lockOrganizationByName    sync.RWMutex
	lockProjectByName         sync.RWMutex
}

// AccessibleProjects calls AccessibleProjectsFunc.
func (mock *MockedOrgStorer) AccessibleProjects(ctx context.Context, userID uuid.UUID, filter pgorg.ProjectFilter, pageSize int, pageOffset int) ([]pgorg.Project, int, error) {
	if mock.AccessibleProjectsFunc == nil {
		panic("MockedOrgStorer.AccessibleProjectsFunc: method is nil but OrgStorer.AccessibleProjects was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		UserID     uuid.UUID
		Filter     pgorg.ProjectFilter
		PageSize   int
		PageOffset int
	}{
		Ctx:        ctx,
		UserID:     userID,
		Filter:     filter,
		PageSize:   pageSize,
		PageOffset: pageOffset,
	}
	mock.lockAccessibleProjects.Lock()
	mock.calls.AccessibleProjects = append(mock.calls.AccessibleProjects, callInfo)
	mock.lockAccessibleProjects.Unlock()
	return mock.AccessibleProjectsFunc(ctx, userID, filter, pageSize, pageOffset)
}

// AccessibleProjectsCalls gets all the calls that were made to AccessibleProjects.
// Check the length with:
//
//	len(mockedOrgStorer.AccessibleProjectsCalls())
func (mock *MockedOrgStorer) AccessibleProjectsCalls() []struct {
	Ctx        context.Context
	UserID     uuid.UUID
	Filter     pgorg.ProjectFilter
	PageSize   int
	PageOffset int
} {
	var calls []struct {
		Ctx        context.Context
		UserID     uuid.UUID
		Filter     pgorg.ProjectFilter
		PageSize   int
		PageOffset int
	}
	mock.lockAccessibleProjects.RLock()
	calls = mock.calls.AccessibleProjects
	mock.lockAccessibleProjects.RUnlock()
	return calls
}

// AddOrganizationMember calls AddOrganizationMemberFunc.
func (mock *MockedOrgStorer) AddOrganizationMember(ctx context.Context, userID uuid.UUID, orgID int) error {
	if mock.AddOrganizationMemberFunc == nil {
		panic("MockedOrgStorer.AddOrganizationMemberFunc: method is nil but OrgStorer.AddOrganizationMember was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID uuid.UUID
		OrgID  int
	}{
		Ctx:    ctx,
		UserID: userID,
		OrgID:  orgID,
	}
	mock.lockAddOrganizationMember.Lock()
	mock.calls.AddOrganizationMember = append(mock.calls.AddOrganizationMember, callInfo)
	mock.lockAddOrganizationMember.Unlock()
	return mock.AddOrganizationMemberFunc(ctx, userID, orgID)
}

// AddOrganizationMemberCalls gets all the calls that were made to AddOrganizationMember.
// Check the length with:
//
//	len(mockedOrgStorer.AddOrganizationMemberCalls())
func (mock *MockedOrgStorer) AddOrganizationMemberCalls() []struct {
	Ctx    context.Context
	UserID uuid.UUID
	OrgID  int
} {
	var calls []struct {
		Ctx    context.Context
		UserID uuid.UUID
		OrgID  int
	}
	mock.lockAddOrganizationMember.RLock()
	calls = mock.calls.AddOrganizationMember
	mock.lockAddOrganizationMember.RUnlock()
	return calls
}

// CreateOrganization calls CreateOrganizationFunc.
func (mock *MockedOrgStorer) CreateOrganization(ctx context.Context, co pgorg.CreateOrganization) (pgorg.Organization, error) {
	if mock.CreateOrganizationFunc == nil {
		panic("MockedOrgStorer.CreateOrganizationFunc: method is nil but OrgStorer.CreateOrganization was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Co  pgorg.CreateOrganization
	}{
		Ctx: ctx,
		Co:  co,
	}
	mock.lockCreateOrganization.Lock()
	mock.calls.CreateOrganization = append(mock.calls.CreateOrganization, callInfo)
	mock.lockCreateOrganization.Unlock()
	return mock.CreateOrganizationFunc(ctx, co)
}

// CreateOrganizationCalls gets all the calls that were made to CreateOrganization.
// Check the length with:
//
//	len(mockedOrgStorer.CreateOrganizationCalls())
func (mock *MockedOrgStorer) CreateOrganizationCalls() []struct {
	Ctx context.Context
	Co  pgorg.CreateOrganization
} {
	var calls []struct {
		Ctx context.Context
		Co  pgorg.CreateOrganization
	}
	mock.lockCreateOrganization.RLock()
	calls = mock.calls.CreateOrganization
	mock.lockCreateOrganization.RUnlock()
	return calls
}

// CreateProject calls CreateProjectFunc.
func (mock *MockedOrgStorer) CreateProject(ctx context.Context, cp pgorg.CreateProject) (pgorg.Project, error) {
	if mock.CreateProjectFunc == nil {
		panic("MockedOrgStorer.CreateProjectFunc: method is nil but OrgStorer.CreateProject was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Cp  pgorg.CreateProject
	}{
		Ctx: ctx,
		Cp:  cp,
	}
	mock.lockCreateProject.Lock()
	mock.calls.CreateProject = append(mock.calls.CreateProject, callInfo)
	mock.lockCreateProject.Unlock()
	return mock.CreateProjectFunc(ctx, cp)
}

// CreateProjectCalls gets all the calls that were made to CreateProject.
// Check the length with:
//
//	len(mockedOrgStorer.CreateProjectCalls())
func (mock *MockedOrgStorer) CreateProjectCalls() []struct {
	Ctx context.Context
	Cp  pgorg.CreateProject
} {
	var calls []struct {
		Ctx context.Context
		Cp  pgorg.CreateProject
	}
	mock.lockCreateProject.RLock()
	calls = mock.calls.CreateProject
	mock.lockCreateProject.RUnlock()
	return calls
}

// IsOrganizationMember calls IsOrganizationMemberFunc.
func (mock *MockedOrgStorer) IsOrganizationMember(ctx context.Context, userID uuid.UUID, orgID int) (bool, error) {
	if mock.IsOrganizationMemberFunc == nil {
		panic("MockedOrgStorer.IsOrganizationMemberFunc: method is nil but OrgStorer.IsOrganizationMember was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID uuid.UUID
		OrgID  int
	}{
		Ctx:    ctx,
		UserID: userID,
		OrgID:  orgID,
	}
	mock.lockIsOrganizationMember.Lock()
	mock.calls.IsOrganizationMember = append(mock.calls.IsOrganizationMember, callInfo)
	mock.lockIsOrganizationMember.Unlock()
	return mock.IsOrganizationMemberFunc(ctx, userID, orgID)
}

// IsOrganizationMemberCalls gets all the calls that were made to IsOrganizationMember.
// Check the length with:
//
//	len(mockedOrgStorer.IsOrganizationMemberCalls())
func (mock *MockedOrgStorer) IsOrganizationMemberCalls() []struct {
	Ctx    context.Context
	UserID uuid.UUID
	OrgID  int
} {
	var calls []struct {
		Ctx    context.Context
		UserID uuid.UUID
		OrgID  int
	}
	mock.lockIsOrganizationMember.RLock()
	calls = mock.calls.IsOrganizationMember
	mock.lockIsOrganizationMember.RUnlock()
	return calls
}

// OrganizationByName calls OrganizationByNameFunc.
func (mock *MockedOrgStorer) OrganizationByName(ctx context.Context, name string) (pgorg.Organization, error) {
	if mock.OrganizationByNameFunc == nil {
		panic("MockedOrgStorer.OrganizationByNameFunc: method is nil but OrgStorer.OrganizationByName was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Name string
	}{
		Ctx:  ctx,
		Name: name,
	}
	mock.lockOrganizationByName.Lock()
	mock.calls.OrganizationByName = append(mock.calls.OrganizationByName, callInfo)
	mock.lockOrganizationByName.Unlock()
	return mock.OrganizationByNameFunc(ctx, name)
}

// OrganizationByNameCalls gets all the calls that were made to OrganizationByName.
// Check the length with:
//
//	len(mockedOrgStorer.OrganizationByNameCalls())
func (mock *MockedOrgStorer) OrganizationByNameCalls() []struct {
	Ctx  context.Context
	Name string
} {
	var calls []struct {
		Ctx  context.Context
		Name string
	}
	mock.lockOrganizationByName.RLock()
	calls = mock.calls.OrganizationByName
	mock.lockOrganizationByName.RUnlock()
	return calls
}

// ProjectByName calls ProjectByNameFunc.
func (mock *MockedOrgStorer) ProjectByName(ctx context.Context, orgID int, name string) (pgorg.Project, error) {
	if mock.ProjectByNameFunc == nil {
		panic("MockedOrgStorer.ProjectByNameFunc: method is nil but OrgStorer.ProjectByName was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		OrgID int
		Name  string
	}{
		Ctx:   ctx,
		OrgID: orgID,
		Name:  name,
	}
	mock.lockProjectByName.Lock()
	mock.calls.ProjectByName = append(mock.calls.ProjectByName, callInfo)
	mock.lockProjectByName.Unlock()
	return mock.ProjectByNameFunc(ctx, orgID, name)
}

// ProjectByNameCalls gets all the calls that were made to ProjectByName.
// Check the length with:
//
//	len(mockedOrgStorer.ProjectByNameCalls())
func (mock *MockedOrgStorer) ProjectByNameCalls() []struct {
	Ctx   context.Context
	OrgID int
	Name  string
} {
	var calls []struct {
		Ctx   context.Context
		OrgID int
		Name  string
	}
	mock.lockProjectByName.RLock()
	calls = mock.calls.ProjectByName
	mock.lockProjectByName.RUnlock()
	return calls
}

// Ensure, that MockedRoleBootstrapperStore does implement RoleBootstrapperStore.
// If this is not the case, regenerate this file with moq.
var _ RoleBootstrapperStore = &MockedRoleBootstrapperStore{}

// MockedRoleBootstrapperStore is a mock implementation of RoleBootstrapperStore.
//
//	func TestSomethingThatUsesRoleBootstrapperStore(t *testing.T) {
//
//		// make and configure a mocked RoleBootstrapperStore
//		mockedRoleBootstrapperStore := &MockedRoleBootstrapperStore{
//			AssignCustomRoleToOrgFunc: func(ctx context.Context, userID uuid.UUID, roleID uuid.UUID, orgID int) error {
//				panic("mock out the AssignCustomRoleToOrg method")
//			},
//			CreateOrganizationAdminRoleFunc: func(ctx context.Context, orgID int, permissionNames []string) (pgrbac.CustomRole, error) {
//				panic("mock out the CreateOrganizationAdminRole method")
//			},
//		}
//
//		// use mockedRoleBootstrapperStore in code that requires RoleBootstrapperStore
//		// and then make assertions.
//
//	}
type MockedRoleBootstrapperStore struct {
	// AssignCustomRoleToOrgFunc mocks the AssignCustomRoleToOrg method.
	AssignCustomRoleToOrgFunc func(ctx context.Context, userID uuid.UUID, roleID uuid.UUID, orgID int) error

	// CreateOrganizationAdminRoleFunc mocks the CreateOrganizationAdminRole method.
	CreateOrganizationAdminRoleFunc func(ctx context.Context, orgID int, permissionNames []string) (pgrbac.CustomRole, error)

	// calls tracks calls to the methods.
	calls struct {
		// AssignCustomRoleToOrg holds details about calls to the AssignCustomRoleToOrg method.
		AssignCustomRoleToOrg []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID uuid.UUID
			// RoleID is the roleID argument value.
			RoleID uuid.UUID
			// OrgID is the orgID argument value.
			OrgID int
		}
		// CreateOrganizationAdminRole holds details about calls to the CreateOrganizationAdminRole method.
		CreateOrganizationAdminRole []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgID is the orgID argument value.
			OrgID int
			// PermissionNames is the permissionNames argument value.
			PermissionNames []string
		}
	}
	lockAssignCustomRoleToOrg       sync.RWMutex
	lockCreateOrganizationAdminRole sync.RWMutex
}

// AssignCustomRoleToOrg calls AssignCustomRoleToOrgFunc.
func (mock *MockedRoleBootstrapperStore) AssignCustomRoleToOrg(ctx context.Context, userID uuid.UUID, roleID uuid.UUID, orgID int) error {
	if mock.AssignCustomRoleToOrgFunc == nil {
		panic("MockedRoleBootstrapperStore.AssignCustomRoleToOrgFunc: method is nil but RoleBootstrapperStore.AssignCustomRoleToOrg was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID uuid.UUID
		RoleID uuid.UUID
		OrgID  int
	}{
		Ctx:    ctx,
		UserID: userID,
		RoleID: roleID,
		OrgID:  orgID,
	}
	mock.lockAssignCustomRoleToOrg.Lock()
	mock.calls.AssignCustomRoleToOrg = append(mock.calls.AssignCustomRoleToOrg, callInfo)
	mock.lockAssignCustomRoleToOrg.Unlock()
	return mock.AssignCustomRoleToOrgFunc(ctx, userID, roleID, orgID)
}

// AssignCustomRoleToOrgCalls gets all the calls that were made to AssignCustomRoleToOrg.
// Check the length with:
//
//	len(mockedRoleBootstrapperStore.AssignCustomRoleToOrgCalls())
func (mock *MockedRoleBootstrapperStore) AssignCustomRoleToOrgCalls() []struct {
	Ctx    context.Context
	UserID uuid.UUID
	RoleID uuid.UUID
	OrgID  int
} {
	var calls []struct {
		Ctx    context.Context
		UserID uuid.UUID
		RoleID uuid.UUID
		OrgID  int
	}
	mock.lockAssignCustomRoleToOrg.RLock()
	calls = mock.calls.AssignCustomRoleToOrg
	mock.lockAssignCustomRoleToOrg.RUnlock()
	return calls
}

// CreateOrganizationAdminRole calls CreateOrganizationAdminRoleFunc.
func (mock *MockedRoleBootstrapperStore) CreateOrganizationAdminRole(ctx context.Context, orgID int, permissionNames []string) (pgrbac.CustomRole, error) {
	if mock.CreateOrganizationAdminRoleFunc == nil {
		panic("MockedRoleBootstrapperStore.CreateOrganizationAdminRoleFunc: method is nil but RoleBootstrapperStore.CreateOrganizationAdminRole was just called")
	}
	callInfo := struct {
		Ctx             context.Context
		OrgID           int
		PermissionNames []string
	}{
		Ctx:             ctx,
		OrgID:           orgID,
		PermissionNames: permissionNames,
	}
	mock.lockCreateOrganizationAdminRole.Lock()
	mock.calls.CreateOrganizationAdminRole = append(mock.calls.CreateOrganizationAdminRole, callInfo)
	mock.lockCreateOrganizationAdminRole.Unlock()
	return mock.CreateOrganizationAdminRoleFunc(ctx, orgID, permissionNames)
}

// CreateOrganizationAdminRoleCalls gets all the calls that were made to CreateOrganizationAdminRole.
// Check the length with:
//
//	len(mockedRoleBootstrapperStore.CreateOrganizationAdminRoleCalls())
func (mock *MockedRoleBootstrapperStore) CreateOrganizationAdminRoleCalls() []struct {
	Ctx             context.Context
	OrgID           int
	PermissionNames []string
} {
	var calls []struct {
		Ctx             context.Context
		OrgID           int
		PermissionNames []string
	}
	mock.lockCreateOrganizationAdminRole.RLock()
	calls = mock.calls.CreateOrganizationAdminRole
	mock.lockCreateOrganizationAdminRole.RUnlock()
	return calls
}
