#!/usr/bin/env bash

root=$(git rev-parse --show-toplevel)
backend="$root/backend"

# Uses tool defined in go.mod.
tool="google.golang.org/protobuf/cmd/protoc-gen-go"
bin="$(cd "$backend" && go tool -n "$tool")"
exec "${bin}"
