// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package rbac

import (
	"context"
	"sync"

	"github.com/zorcal/theapp/backend/internal/core/pgstores/pgorg"
)

// Ensure, that MockedOrgStorer does implement OrgStorer.
// If this is not the case, regenerate this file with moq.
var _ OrgStorer = &MockedOrgStorer{}

// MockedOrgStorer is a mock implementation of OrgStorer.
//
//	func TestSomethingThatUsesOrgStorer(t *testing.T) {
//
//		// make and configure a mocked OrgStorer
//		mockedOrgStorer := &MockedOrgStorer{
//			IsOrgMemberFunc: func(ctx context.Context, userID int, orgID int) (bool, error) {
//				panic("mock out the IsOrgMember method")
//			},
//			ProjectByIDFunc: func(ctx context.Context, id int) (pgorg.Project, error) {
//				panic("mock out the ProjectByID method")
//			},
//		}
//
//		// use mockedOrgStorer in code that requires OrgStorer
//		// and then make assertions.
//
//	}
type MockedOrgStorer struct {
	// IsOrgMemberFunc mocks the IsOrgMember method.
	IsOrgMemberFunc func(ctx context.Context, userID int, orgID int) (bool, error)

	// ProjectByIDFunc mocks the ProjectByID method.
	ProjectByIDFunc func(ctx context.Context, id int) (pgorg.Project, error)

	// calls tracks calls to the methods.
	calls struct {
		// IsOrgMember holds details about calls to the IsOrgMember method.
		IsOrgMember []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID int
			// OrgID is the orgID argument value.
			OrgID int
		}
		// ProjectByID holds details about calls to the ProjectByID method.
		ProjectByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int
		}
	}
	lockIsOrgMember sync.RWMutex
	lockProjectByID sync.RWMutex
}

// IsOrgMember calls IsOrgMemberFunc.
func (mock *MockedOrgStorer) IsOrgMember(ctx context.Context, userID int, orgID int) (bool, error) {
	if mock.IsOrgMemberFunc == nil {
		panic("MockedOrgStorer.IsOrgMemberFunc: method is nil but OrgStorer.IsOrgMember was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID int
		OrgID  int
	}{
		Ctx:    ctx,
		UserID: userID,
		OrgID:  orgID,
	}
	mock.lockIsOrgMember.Lock()
	mock.calls.IsOrgMember = append(mock.calls.IsOrgMember, callInfo)
	mock.lockIsOrgMember.Unlock()
	return mock.IsOrgMemberFunc(ctx, userID, orgID)
}

// IsOrgMemberCalls gets all the calls that were made to IsOrgMember.
// Check the length with:
//
//	len(mockedOrgStorer.IsOrgMemberCalls())
func (mock *MockedOrgStorer) IsOrgMemberCalls() []struct {
	Ctx    context.Context
	UserID int
	OrgID  int
} {
	var calls []struct {
		Ctx    context.Context
		UserID int
		OrgID  int
	}
	mock.lockIsOrgMember.RLock()
	calls = mock.calls.IsOrgMember
	mock.lockIsOrgMember.RUnlock()
	return calls
}

// ProjectByID calls ProjectByIDFunc.
func (mock *MockedOrgStorer) ProjectByID(ctx context.Context, id int) (pgorg.Project, error) {
	if mock.ProjectByIDFunc == nil {
		panic("MockedOrgStorer.ProjectByIDFunc: method is nil but OrgStorer.ProjectByID was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockProjectByID.Lock()
	mock.calls.ProjectByID = append(mock.calls.ProjectByID, callInfo)
	mock.lockProjectByID.Unlock()
	return mock.ProjectByIDFunc(ctx, id)
}

// ProjectByIDCalls gets all the calls that were made to ProjectByID.
// Check the length with:
//
//	len(mockedOrgStorer.ProjectByIDCalls())
func (mock *MockedOrgStorer) ProjectByIDCalls() []struct {
	Ctx context.Context
	ID  int
} {
	var calls []struct {
		Ctx context.Context
		ID  int
	}
	mock.lockProjectByID.RLock()
	calls = mock.calls.ProjectByID
	mock.lockProjectByID.RUnlock()
	return calls
}
