// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package rbac

import (
	"context"
	"sync"

	"github.com/zorcal/theapp/backend/internal/core/pgstores/pgrbac"
)

// Ensure, that MockedRoleStorer does implement RoleStorer.
// If this is not the case, regenerate this file with moq.
var _ RoleStorer = &MockedRoleStorer{}

// MockedRoleStorer is a mock implementation of RoleStorer.
//
//	func TestSomethingThatUsesRoleStorer(t *testing.T) {
//
//		// make and configure a mocked RoleStorer
//		mockedRoleStorer := &MockedRoleStorer{
//			AssignSystemRoleFunc: func(ctx context.Context, userID int, roleName string) error {
//				panic("mock out the AssignSystemRole method")
//			},
//			RolesFunc: func(ctx context.Context) ([]pgrbac.Role, error) {
//				panic("mock out the Roles method")
//			},
//		}
//
//		// use mockedRoleStorer in code that requires RoleStorer
//		// and then make assertions.
//
//	}
type MockedRoleStorer struct {
	// AssignSystemRoleFunc mocks the AssignSystemRole method.
	AssignSystemRoleFunc func(ctx context.Context, userID int, roleName string) error

	// RolesFunc mocks the Roles method.
	RolesFunc func(ctx context.Context) ([]pgrbac.Role, error)

	// calls tracks calls to the methods.
	calls struct {
		// AssignSystemRole holds details about calls to the AssignSystemRole method.
		AssignSystemRole []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID int
			// RoleName is the roleName argument value.
			RoleName string
		}
		// Roles holds details about calls to the Roles method.
		Roles []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockAssignSystemRole sync.RWMutex
	lockRoles            sync.RWMutex
}

// AssignSystemRole calls AssignSystemRoleFunc.
func (mock *MockedRoleStorer) AssignSystemRole(ctx context.Context, userID int, roleName string) error {
	if mock.AssignSystemRoleFunc == nil {
		panic("MockedRoleStorer.AssignSystemRoleFunc: method is nil but RoleStorer.AssignSystemRole was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		UserID   int
		RoleName string
	}{
		Ctx:      ctx,
		UserID:   userID,
		RoleName: roleName,
	}
	mock.lockAssignSystemRole.Lock()
	mock.calls.AssignSystemRole = append(mock.calls.AssignSystemRole, callInfo)
	mock.lockAssignSystemRole.Unlock()
	return mock.AssignSystemRoleFunc(ctx, userID, roleName)
}

// AssignSystemRoleCalls gets all the calls that were made to AssignSystemRole.
// Check the length with:
//
//	len(mockedRoleStorer.AssignSystemRoleCalls())
func (mock *MockedRoleStorer) AssignSystemRoleCalls() []struct {
	Ctx      context.Context
	UserID   int
	RoleName string
} {
	var calls []struct {
		Ctx      context.Context
		UserID   int
		RoleName string
	}
	mock.lockAssignSystemRole.RLock()
	calls = mock.calls.AssignSystemRole
	mock.lockAssignSystemRole.RUnlock()
	return calls
}

// Roles calls RolesFunc.
func (mock *MockedRoleStorer) Roles(ctx context.Context) ([]pgrbac.Role, error) {
	if mock.RolesFunc == nil {
		panic("MockedRoleStorer.RolesFunc: method is nil but RoleStorer.Roles was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockRoles.Lock()
	mock.calls.Roles = append(mock.calls.Roles, callInfo)
	mock.lockRoles.Unlock()
	return mock.RolesFunc(ctx)
}

// RolesCalls gets all the calls that were made to Roles.
// Check the length with:
//
//	len(mockedRoleStorer.RolesCalls())
func (mock *MockedRoleStorer) RolesCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockRoles.RLock()
	calls = mock.calls.Roles
	mock.lockRoles.RUnlock()
	return calls
}
