// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package rbac

import (
	"context"
	"sync"

	"github.com/google/uuid"
	"github.com/zorcal/theapp/backend/internal/core/pgstores/pgrbac"
)

// Ensure, that MockedRoleStorer does implement RoleStorer.
// If this is not the case, regenerate this file with moq.
var _ RoleStorer = &MockedRoleStorer{}

// MockedRoleStorer is a mock implementation of RoleStorer.
//
//	func TestSomethingThatUsesRoleStorer(t *testing.T) {
//
//		// make and configure a mocked RoleStorer
//		mockedRoleStorer := &MockedRoleStorer{
//			AssignCustomRoleToOrgFunc: func(ctx context.Context, userID uuid.UUID, roleID uuid.UUID, orgID int) error {
//				panic("mock out the AssignCustomRoleToOrg method")
//			},
//			AssignCustomRoleToProjectFunc: func(ctx context.Context, userID uuid.UUID, roleID uuid.UUID, projectID int) error {
//				panic("mock out the AssignCustomRoleToProject method")
//			},
//			AssignSystemRoleFunc: func(ctx context.Context, userID uuid.UUID, roleName string) error {
//				panic("mock out the AssignSystemRole method")
//			},
//			CreateCustomRoleFunc: func(ctx context.Context, cr pgrbac.CreateCustomRole) (pgrbac.CustomRole, error) {
//				panic("mock out the CreateCustomRole method")
//			},
//			CustomRoleByExternalIDFunc: func(ctx context.Context, orgID int, roleID uuid.UUID) (pgrbac.CustomRole, error) {
//				panic("mock out the CustomRoleByExternalID method")
//			},
//			CustomRolesFunc: func(ctx context.Context, orgID int, pageSize int, pageOffset int) ([]pgrbac.CustomRole, int, error) {
//				panic("mock out the CustomRoles method")
//			},
//			DeleteCustomRoleFunc: func(ctx context.Context, orgID int, roleID uuid.UUID) error {
//				panic("mock out the DeleteCustomRole method")
//			},
//			FullyPrivilegedUserRemainsAfterSystemRoleUnassignFunc: func(ctx context.Context, userID uuid.UUID, roleName string) (bool, error) {
//				panic("mock out the FullyPrivilegedUserRemainsAfterSystemRoleUnassign method")
//			},
//			LockSystemRoleManagementFunc: func(ctx context.Context) error {
//				panic("mock out the LockSystemRoleManagement method")
//			},
//			LockSystemRoleUserFunc: func(ctx context.Context, userID uuid.UUID) error {
//				panic("mock out the LockSystemRoleUser method")
//			},
//			ModifyCustomRolePermissionsFunc: func(ctx context.Context, mp pgrbac.ModifyCustomRolePermissions) (pgrbac.CustomRole, error) {
//				panic("mock out the ModifyCustomRolePermissions method")
//			},
//			OrgPermissionsByProjectIDFunc: func(ctx context.Context, userID uuid.UUID, projectID int) (pgrbac.OrgPermissions, error) {
//				panic("mock out the OrgPermissionsByProjectID method")
//			},
//			ProjectPermissionsFunc: func(ctx context.Context, userID uuid.UUID, projectID int) (pgrbac.ProjectPermissions, error) {
//				panic("mock out the ProjectPermissions method")
//			},
//			SystemPermissionsFunc: func(ctx context.Context, userID uuid.UUID) ([]string, error) {
//				panic("mock out the SystemPermissions method")
//			},
//			SystemRoleByNameFunc: func(ctx context.Context, name string) (pgrbac.SystemRole, error) {
//				panic("mock out the SystemRoleByName method")
//			},
//			SystemRolesFunc: func(ctx context.Context, pageSize int, pageOffset int) ([]pgrbac.SystemRole, int, error) {
//				panic("mock out the SystemRoles method")
//			},
//			UnassignCustomRoleFromOrgFunc: func(ctx context.Context, userID uuid.UUID, roleID uuid.UUID, orgID int) error {
//				panic("mock out the UnassignCustomRoleFromOrg method")
//			},
//			UnassignCustomRoleFromProjectFunc: func(ctx context.Context, userID uuid.UUID, roleID uuid.UUID, projectID int) error {
//				panic("mock out the UnassignCustomRoleFromProject method")
//			},
//			UnassignSystemRoleFunc: func(ctx context.Context, userID uuid.UUID, roleName string) error {
//				panic("mock out the UnassignSystemRole method")
//			},
//			UpdateCustomRoleFunc: func(ctx context.Context, ur pgrbac.UpdateCustomRole) (pgrbac.CustomRole, error) {
//				panic("mock out the UpdateCustomRole method")
//			},
//			UserOrgCustomRolesFunc: func(ctx context.Context, userID uuid.UUID, orgID int, pageSize int, pageOffset int) ([]pgrbac.CustomRole, int, error) {
//				panic("mock out the UserOrgCustomRoles method")
//			},
//			UserProjectCustomRolesFunc: func(ctx context.Context, userID uuid.UUID, projectID int, pageSize int, pageOffset int) ([]pgrbac.CustomRole, int, error) {
//				panic("mock out the UserProjectCustomRoles method")
//			},
//			UserSystemRolesByExternalIDFunc: func(ctx context.Context, userID uuid.UUID, pageSize int, pageOffset int) ([]pgrbac.SystemRole, int, error) {
//				panic("mock out the UserSystemRolesByExternalID method")
//			},
//		}
//
//		// use mockedRoleStorer in code that requires RoleStorer
//		// and then make assertions.
//
//	}
type MockedRoleStorer struct {
	// AssignCustomRoleToOrgFunc mocks the AssignCustomRoleToOrg method.
	AssignCustomRoleToOrgFunc func(ctx context.Context, userID uuid.UUID, roleID uuid.UUID, orgID int) error

	// AssignCustomRoleToProjectFunc mocks the AssignCustomRoleToProject method.
	AssignCustomRoleToProjectFunc func(ctx context.Context, userID uuid.UUID, roleID uuid.UUID, projectID int) error

	// AssignSystemRoleFunc mocks the AssignSystemRole method.
	AssignSystemRoleFunc func(ctx context.Context, userID uuid.UUID, roleName string) error

	// CreateCustomRoleFunc mocks the CreateCustomRole method.
	CreateCustomRoleFunc func(ctx context.Context, cr pgrbac.CreateCustomRole) (pgrbac.CustomRole, error)

	// CustomRoleByExternalIDFunc mocks the CustomRoleByExternalID method.
	CustomRoleByExternalIDFunc func(ctx context.Context, orgID int, roleID uuid.UUID) (pgrbac.CustomRole, error)

	// CustomRolesFunc mocks the CustomRoles method.
	CustomRolesFunc func(ctx context.Context, orgID int, pageSize int, pageOffset int) ([]pgrbac.CustomRole, int, error)

	// DeleteCustomRoleFunc mocks the DeleteCustomRole method.
	DeleteCustomRoleFunc func(ctx context.Context, orgID int, roleID uuid.UUID) error

	// FullyPrivilegedUserRemainsAfterSystemRoleUnassignFunc mocks the FullyPrivilegedUserRemainsAfterSystemRoleUnassign method.
	FullyPrivilegedUserRemainsAfterSystemRoleUnassignFunc func(ctx context.Context, userID uuid.UUID, roleName string) (bool, error)

	// LockSystemRoleManagementFunc mocks the LockSystemRoleManagement method.
	LockSystemRoleManagementFunc func(ctx context.Context) error

	// LockSystemRoleUserFunc mocks the LockSystemRoleUser method.
	LockSystemRoleUserFunc func(ctx context.Context, userID uuid.UUID) error

	// ModifyCustomRolePermissionsFunc mocks the ModifyCustomRolePermissions method.
	ModifyCustomRolePermissionsFunc func(ctx context.Context, mp pgrbac.ModifyCustomRolePermissions) (pgrbac.CustomRole, error)

	// OrgPermissionsByProjectIDFunc mocks the OrgPermissionsByProjectID method.
	OrgPermissionsByProjectIDFunc func(ctx context.Context, userID uuid.UUID, projectID int) (pgrbac.OrgPermissions, error)

	// ProjectPermissionsFunc mocks the ProjectPermissions method.
	ProjectPermissionsFunc func(ctx context.Context, userID uuid.UUID, projectID int) (pgrbac.ProjectPermissions, error)

	// SystemPermissionsFunc mocks the SystemPermissions method.
	SystemPermissionsFunc func(ctx context.Context, userID uuid.UUID) ([]string, error)

	// SystemRoleByNameFunc mocks the SystemRoleByName method.
	SystemRoleByNameFunc func(ctx context.Context, name string) (pgrbac.SystemRole, error)

	// SystemRolesFunc mocks the SystemRoles method.
	SystemRolesFunc func(ctx context.Context, pageSize int, pageOffset int) ([]pgrbac.SystemRole, int, error)

	// UnassignCustomRoleFromOrgFunc mocks the UnassignCustomRoleFromOrg method.
	UnassignCustomRoleFromOrgFunc func(ctx context.Context, userID uuid.UUID, roleID uuid.UUID, orgID int) error

	// UnassignCustomRoleFromProjectFunc mocks the UnassignCustomRoleFromProject method.
	UnassignCustomRoleFromProjectFunc func(ctx context.Context, userID uuid.UUID, roleID uuid.UUID, projectID int) error

	// UnassignSystemRoleFunc mocks the UnassignSystemRole method.
	UnassignSystemRoleFunc func(ctx context.Context, userID uuid.UUID, roleName string) error

	// UpdateCustomRoleFunc mocks the UpdateCustomRole method.
	UpdateCustomRoleFunc func(ctx context.Context, ur pgrbac.UpdateCustomRole) (pgrbac.CustomRole, error)

	// UserOrgCustomRolesFunc mocks the UserOrgCustomRoles method.
	UserOrgCustomRolesFunc func(ctx context.Context, userID uuid.UUID, orgID int, pageSize int, pageOffset int) ([]pgrbac.CustomRole, int, error)

	// UserProjectCustomRolesFunc mocks the UserProjectCustomRoles method.
	UserProjectCustomRolesFunc func(ctx context.Context, userID uuid.UUID, projectID int, pageSize int, pageOffset int) ([]pgrbac.CustomRole, int, error)

	// UserSystemRolesByExternalIDFunc mocks the UserSystemRolesByExternalID method.
	UserSystemRolesByExternalIDFunc func(ctx context.Context, userID uuid.UUID, pageSize int, pageOffset int) ([]pgrbac.SystemRole, int, error)

	// calls tracks calls to the methods.
	calls struct {
		// AssignCustomRoleToOrg holds details about calls to the AssignCustomRoleToOrg method.
		AssignCustomRoleToOrg []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID uuid.UUID
			// RoleID is the roleID argument value.
			RoleID uuid.UUID
			// OrgID is the orgID argument value.
			OrgID int
		}
		// AssignCustomRoleToProject holds details about calls to the AssignCustomRoleToProject method.
		AssignCustomRoleToProject []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID uuid.UUID
			// RoleID is the roleID argument value.
			RoleID uuid.UUID
			// ProjectID is the projectID argument value.
			ProjectID int
		}
		// AssignSystemRole holds details about calls to the AssignSystemRole method.
		AssignSystemRole []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID uuid.UUID
			// RoleName is the roleName argument value.
			RoleName string
		}
		// CreateCustomRole holds details about calls to the CreateCustomRole method.
		CreateCustomRole []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Cr is the cr argument value.
			Cr pgrbac.CreateCustomRole
		}
		// CustomRoleByExternalID holds details about calls to the CustomRoleByExternalID method.
		CustomRoleByExternalID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgID is the orgID argument value.
			OrgID int
			// RoleID is the roleID argument value.
			RoleID uuid.UUID
		}
		// CustomRoles holds details about calls to the CustomRoles method.
		CustomRoles []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgID is the orgID argument value.
			OrgID int
			// PageSize is the pageSize argument value.
			PageSize int
			// PageOffset is the pageOffset argument value.
			PageOffset int
		}
		// DeleteCustomRole holds details about calls to the DeleteCustomRole method.
		DeleteCustomRole []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgID is the orgID argument value.
			OrgID int
			// RoleID is the roleID argument value.
			RoleID uuid.UUID
		}
		// FullyPrivilegedUserRemainsAfterSystemRoleUnassign holds details about calls to the FullyPrivilegedUserRemainsAfterSystemRoleUnassign method.
		FullyPrivilegedUserRemainsAfterSystemRoleUnassign []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID uuid.UUID
			// RoleName is the roleName argument value.
			RoleName string
		}
		// LockSystemRoleManagement holds details about calls to the LockSystemRoleManagement method.
		LockSystemRoleManagement []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// LockSystemRoleUser holds details about calls to the LockSystemRoleUser method.
		LockSystemRoleUser []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID uuid.UUID
		}
		// ModifyCustomRolePermissions holds details about calls to the ModifyCustomRolePermissions method.
		ModifyCustomRolePermissions []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Mp is the mp argument value.
			Mp pgrbac.ModifyCustomRolePermissions
		}
		// OrgPermissionsByProjectID holds details about calls to the OrgPermissionsByProjectID method.
		OrgPermissionsByProjectID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID uuid.UUID
			// ProjectID is the projectID argument value.
			ProjectID int
		}
		// ProjectPermissions holds details about calls to the ProjectPermissions method.
		ProjectPermissions []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID uuid.UUID
			// ProjectID is the projectID argument value.
			ProjectID int
		}
		// SystemPermissions holds details about calls to the SystemPermissions method.
		SystemPermissions []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID uuid.UUID
		}
		// SystemRoleByName holds details about calls to the SystemRoleByName method.
		SystemRoleByName []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
		}
		// SystemRoles holds details about calls to the SystemRoles method.
		SystemRoles []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// PageSize is the pageSize argument value.
			PageSize int
			// PageOffset is the pageOffset argument value.
			PageOffset int
		}
		// UnassignCustomRoleFromOrg holds details about calls to the UnassignCustomRoleFromOrg method.
		UnassignCustomRoleFromOrg []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID uuid.UUID
			// RoleID is the roleID argument value.
			RoleID uuid.UUID
			// OrgID is the orgID argument value.
			OrgID int
		}
		// UnassignCustomRoleFromProject holds details about calls to the UnassignCustomRoleFromProject method.
		UnassignCustomRoleFromProject []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID uuid.UUID
			// RoleID is the roleID argument value.
			RoleID uuid.UUID
			// ProjectID is the projectID argument value.
			ProjectID int
		}
		// UnassignSystemRole holds details about calls to the UnassignSystemRole method.
		UnassignSystemRole []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID uuid.UUID
			// RoleName is the roleName argument value.
			RoleName string
		}
		// UpdateCustomRole holds details about calls to the UpdateCustomRole method.
		UpdateCustomRole []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Ur is the ur argument value.
			Ur pgrbac.UpdateCustomRole
		}
		// UserOrgCustomRoles holds details about calls to the UserOrgCustomRoles method.
		UserOrgCustomRoles []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID uuid.UUID
			// OrgID is the orgID argument value.
			OrgID int
			// PageSize is the pageSize argument value.
			PageSize int
			// PageOffset is the pageOffset argument value.
			PageOffset int
		}
		// UserProjectCustomRoles holds details about calls to the UserProjectCustomRoles method.
		UserProjectCustomRoles []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID uuid.UUID
			// ProjectID is the projectID argument value.
			ProjectID int
			// PageSize is the pageSize argument value.
			PageSize int
			// PageOffset is the pageOffset argument value.
			PageOffset int
		}
		// UserSystemRolesByExternalID holds details about calls to the UserSystemRolesByExternalID method.
		UserSystemRolesByExternalID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID uuid.UUID
			// PageSize is the pageSize argument value.
			PageSize int
			// PageOffset is the pageOffset argument value.
			PageOffset int
		}
	}
	lockAssignCustomRoleToOrg                             sync.RWMutex
	lockAssignCustomRoleToProject                         sync.RWMutex
	lockAssignSystemRole                                  sync.RWMutex
	lockCreateCustomRole                                  sync.RWMutex
	lockCustomRoleByExternalID                            sync.RWMutex
	lockCustomRoles                                       sync.RWMutex
	lockDeleteCustomRole                                  sync.RWMutex
	lockFullyPrivilegedUserRemainsAfterSystemRoleUnassign sync.RWMutex
	lockLockSystemRoleManagement                          sync.RWMutex
	lockLockSystemRoleUser                                sync.RWMutex
	lockModifyCustomRolePermissions                       sync.RWMutex
	lockOrgPermissionsByProjectID                         sync.RWMutex
	lockProjectPermissions                                sync.RWMutex
	lockSystemPermissions                                 sync.RWMutex
	lockSystemRoleByName                                  sync.RWMutex
	lockSystemRoles                                       sync.RWMutex
	lockUnassignCustomRoleFromOrg                         sync.RWMutex
	lockUnassignCustomRoleFromProject                     sync.RWMutex
	lockUnassignSystemRole                                sync.RWMutex
	lockUpdateCustomRole                                  sync.RWMutex
	lockUserOrgCustomRoles                                sync.RWMutex
	lockUserProjectCustomRoles                            sync.RWMutex
	lockUserSystemRolesByExternalID                       sync.RWMutex
}

// AssignCustomRoleToOrg calls AssignCustomRoleToOrgFunc.
func (mock *MockedRoleStorer) AssignCustomRoleToOrg(ctx context.Context, userID uuid.UUID, roleID uuid.UUID, orgID int) error {
	if mock.AssignCustomRoleToOrgFunc == nil {
		panic("MockedRoleStorer.AssignCustomRoleToOrgFunc: method is nil but RoleStorer.AssignCustomRoleToOrg was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID uuid.UUID
		RoleID uuid.UUID
		OrgID  int
	}{
		Ctx:    ctx,
		UserID: userID,
		RoleID: roleID,
		OrgID:  orgID,
	}
	mock.lockAssignCustomRoleToOrg.Lock()
	mock.calls.AssignCustomRoleToOrg = append(mock.calls.AssignCustomRoleToOrg, callInfo)
	mock.lockAssignCustomRoleToOrg.Unlock()
	return mock.AssignCustomRoleToOrgFunc(ctx, userID, roleID, orgID)
}

// AssignCustomRoleToOrgCalls gets all the calls that were made to AssignCustomRoleToOrg.
// Check the length with:
//
//	len(mockedRoleStorer.AssignCustomRoleToOrgCalls())
func (mock *MockedRoleStorer) AssignCustomRoleToOrgCalls() []struct {
	Ctx    context.Context
	UserID uuid.UUID
	RoleID uuid.UUID
	OrgID  int
} {
	var calls []struct {
		Ctx    context.Context
		UserID uuid.UUID
		RoleID uuid.UUID
		OrgID  int
	}
	mock.lockAssignCustomRoleToOrg.RLock()
	calls = mock.calls.AssignCustomRoleToOrg
	mock.lockAssignCustomRoleToOrg.RUnlock()
	return calls
}

// AssignCustomRoleToProject calls AssignCustomRoleToProjectFunc.
func (mock *MockedRoleStorer) AssignCustomRoleToProject(ctx context.Context, userID uuid.UUID, roleID uuid.UUID, projectID int) error {
	if mock.AssignCustomRoleToProjectFunc == nil {
		panic("MockedRoleStorer.AssignCustomRoleToProjectFunc: method is nil but RoleStorer.AssignCustomRoleToProject was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		UserID    uuid.UUID
		RoleID    uuid.UUID
		ProjectID int
	}{
		Ctx:       ctx,
		UserID:    userID,
		RoleID:    roleID,
		ProjectID: projectID,
	}
	mock.lockAssignCustomRoleToProject.Lock()
	mock.calls.AssignCustomRoleToProject = append(mock.calls.AssignCustomRoleToProject, callInfo)
	mock.lockAssignCustomRoleToProject.Unlock()
	return mock.AssignCustomRoleToProjectFunc(ctx, userID, roleID, projectID)
}

// AssignCustomRoleToProjectCalls gets all the calls that were made to AssignCustomRoleToProject.
// Check the length with:
//
//	len(mockedRoleStorer.AssignCustomRoleToProjectCalls())
func (mock *MockedRoleStorer) AssignCustomRoleToProjectCalls() []struct {
	Ctx       context.Context
	UserID    uuid.UUID
	RoleID    uuid.UUID
	ProjectID int
} {
	var calls []struct {
		Ctx       context.Context
		UserID    uuid.UUID
		RoleID    uuid.UUID
		ProjectID int
	}
	mock.lockAssignCustomRoleToProject.RLock()
	calls = mock.calls.AssignCustomRoleToProject
	mock.lockAssignCustomRoleToProject.RUnlock()
	return calls
}

// AssignSystemRole calls AssignSystemRoleFunc.
func (mock *MockedRoleStorer) AssignSystemRole(ctx context.Context, userID uuid.UUID, roleName string) error {
	if mock.AssignSystemRoleFunc == nil {
		panic("MockedRoleStorer.AssignSystemRoleFunc: method is nil but RoleStorer.AssignSystemRole was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		UserID   uuid.UUID
		RoleName string
	}{
		Ctx:      ctx,
		UserID:   userID,
		RoleName: roleName,
	}
	mock.lockAssignSystemRole.Lock()
	mock.calls.AssignSystemRole = append(mock.calls.AssignSystemRole, callInfo)
	mock.lockAssignSystemRole.Unlock()
	return mock.AssignSystemRoleFunc(ctx, userID, roleName)
}

// AssignSystemRoleCalls gets all the calls that were made to AssignSystemRole.
// Check the length with:
//
//	len(mockedRoleStorer.AssignSystemRoleCalls())
func (mock *MockedRoleStorer) AssignSystemRoleCalls() []struct {
	Ctx      context.Context
	UserID   uuid.UUID
	RoleName string
} {
	var calls []struct {
		Ctx      context.Context
		UserID   uuid.UUID
		RoleName string
	}
	mock.lockAssignSystemRole.RLock()
	calls = mock.calls.AssignSystemRole
	mock.lockAssignSystemRole.RUnlock()
	return calls
}

// CreateCustomRole calls CreateCustomRoleFunc.
func (mock *MockedRoleStorer) CreateCustomRole(ctx context.Context, cr pgrbac.CreateCustomRole) (pgrbac.CustomRole, error) {
	if mock.CreateCustomRoleFunc == nil {
		panic("MockedRoleStorer.CreateCustomRoleFunc: method is nil but RoleStorer.CreateCustomRole was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Cr  pgrbac.CreateCustomRole
	}{
		Ctx: ctx,
		Cr:  cr,
	}
	mock.lockCreateCustomRole.Lock()
	mock.calls.CreateCustomRole = append(mock.calls.CreateCustomRole, callInfo)
	mock.lockCreateCustomRole.Unlock()
	return mock.CreateCustomRoleFunc(ctx, cr)
}

// CreateCustomRoleCalls gets all the calls that were made to CreateCustomRole.
// Check the length with:
//
//	len(mockedRoleStorer.CreateCustomRoleCalls())
func (mock *MockedRoleStorer) CreateCustomRoleCalls() []struct {
	Ctx context.Context
	Cr  pgrbac.CreateCustomRole
} {
	var calls []struct {
		Ctx context.Context
		Cr  pgrbac.CreateCustomRole
	}
	mock.lockCreateCustomRole.RLock()
	calls = mock.calls.CreateCustomRole
	mock.lockCreateCustomRole.RUnlock()
	return calls
}

// CustomRoleByExternalID calls CustomRoleByExternalIDFunc.
func (mock *MockedRoleStorer) CustomRoleByExternalID(ctx context.Context, orgID int, roleID uuid.UUID) (pgrbac.CustomRole, error) {
	if mock.CustomRoleByExternalIDFunc == nil {
		panic("MockedRoleStorer.CustomRoleByExternalIDFunc: method is nil but RoleStorer.CustomRoleByExternalID was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		OrgID  int
		RoleID uuid.UUID
	}{
		Ctx:    ctx,
		OrgID:  orgID,
		RoleID: roleID,
	}
	mock.lockCustomRoleByExternalID.Lock()
	mock.calls.CustomRoleByExternalID = append(mock.calls.CustomRoleByExternalID, callInfo)
	mock.lockCustomRoleByExternalID.Unlock()
	return mock.CustomRoleByExternalIDFunc(ctx, orgID, roleID)
}

// CustomRoleByExternalIDCalls gets all the calls that were made to CustomRoleByExternalID.
// Check the length with:
//
//	len(mockedRoleStorer.CustomRoleByExternalIDCalls())
func (mock *MockedRoleStorer) CustomRoleByExternalIDCalls() []struct {
	Ctx    context.Context
	OrgID  int
	RoleID uuid.UUID
} {
	var calls []struct {
		Ctx    context.Context
		OrgID  int
		RoleID uuid.UUID
	}
	mock.lockCustomRoleByExternalID.RLock()
	calls = mock.calls.CustomRoleByExternalID
	mock.lockCustomRoleByExternalID.RUnlock()
	return calls
}

// CustomRoles calls CustomRolesFunc.
func (mock *MockedRoleStorer) CustomRoles(ctx context.Context, orgID int, pageSize int, pageOffset int) ([]pgrbac.CustomRole, int, error) {
	if mock.CustomRolesFunc == nil {
		panic("MockedRoleStorer.CustomRolesFunc: method is nil but RoleStorer.CustomRoles was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		OrgID      int
		PageSize   int
		PageOffset int
	}{
		Ctx:        ctx,
		OrgID:      orgID,
		PageSize:   pageSize,
		PageOffset: pageOffset,
	}
	mock.lockCustomRoles.Lock()
	mock.calls.CustomRoles = append(mock.calls.CustomRoles, callInfo)
	mock.lockCustomRoles.Unlock()
	return mock.CustomRolesFunc(ctx, orgID, pageSize, pageOffset)
}

// CustomRolesCalls gets all the calls that were made to CustomRoles.
// Check the length with:
//
//	len(mockedRoleStorer.CustomRolesCalls())
func (mock *MockedRoleStorer) CustomRolesCalls() []struct {
	Ctx        context.Context
	OrgID      int
	PageSize   int
	PageOffset int
} {
	var calls []struct {
		Ctx        context.Context
		OrgID      int
		PageSize   int
		PageOffset int
	}
	mock.lockCustomRoles.RLock()
	calls = mock.calls.CustomRoles
	mock.lockCustomRoles.RUnlock()
	return calls
}

// DeleteCustomRole calls DeleteCustomRoleFunc.
func (mock *MockedRoleStorer) DeleteCustomRole(ctx context.Context, orgID int, roleID uuid.UUID) error {
	if mock.DeleteCustomRoleFunc == nil {
		panic("MockedRoleStorer.DeleteCustomRoleFunc: method is nil but RoleStorer.DeleteCustomRole was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		OrgID  int
		RoleID uuid.UUID
	}{
		Ctx:    ctx,
		OrgID:  orgID,
		RoleID: roleID,
	}
	mock.lockDeleteCustomRole.Lock()
	mock.calls.DeleteCustomRole = append(mock.calls.DeleteCustomRole, callInfo)
	mock.lockDeleteCustomRole.Unlock()
	return mock.DeleteCustomRoleFunc(ctx, orgID, roleID)
}

// DeleteCustomRoleCalls gets all the calls that were made to DeleteCustomRole.
// Check the length with:
//
//	len(mockedRoleStorer.DeleteCustomRoleCalls())
func (mock *MockedRoleStorer) DeleteCustomRoleCalls() []struct {
	Ctx    context.Context
	OrgID  int
	RoleID uuid.UUID
} {
	var calls []struct {
		Ctx    context.Context
		OrgID  int
		RoleID uuid.UUID
	}
	mock.lockDeleteCustomRole.RLock()
	calls = mock.calls.DeleteCustomRole
	mock.lockDeleteCustomRole.RUnlock()
	return calls
}

// FullyPrivilegedUserRemainsAfterSystemRoleUnassign calls FullyPrivilegedUserRemainsAfterSystemRoleUnassignFunc.
func (mock *MockedRoleStorer) FullyPrivilegedUserRemainsAfterSystemRoleUnassign(ctx context.Context, userID uuid.UUID, roleName string) (bool, error) {
	if mock.FullyPrivilegedUserRemainsAfterSystemRoleUnassignFunc == nil {
		panic("MockedRoleStorer.FullyPrivilegedUserRemainsAfterSystemRoleUnassignFunc: method is nil but RoleStorer.FullyPrivilegedUserRemainsAfterSystemRoleUnassign was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		UserID   uuid.UUID
		RoleName string
	}{
		Ctx:      ctx,
		UserID:   userID,
		RoleName: roleName,
	}
	mock.lockFullyPrivilegedUserRemainsAfterSystemRoleUnassign.Lock()
	mock.calls.FullyPrivilegedUserRemainsAfterSystemRoleUnassign = append(mock.calls.FullyPrivilegedUserRemainsAfterSystemRoleUnassign, callInfo)
	mock.lockFullyPrivilegedUserRemainsAfterSystemRoleUnassign.Unlock()
	return mock.FullyPrivilegedUserRemainsAfterSystemRoleUnassignFunc(ctx, userID, roleName)
}

// FullyPrivilegedUserRemainsAfterSystemRoleUnassignCalls gets all the calls that were made to FullyPrivilegedUserRemainsAfterSystemRoleUnassign.
// Check the length with:
//
//	len(mockedRoleStorer.FullyPrivilegedUserRemainsAfterSystemRoleUnassignCalls())
func (mock *MockedRoleStorer) FullyPrivilegedUserRemainsAfterSystemRoleUnassignCalls() []struct {
	Ctx      context.Context
	UserID   uuid.UUID
	RoleName string
} {
	var calls []struct {
		Ctx      context.Context
		UserID   uuid.UUID
		RoleName string
	}
	mock.lockFullyPrivilegedUserRemainsAfterSystemRoleUnassign.RLock()
	calls = mock.calls.FullyPrivilegedUserRemainsAfterSystemRoleUnassign
	mock.lockFullyPrivilegedUserRemainsAfterSystemRoleUnassign.RUnlock()
	return calls
}

// LockSystemRoleManagement calls LockSystemRoleManagementFunc.
func (mock *MockedRoleStorer) LockSystemRoleManagement(ctx context.Context) error {
	if mock.LockSystemRoleManagementFunc == nil {
		panic("MockedRoleStorer.LockSystemRoleManagementFunc: method is nil but RoleStorer.LockSystemRoleManagement was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockLockSystemRoleManagement.Lock()
	mock.calls.LockSystemRoleManagement = append(mock.calls.LockSystemRoleManagement, callInfo)
	mock.lockLockSystemRoleManagement.Unlock()
	return mock.LockSystemRoleManagementFunc(ctx)
}

// LockSystemRoleManagementCalls gets all the calls that were made to LockSystemRoleManagement.
// Check the length with:
//
//	len(mockedRoleStorer.LockSystemRoleManagementCalls())
func (mock *MockedRoleStorer) LockSystemRoleManagementCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockLockSystemRoleManagement.RLock()
	calls = mock.calls.LockSystemRoleManagement
	mock.lockLockSystemRoleManagement.RUnlock()
	return calls
}

// LockSystemRoleUser calls LockSystemRoleUserFunc.
func (mock *MockedRoleStorer) LockSystemRoleUser(ctx context.Context, userID uuid.UUID) error {
	if mock.LockSystemRoleUserFunc == nil {
		panic("MockedRoleStorer.LockSystemRoleUserFunc: method is nil but RoleStorer.LockSystemRoleUser was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID uuid.UUID
	}{
		Ctx:    ctx,
		UserID: userID,
	}
	mock.lockLockSystemRoleUser.Lock()
	mock.calls.LockSystemRoleUser = append(mock.calls.LockSystemRoleUser, callInfo)
	mock.lockLockSystemRoleUser.Unlock()
	return mock.LockSystemRoleUserFunc(ctx, userID)
}

// LockSystemRoleUserCalls gets all the calls that were made to LockSystemRoleUser.
// Check the length with:
//
//	len(mockedRoleStorer.LockSystemRoleUserCalls())
func (mock *MockedRoleStorer) LockSystemRoleUserCalls() []struct {
	Ctx    context.Context
	UserID uuid.UUID
} {
	var calls []struct {
		Ctx    context.Context
		UserID uuid.UUID
	}
	mock.lockLockSystemRoleUser.RLock()
	calls = mock.calls.LockSystemRoleUser
	mock.lockLockSystemRoleUser.RUnlock()
	return calls
}

// ModifyCustomRolePermissions calls ModifyCustomRolePermissionsFunc.
func (mock *MockedRoleStorer) ModifyCustomRolePermissions(ctx context.Context, mp pgrbac.ModifyCustomRolePermissions) (pgrbac.CustomRole, error) {
	if mock.ModifyCustomRolePermissionsFunc == nil {
		panic("MockedRoleStorer.ModifyCustomRolePermissionsFunc: method is nil but RoleStorer.ModifyCustomRolePermissions was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Mp  pgrbac.ModifyCustomRolePermissions
	}{
		Ctx: ctx,
		Mp:  mp,
	}
	mock.lockModifyCustomRolePermissions.Lock()
	mock.calls.ModifyCustomRolePermissions = append(mock.calls.ModifyCustomRolePermissions, callInfo)
	mock.lockModifyCustomRolePermissions.Unlock()
	return mock.ModifyCustomRolePermissionsFunc(ctx, mp)
}

// ModifyCustomRolePermissionsCalls gets all the calls that were made to ModifyCustomRolePermissions.
// Check the length with:
//
//	len(mockedRoleStorer.ModifyCustomRolePermissionsCalls())
func (mock *MockedRoleStorer) ModifyCustomRolePermissionsCalls() []struct {
	Ctx context.Context
	Mp  pgrbac.ModifyCustomRolePermissions
} {
	var calls []struct {
		Ctx context.Context
		Mp  pgrbac.ModifyCustomRolePermissions
	}
	mock.lockModifyCustomRolePermissions.RLock()
	calls = mock.calls.ModifyCustomRolePermissions
	mock.lockModifyCustomRolePermissions.RUnlock()
	return calls
}

// OrgPermissionsByProjectID calls OrgPermissionsByProjectIDFunc.
func (mock *MockedRoleStorer) OrgPermissionsByProjectID(ctx context.Context, userID uuid.UUID, projectID int) (pgrbac.OrgPermissions, error) {
	if mock.OrgPermissionsByProjectIDFunc == nil {
		panic("MockedRoleStorer.OrgPermissionsByProjectIDFunc: method is nil but RoleStorer.OrgPermissionsByProjectID was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		UserID    uuid.UUID
		ProjectID int
	}{
		Ctx:       ctx,
		UserID:    userID,
		ProjectID: projectID,
	}
	mock.lockOrgPermissionsByProjectID.Lock()
	mock.calls.OrgPermissionsByProjectID = append(mock.calls.OrgPermissionsByProjectID, callInfo)
	mock.lockOrgPermissionsByProjectID.Unlock()
	return mock.OrgPermissionsByProjectIDFunc(ctx, userID, projectID)
}

// OrgPermissionsByProjectIDCalls gets all the calls that were made to OrgPermissionsByProjectID.
// Check the length with:
//
//	len(mockedRoleStorer.OrgPermissionsByProjectIDCalls())
func (mock *MockedRoleStorer) OrgPermissionsByProjectIDCalls() []struct {
	Ctx       context.Context
	UserID    uuid.UUID
	ProjectID int
} {
	var calls []struct {
		Ctx       context.Context
		UserID    uuid.UUID
		ProjectID int
	}
	mock.lockOrgPermissionsByProjectID.RLock()
	calls = mock.calls.OrgPermissionsByProjectID
	mock.lockOrgPermissionsByProjectID.RUnlock()
	return calls
}

// ProjectPermissions calls ProjectPermissionsFunc.
func (mock *MockedRoleStorer) ProjectPermissions(ctx context.Context, userID uuid.UUID, projectID int) (pgrbac.ProjectPermissions, error) {
	if mock.ProjectPermissionsFunc == nil {
		panic("MockedRoleStorer.ProjectPermissionsFunc: method is nil but RoleStorer.ProjectPermissions was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		UserID    uuid.UUID
		ProjectID int
	}{
		Ctx:       ctx,
		UserID:    userID,
		ProjectID: projectID,
	}
	mock.lockProjectPermissions.Lock()
	mock.calls.ProjectPermissions = append(mock.calls.ProjectPermissions, callInfo)
	mock.lockProjectPermissions.Unlock()
	return mock.ProjectPermissionsFunc(ctx, userID, projectID)
}

// ProjectPermissionsCalls gets all the calls that were made to ProjectPermissions.
// Check the length with:
//
//	len(mockedRoleStorer.ProjectPermissionsCalls())
func (mock *MockedRoleStorer) ProjectPermissionsCalls() []struct {
	Ctx       context.Context
	UserID    uuid.UUID
	ProjectID int
} {
	var calls []struct {
		Ctx       context.Context
		UserID    uuid.UUID
		ProjectID int
	}
	mock.lockProjectPermissions.RLock()
	calls = mock.calls.ProjectPermissions
	mock.lockProjectPermissions.RUnlock()
	return calls
}

// SystemPermissions calls SystemPermissionsFunc.
func (mock *MockedRoleStorer) SystemPermissions(ctx context.Context, userID uuid.UUID) ([]string, error) {
	if mock.SystemPermissionsFunc == nil {
		panic("MockedRoleStorer.SystemPermissionsFunc: method is nil but RoleStorer.SystemPermissions was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID uuid.UUID
	}{
		Ctx:    ctx,
		UserID: userID,
	}
	mock.lockSystemPermissions.Lock()
	mock.calls.SystemPermissions = append(mock.calls.SystemPermissions, callInfo)
	mock.lockSystemPermissions.Unlock()
	return mock.SystemPermissionsFunc(ctx, userID)
}

// SystemPermissionsCalls gets all the calls that were made to SystemPermissions.
// Check the length with:
//
//	len(mockedRoleStorer.SystemPermissionsCalls())
func (mock *MockedRoleStorer) SystemPermissionsCalls() []struct {
	Ctx    context.Context
	UserID uuid.UUID
} {
	var calls []struct {
		Ctx    context.Context
		UserID uuid.UUID
	}
	mock.lockSystemPermissions.RLock()
	calls = mock.calls.SystemPermissions
	mock.lockSystemPermissions.RUnlock()
	return calls
}

// SystemRoleByName calls SystemRoleByNameFunc.
func (mock *MockedRoleStorer) SystemRoleByName(ctx context.Context, name string) (pgrbac.SystemRole, error) {
	if mock.SystemRoleByNameFunc == nil {
		panic("MockedRoleStorer.SystemRoleByNameFunc: method is nil but RoleStorer.SystemRoleByName was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Name string
	}{
		Ctx:  ctx,
		Name: name,
	}
	mock.lockSystemRoleByName.Lock()
	mock.calls.SystemRoleByName = append(mock.calls.SystemRoleByName, callInfo)
	mock.lockSystemRoleByName.Unlock()
	return mock.SystemRoleByNameFunc(ctx, name)
}

// SystemRoleByNameCalls gets all the calls that were made to SystemRoleByName.
// Check the length with:
//
//	len(mockedRoleStorer.SystemRoleByNameCalls())
func (mock *MockedRoleStorer) SystemRoleByNameCalls() []struct {
	Ctx  context.Context
	Name string
} {
	var calls []struct {
		Ctx  context.Context
		Name string
	}
	mock.lockSystemRoleByName.RLock()
	calls = mock.calls.SystemRoleByName
	mock.lockSystemRoleByName.RUnlock()
	return calls
}

// SystemRoles calls SystemRolesFunc.
func (mock *MockedRoleStorer) SystemRoles(ctx context.Context, pageSize int, pageOffset int) ([]pgrbac.SystemRole, int, error) {
	if mock.SystemRolesFunc == nil {
		panic("MockedRoleStorer.SystemRolesFunc: method is nil but RoleStorer.SystemRoles was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		PageSize   int
		PageOffset int
	}{
		Ctx:        ctx,
		PageSize:   pageSize,
		PageOffset: pageOffset,
	}
	mock.lockSystemRoles.Lock()
	mock.calls.SystemRoles = append(mock.calls.SystemRoles, callInfo)
	mock.lockSystemRoles.Unlock()
	return mock.SystemRolesFunc(ctx, pageSize, pageOffset)
}

// SystemRolesCalls gets all the calls that were made to SystemRoles.
// Check the length with:
//
//	len(mockedRoleStorer.SystemRolesCalls())
func (mock *MockedRoleStorer) SystemRolesCalls() []struct {
	Ctx        context.Context
	PageSize   int
	PageOffset int
} {
	var calls []struct {
		Ctx        context.Context
		PageSize   int
		PageOffset int
	}
	mock.lockSystemRoles.RLock()
	calls = mock.calls.SystemRoles
	mock.lockSystemRoles.RUnlock()
	return calls
}

// UnassignCustomRoleFromOrg calls UnassignCustomRoleFromOrgFunc.
func (mock *MockedRoleStorer) UnassignCustomRoleFromOrg(ctx context.Context, userID uuid.UUID, roleID uuid.UUID, orgID int) error {
	if mock.UnassignCustomRoleFromOrgFunc == nil {
		panic("MockedRoleStorer.UnassignCustomRoleFromOrgFunc: method is nil but RoleStorer.UnassignCustomRoleFromOrg was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID uuid.UUID
		RoleID uuid.UUID
		OrgID  int
	}{
		Ctx:    ctx,
		UserID: userID,
		RoleID: roleID,
		OrgID:  orgID,
	}
	mock.lockUnassignCustomRoleFromOrg.Lock()
	mock.calls.UnassignCustomRoleFromOrg = append(mock.calls.UnassignCustomRoleFromOrg, callInfo)
	mock.lockUnassignCustomRoleFromOrg.Unlock()
	return mock.UnassignCustomRoleFromOrgFunc(ctx, userID, roleID, orgID)
}

// UnassignCustomRoleFromOrgCalls gets all the calls that were made to UnassignCustomRoleFromOrg.
// Check the length with:
//
//	len(mockedRoleStorer.UnassignCustomRoleFromOrgCalls())
func (mock *MockedRoleStorer) UnassignCustomRoleFromOrgCalls() []struct {
	Ctx    context.Context
	UserID uuid.UUID
	RoleID uuid.UUID
	OrgID  int
} {
	var calls []struct {
		Ctx    context.Context
		UserID uuid.UUID
		RoleID uuid.UUID
		OrgID  int
	}
	mock.lockUnassignCustomRoleFromOrg.RLock()
	calls = mock.calls.UnassignCustomRoleFromOrg
	mock.lockUnassignCustomRoleFromOrg.RUnlock()
	return calls
}

// UnassignCustomRoleFromProject calls UnassignCustomRoleFromProjectFunc.
func (mock *MockedRoleStorer) UnassignCustomRoleFromProject(ctx context.Context, userID uuid.UUID, roleID uuid.UUID, projectID int) error {
	if mock.UnassignCustomRoleFromProjectFunc == nil {
		panic("MockedRoleStorer.UnassignCustomRoleFromProjectFunc: method is nil but RoleStorer.UnassignCustomRoleFromProject was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		UserID    uuid.UUID
		RoleID    uuid.UUID
		ProjectID int
	}{
		Ctx:       ctx,
		UserID:    userID,
		RoleID:    roleID,
		ProjectID: projectID,
	}
	mock.lockUnassignCustomRoleFromProject.Lock()
	mock.calls.UnassignCustomRoleFromProject = append(mock.calls.UnassignCustomRoleFromProject, callInfo)
	mock.lockUnassignCustomRoleFromProject.Unlock()
	return mock.UnassignCustomRoleFromProjectFunc(ctx, userID, roleID, projectID)
}

// UnassignCustomRoleFromProjectCalls gets all the calls that were made to UnassignCustomRoleFromProject.
// Check the length with:
//
//	len(mockedRoleStorer.UnassignCustomRoleFromProjectCalls())
func (mock *MockedRoleStorer) UnassignCustomRoleFromProjectCalls() []struct {
	Ctx       context.Context
	UserID    uuid.UUID
	RoleID    uuid.UUID
	ProjectID int
} {
	var calls []struct {
		Ctx       context.Context
		UserID    uuid.UUID
		RoleID    uuid.UUID
		ProjectID int
	}
	mock.lockUnassignCustomRoleFromProject.RLock()
	calls = mock.calls.UnassignCustomRoleFromProject
	mock.lockUnassignCustomRoleFromProject.RUnlock()
	return calls
}

// UnassignSystemRole calls UnassignSystemRoleFunc.
func (mock *MockedRoleStorer) UnassignSystemRole(ctx context.Context, userID uuid.UUID, roleName string) error {
	if mock.UnassignSystemRoleFunc == nil {
		panic("MockedRoleStorer.UnassignSystemRoleFunc: method is nil but RoleStorer.UnassignSystemRole was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		UserID   uuid.UUID
		RoleName string
	}{
		Ctx:      ctx,
		UserID:   userID,
		RoleName: roleName,
	}
	mock.lockUnassignSystemRole.Lock()
	mock.calls.UnassignSystemRole = append(mock.calls.UnassignSystemRole, callInfo)
	mock.lockUnassignSystemRole.Unlock()
	return mock.UnassignSystemRoleFunc(ctx, userID, roleName)
}

// UnassignSystemRoleCalls gets all the calls that were made to UnassignSystemRole.
// Check the length with:
//
//	len(mockedRoleStorer.UnassignSystemRoleCalls())
func (mock *MockedRoleStorer) UnassignSystemRoleCalls() []struct {
	Ctx      context.Context
	UserID   uuid.UUID
	RoleName string
} {
	var calls []struct {
		Ctx      context.Context
		UserID   uuid.UUID
		RoleName string
	}
	mock.lockUnassignSystemRole.RLock()
	calls = mock.calls.UnassignSystemRole
	mock.lockUnassignSystemRole.RUnlock()
	return calls
}

// UpdateCustomRole calls UpdateCustomRoleFunc.
func (mock *MockedRoleStorer) UpdateCustomRole(ctx context.Context, ur pgrbac.UpdateCustomRole) (pgrbac.CustomRole, error) {
	if mock.UpdateCustomRoleFunc == nil {
		panic("MockedRoleStorer.UpdateCustomRoleFunc: method is nil but RoleStorer.UpdateCustomRole was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Ur  pgrbac.UpdateCustomRole
	}{
		Ctx: ctx,
		Ur:  ur,
	}
	mock.lockUpdateCustomRole.Lock()
	mock.calls.UpdateCustomRole = append(mock.calls.UpdateCustomRole, callInfo)
	mock.lockUpdateCustomRole.Unlock()
	return mock.UpdateCustomRoleFunc(ctx, ur)
}

// UpdateCustomRoleCalls gets all the calls that were made to UpdateCustomRole.
// Check the length with:
//
//	len(mockedRoleStorer.UpdateCustomRoleCalls())
func (mock *MockedRoleStorer) UpdateCustomRoleCalls() []struct {
	Ctx context.Context
	Ur  pgrbac.UpdateCustomRole
} {
	var calls []struct {
		Ctx context.Context
		Ur  pgrbac.UpdateCustomRole
	}
	mock.lockUpdateCustomRole.RLock()
	calls = mock.calls.UpdateCustomRole
	mock.lockUpdateCustomRole.RUnlock()
	return calls
}

// UserOrgCustomRoles calls UserOrgCustomRolesFunc.
func (mock *MockedRoleStorer) UserOrgCustomRoles(ctx context.Context, userID uuid.UUID, orgID int, pageSize int, pageOffset int) ([]pgrbac.CustomRole, int, error) {
	if mock.UserOrgCustomRolesFunc == nil {
		panic("MockedRoleStorer.UserOrgCustomRolesFunc: method is nil but RoleStorer.UserOrgCustomRoles was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		UserID     uuid.UUID
		OrgID      int
		PageSize   int
		PageOffset int
	}{
		Ctx:        ctx,
		UserID:     userID,
		OrgID:      orgID,
		PageSize:   pageSize,
		PageOffset: pageOffset,
	}
	mock.lockUserOrgCustomRoles.Lock()
	mock.calls.UserOrgCustomRoles = append(mock.calls.UserOrgCustomRoles, callInfo)
	mock.lockUserOrgCustomRoles.Unlock()
	return mock.UserOrgCustomRolesFunc(ctx, userID, orgID, pageSize, pageOffset)
}

// UserOrgCustomRolesCalls gets all the calls that were made to UserOrgCustomRoles.
// Check the length with:
//
//	len(mockedRoleStorer.UserOrgCustomRolesCalls())
func (mock *MockedRoleStorer) UserOrgCustomRolesCalls() []struct {
	Ctx        context.Context
	UserID     uuid.UUID
	OrgID      int
	PageSize   int
	PageOffset int
} {
	var calls []struct {
		Ctx        context.Context
		UserID     uuid.UUID
		OrgID      int
		PageSize   int
		PageOffset int
	}
	mock.lockUserOrgCustomRoles.RLock()
	calls = mock.calls.UserOrgCustomRoles
	mock.lockUserOrgCustomRoles.RUnlock()
	return calls
}

// UserProjectCustomRoles calls UserProjectCustomRolesFunc.
func (mock *MockedRoleStorer) UserProjectCustomRoles(ctx context.Context, userID uuid.UUID, projectID int, pageSize int, pageOffset int) ([]pgrbac.CustomRole, int, error) {
	if mock.UserProjectCustomRolesFunc == nil {
		panic("MockedRoleStorer.UserProjectCustomRolesFunc: method is nil but RoleStorer.UserProjectCustomRoles was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		UserID     uuid.UUID
		ProjectID  int
		PageSize   int
		PageOffset int
	}{
		Ctx:        ctx,
		UserID:     userID,
		ProjectID:  projectID,
		PageSize:   pageSize,
		PageOffset: pageOffset,
	}
	mock.lockUserProjectCustomRoles.Lock()
	mock.calls.UserProjectCustomRoles = append(mock.calls.UserProjectCustomRoles, callInfo)
	mock.lockUserProjectCustomRoles.Unlock()
	return mock.UserProjectCustomRolesFunc(ctx, userID, projectID, pageSize, pageOffset)
}

// UserProjectCustomRolesCalls gets all the calls that were made to UserProjectCustomRoles.
// Check the length with:
//
//	len(mockedRoleStorer.UserProjectCustomRolesCalls())
func (mock *MockedRoleStorer) UserProjectCustomRolesCalls() []struct {
	Ctx        context.Context
	UserID     uuid.UUID
	ProjectID  int
	PageSize   int
	PageOffset int
} {
	var calls []struct {
		Ctx        context.Context
		UserID     uuid.UUID
		ProjectID  int
		PageSize   int
		PageOffset int
	}
	mock.lockUserProjectCustomRoles.RLock()
	calls = mock.calls.UserProjectCustomRoles
	mock.lockUserProjectCustomRoles.RUnlock()
	return calls
}

// UserSystemRolesByExternalID calls UserSystemRolesByExternalIDFunc.
func (mock *MockedRoleStorer) UserSystemRolesByExternalID(ctx context.Context, userID uuid.UUID, pageSize int, pageOffset int) ([]pgrbac.SystemRole, int, error) {
	if mock.UserSystemRolesByExternalIDFunc == nil {
		panic("MockedRoleStorer.UserSystemRolesByExternalIDFunc: method is nil but RoleStorer.UserSystemRolesByExternalID was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		UserID     uuid.UUID
		PageSize   int
		PageOffset int
	}{
		Ctx:        ctx,
		UserID:     userID,
		PageSize:   pageSize,
		PageOffset: pageOffset,
	}
	mock.lockUserSystemRolesByExternalID.Lock()
	mock.calls.UserSystemRolesByExternalID = append(mock.calls.UserSystemRolesByExternalID, callInfo)
	mock.lockUserSystemRolesByExternalID.Unlock()
	return mock.UserSystemRolesByExternalIDFunc(ctx, userID, pageSize, pageOffset)
}

// UserSystemRolesByExternalIDCalls gets all the calls that were made to UserSystemRolesByExternalID.
// Check the length with:
//
//	len(mockedRoleStorer.UserSystemRolesByExternalIDCalls())
func (mock *MockedRoleStorer) UserSystemRolesByExternalIDCalls() []struct {
	Ctx        context.Context
	UserID     uuid.UUID
	PageSize   int
	PageOffset int
} {
	var calls []struct {
		Ctx        context.Context
		UserID     uuid.UUID
		PageSize   int
		PageOffset int
	}
	mock.lockUserSystemRolesByExternalID.RLock()
	calls = mock.calls.UserSystemRolesByExternalID
	mock.lockUserSystemRolesByExternalID.RUnlock()
	return calls
}
