// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package rbac

import (
	"context"
	"sync"

	"github.com/google/uuid"
	"github.com/zorcal/theapp/backend/internal/core/pgstores/pguser"
)

// Ensure, that MockedUserStorer does implement UserStorer.
// If this is not the case, regenerate this file with moq.
var _ UserStorer = &MockedUserStorer{}

// MockedUserStorer is a mock implementation of UserStorer.
//
//	func TestSomethingThatUsesUserStorer(t *testing.T) {
//
//		// make and configure a mocked UserStorer
//		mockedUserStorer := &MockedUserStorer{
//			UserByExternalIDFunc: func(ctx context.Context, id uuid.UUID) (pguser.User, error) {
//				panic("mock out the UserByExternalID method")
//			},
//		}
//
//		// use mockedUserStorer in code that requires UserStorer
//		// and then make assertions.
//
//	}
type MockedUserStorer struct {
	// UserByExternalIDFunc mocks the UserByExternalID method.
	UserByExternalIDFunc func(ctx context.Context, id uuid.UUID) (pguser.User, error)

	// calls tracks calls to the methods.
	calls struct {
		// UserByExternalID holds details about calls to the UserByExternalID method.
		UserByExternalID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
		}
	}
	lockUserByExternalID sync.RWMutex
}

// UserByExternalID calls UserByExternalIDFunc.
func (mock *MockedUserStorer) UserByExternalID(ctx context.Context, id uuid.UUID) (pguser.User, error) {
	if mock.UserByExternalIDFunc == nil {
		panic("MockedUserStorer.UserByExternalIDFunc: method is nil but UserStorer.UserByExternalID was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  uuid.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockUserByExternalID.Lock()
	mock.calls.UserByExternalID = append(mock.calls.UserByExternalID, callInfo)
	mock.lockUserByExternalID.Unlock()
	return mock.UserByExternalIDFunc(ctx, id)
}

// UserByExternalIDCalls gets all the calls that were made to UserByExternalID.
// Check the length with:
//
//	len(mockedUserStorer.UserByExternalIDCalls())
func (mock *MockedUserStorer) UserByExternalIDCalls() []struct {
	Ctx context.Context
	ID  uuid.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  uuid.UUID
	}
	mock.lockUserByExternalID.RLock()
	calls = mock.calls.UserByExternalID
	mock.lockUserByExternalID.RUnlock()
	return calls
}
